packages/gcf-utils/package.json
packages/gcf-utils/src/bin/genkey.ts

Added new bin: `genkey`, which will build and encrypt a set of
configuration options and upload them to a GCS bucket.

feat(gcf-utils): Utility to add/upload probot secrets.

---

packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
packages/conventional-commit-lint/package.json
packages/conventional-commit-lint/src/conventional-commit-lint.ts
packages/conventional-commit-lint/test/conventional-commit-lint.ts
packages/conventional-commit-lint/test/fixtures/pull_request_synchronize_invalid_title.json
packages/gcf-utils/src/bin/genkey.ts

A couple changes to make the commit lint bot a bit less of a pain:
1. if more than one commit exists on the PR,  we now lint the title rather than all commits.
1. we support the new `!` syntax on a commit title.
1. we no longer enforce a set of types (since this goes against the goals of conventionalcommits.org, which aims to be mellow).

feat: lint title if more than 1 commit exists

---

packages/header-checker-lint/__snapshots__/header-checker-lint.js
packages/header-checker-lint/src/header-checker-lint.ts
packages/header-checker-lint/test/header-checker-lint.ts

We have _a lot_ of copyright holder stanzas that are slightly off (it's creating busy work for every PR today).
Let's only apply this logic for new files that are added for now.

fix: don't enforce ALLOWED_COPYRIGHT_HOLDERS on updates (yet)

---

packages/header-checker-lint/README.md
packages/header-checker-lint/__snapshots__/header-checker-lint.js
packages/header-checker-lint/src/header-checker-lint.ts
packages/header-checker-lint/test/fixtures/config_copyright_holder.json
packages/header-checker-lint/test/header-checker-lint.ts

The bot now reads a `.bots/header-checker-lint.json` file for configuration. If available, it will set the override the default configuration with values from this json file. If not available, it will use the default configuration.

feat: add header-checker-lint options file

---

packages/header-checker-lint/package.json

fix: add minimatch dependencies to header-checker-lint

---

packages/header-checker-lint/src/header-checker-lint.ts
packages/header-checker-lint/src/header-parser.ts
packages/header-checker-lint/test/fixtures/bash-style-header.txt
packages/header-checker-lint/test/fixtures/c-style-header-all-rights.txt
packages/header-checker-lint/test/fixtures/c-style-header-extended.txt
packages/header-checker-lint/test/fixtures/c-style-header.txt
packages/header-checker-lint/test/fixtures/inline-java-style-header.txt
packages/header-checker-lint/test/header-parser.ts

The header format with `All Rights Reserved.` fails to match the current regex.
` * Copyright 2019 Google LLC. All Rights Reserved.`

fix: copyright detection

---

packages/release-please/src/app.ts

This fixes the deployment to allow the cloud function bootstrapper to find this function.

fix: release-please bot entrypoint name

---

cloudbuild.yaml

Builds default to 10 minutes. If each function takes ~2 minutes to deploy, we will  hit the timeout at 5 functions. 
Increase timeout to 20 minutes

fix(cloudbuild): increase build timeout

---

packages/release-please/package.json

Not sure why renovate doesn't update these packages.

chore(deps): update release-please to 2.10.1

---

packages/blunderbuss/package.json
packages/conventional-commit-lint/package.json
packages/header-checker-lint/package.json
packages/header-checker-lint/src/header-checker-lint.ts
packages/release-please/package.json

`probot` is guaranteed to pull `@octokit` into our dependency graph, so there's no need to explicitly install it.
This should prevent the two octokit versions from getting out of sync.
fixes https://github.com/googleapis/repo-automation-bots/issues/91

refactor: we can trust that @octokit/rest exists

---

packages/release-please/src/release-please.ts
packages/release-please/test/fixtures/config/ruby_release_alternate_pkg_name.yml
packages/release-please/test/release-please.ts

we were failing to update `sample/package.json`, because the `packageName` and `repoName` are different for Node.js.
I also added some logging so it's easier to dig into publication issues.

fix: Node repo and package name are different

---

packages/trusted-contribution/src/trusted-contribution.ts

It's possible there are jobs that need `force`, but the the repos I've seen have all worked with `kokoro:run`. Can switch back if this doesn't work as expected.

fix(trusted-contribution): use kokoro:run instead of kokoro:force-run

---

.gitignore
package-lock.json
packages/conventional-commit-lint/package-lock.json
packages/gcf-utils/package-lock.json
packages/header-checker-lint/package-lock.json
packages/release-please/package-lock.json
packages/trusted-contribution/package-lock.json

It's my hope that we will be able to start using some bots contributed by the community.
I'm _specifically_ interested in trying out this bot that was written to support reminders:
https://github.com/probot/reminders
One concern with using community contributed bots (which we're actually already susceptible to) are [dependency poisoning attacks](https://nakedsecurity.sophos.com/2019/06/10/thwarted-cryptocurrency-attack-shows-importance-of-testing-open-source-code/). By adding, and grooming a `package-lock.json`, we can be more explicit about updating deep dependencies.

feat: adds package-lock.json to make upgrades more explicit

---

packages/release-please/README.md
packages/release-please/package-lock.json
packages/release-please/package.json
packages/release-please/src/release-please.ts
packages/release-please/src/runner.ts
packages/release-please/test/fixtures/config/ruby_release.yml
packages/release-please/test/fixtures/config/valid_handle_gh_release.yml
packages/release-please/test/release-please.ts

This adds support to our bot for creating GitHub releases, if `handleGHRelease` is set to `true`.
This is exciting to me because it allows me to start adding release-please to non-autorelease repos, e.g., [yargs](https://github.com/yargs/yargs/pull/1462).
---
This also updates the version of `release-please` used by by the bot, which has additional functionality added for @TheRoyalTnetennba; Ruby will be using the `Ruby` release type for the bot, not `RubyYoshi`.

feat: support for GitHub releases and Ruby

---

package-lock.json
packages/header-checker-lint/README.md
packages/header-checker-lint/src/header-checker-lint.ts
packages/release-please/src/release-please.ts

[google-gax](https://github.com/googleapis/gax-nodejs) was originally released with BSD license, so the bot constantly feels unhappy about its sources. Let's allow BSD since it's an approved license as well.

fix: allow BSD license

---

scripts/cron-deploy.sh

`scheduler` expects the flag `--headers` not `--header`.

fix: should be --headers not --header

---

scripts/cron-deploy.sh

`functionname` was being invoked as a bin, rather than as a variable.

fix: functionname is variable not bin

---

scripts/cron-deploy.sh

I noticed our functioning scheduler URL has a `/0` suffix.

fix: proxyurl should have /v0 suffix for posts

---

packages/gcf-utils/src/bin/genkey.ts

Our older credential files are not base64 encoded at rest, the current iteration of the `genkey.ts` tool seems to store the credentials encoded, which leads to failures loading the credentials.

fix: credentials should not be base64 encoded when stored

---

serverless-scheduler-proxy/main.go

we were still referencing `botname` in JSON rather than `Name`.

fix: address naming issues with payload

---

packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts

@tbpg this adds support for the `pubsub.message` message type, a couple notes:
1. it takes care of parsing `body.message.data` for you, so in your bot you should just assume you've gotten the parsed JavaScript object represented by `data`.
2. you must set a top level key `repo` in the message you dispatch, it uses this to decide what repo the cloud function is running for.

feat: make gcf-utils work with pubsub

---

packages/buildcop/package-lock.json
packages/buildcop/package.json
packages/buildcop/src/app.ts
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

I also renamed the app to `buildcop` and adjusted exports so I could use `BuildCopPayload` from tests. Let me know if there is a better way to do that -- wasn't sure the correct way.
Updates #178.

fix: slight changes to payload format, based on testing

---

packages/trusted-contribution/src/trusted-contribution.ts

I think there's a chance that the `edited` action might fire when a force push happens from renovate; In case this isn't the case, I've also added additional logging so that we can continue to perfect the events we listen on.
see: https://github.com/googleapis/repo-automation-bots/issues/198

feat: listen on edited action

---

packages/header-checker-lint/src/header-parser.ts
packages/header-checker-lint/test/fixtures/inline-java-style-header-date-range.txt
packages/header-checker-lint/test/header-parser.ts

Fixes https://github.com/googleapis/repo-automation-bots/issues/207

fix(header-checker-lint): allow for copyright date ranges

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

This adds a new boolean field to the Pub/Sub payload: `testsFailed`.
If `xunitXML` is set, `testsFailed` is ignored. Otherwise, `testsFailed` indicates if any test failed (maybe it should be `buildFailed`?)
I also updated the issue labels to automatically add `type: bug` and `priority: p1`. There is some extra logic for searching issues only based on the `buildcop:issue` label.
Fixes #217.

feat: make buildcop XML optional

---

README.md

the publish bot wasn't documented in the top-level README.

docs: add the publish bot to the README

---

packages/header-checker-lint/__snapshots__/header-checker-lint.js
packages/header-checker-lint/src/header-checker-lint.ts
packages/header-checker-lint/test/fixtures/deleted_file_ignored.json
packages/header-checker-lint/test/header-checker-lint.ts

fixes #222 - Ensures the header lint checker skips deleted files

fix: ensure header check ignores deleted files

---

packages/label-sync/src/label-sync.ts

For our split-repos, there's no need to populate all repos, instead let's populate the one label that is associated with the given repo.
For mono-repos we will still populate all labels. I have also updated the backfilling logic slightly, so that it doesn't perform hundreds of requests in parallel.

feat: only populate one label for split-repos

---

packages/label-sync/src/label-sync.ts

repos might be tracked but not have a product label associated with them.

fix: labels can be blank for repo

---

packages/label-sync/src/label-sync.ts

caching was interfering with our ability to return labels based on the context of the repo firing a webhook, this lead to the label for the first repo invoking the cloud function to be applied to subsequent calls.

fix: labels from first invocation were being applied to future calls

---

packages/auto-label/package.json
packages/auto-label/src/auto-label.ts

we're currently having deployment failures due to reliance on a file in `src/`, whereas we only upload `build/`.

fix: published cloud functions do not include src/

---

.github/workflows/ci.yml

To divide up load, and to make it easier to update the testing matrix, experimenting with GitHub actions for CI.

build: introducing GitHub actions for unit tests

---

.github/workflows/ci.yml

Let's try using `push` only rather than `pull_request` and `push`.

chore: set config to push only

---

.github/workflows/ci.yml

codecov was uploading a bunch of the wrong files, let's be more specific.

build: codecov was finding the wrong JSON files

---

packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
packages/conventional-commit-lint/src/conventional-commit-lint.ts
packages/conventional-commit-lint/test/fixtures/pull_request_synchronize.json

The Conventional Commit specification indicates:
"Any casing may be used, but it’s best to be consistent."
fixes #59

fix: ignore case when linting commit messages

---

packages/trusted-contribution/README.md
packages/trusted-contribution/src/trusted-contribution.ts
packages/trusted-contribution/test/fixtures/custom.yml
packages/trusted-contribution/test/fixtures/no-contributors.yml
packages/trusted-contribution/test/trusted-contribution.ts

This allows repos to opt-out of the functionality by explicitly configuring an empty list of `trustedContributors` via the `.github/trusted-contribution.yml` configuration file. You can also customize the list by specifying your own list of usernames to allow (replaces the default list rather than merging).
We could make the entire bot do nothing in the absence of a configuration (like release-please), but that is not included in this PR.
For context, we would like to not automatically run the tests for `release-please[bot]` PRs in java as it can overwhelm CI.
The current default behavior (i.e. no configuration file) is preserved.

feat(trusted_contribution): allow customizing list of trusted contributors

---

packages/failurechecker/package.json
packages/generate-bot/templates/package.json
packages/header-checker-lint/package.json
packages/label-sync/package.json
packages/publish/package.json
packages/release-please/package.json
packages/trusted-contribution/package.json

updates release-please, addressing https://github.com/googleapis/repo-automation-bots/issues/277.
also removes `probot` dependency, which we get implicitly through `gcf-utils` (there were annoying TypeScript build issues due to these versions sometimes getting out of whack).

fix: new release-please with fix for Python

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

If the bot reopens an issue, it marks it as flaky then stops commenting
on it and will not close it.
If a flaky test is closed (by a human) then fails again, it will be reopened.
Fixes #281.

feat(Build Cop): handle flaky tests

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

feat(Build Cop): handle issue pagination and duplicates

---

packages/buildcop/package.json
packages/buildcop/src/buildcop.ts
packages/buildcop/src/main.ts
packages/buildcop/test/buildcop.ts

Local development wasn't working because `buildcop.ts` doesn't have the Probot app as the default export. I found the `main.ts` pattern [in the Probot docs](https://probot.github.io/docs/development/#alternate-way-of-running-a-probot-app), adapted it for this, and it works.
That local development was how I figured out the payload for labels was not correct, so issues were never detected as flaky.
Fixes #281 🦕

fix(Build Cop): fix flaky detection, fix local dev

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

Otherwise, if there are 50 invocations of the bot at the same time, they
will all try to close the duplicate issues. This isn't perfect, but will
be way better than 50.
Fixes #283 🦕

fix(Build Cop): only close duplicates when the test was run

---

scripts/cron-deploy.sh

there was a missing `]` in the deploy script.

fix: missing ] breaking deploy

---

packages/merge-on-green/src/merge-logic.ts
packages/merge-on-green/test/merge-on-green.ts

-addressing bug #305 and bug #304

fix: update branch was being called too often (bonus, also loosened strictness of review check)

---

packages/buildcop/README.md
packages/buildcop/buildcop.sh

The script is currently in GoogleCloudPlatform/golang-samples. We should
move it here to keep everything together.
`buildcop.sh` has already been copied to the `trampoline` directory and is being used by a few repos.
We might want to tie this "deploy" to the repo's deployment tools. But, for now, I'm intentionally leaving it out so we can copy ad-hoc as we make changes.

feat(Build Cop): add buildcop.sh script

---

packages/merge-on-green/src/merge-logic.ts
packages/merge-on-green/src/merge-on-green.ts
packages/merge-on-green/test/merge-on-green.ts

The underlying problem with `automerge` on `GoogleCloudPlatform` was that it has a different installation ID than `googleapis`, and we weren't clever enough to support this. We now have a cron setup for both `GoogleCloudPlatform` and for `googleapis`, each with a different installation ID.
This was the quickest fix, we may want to revisit this design in `gcf-utils` in the future, and make it so that a single cron can have multiple `installation` IDs, this would take quite a few finicky changes though.

fix: filter to org in payload

---

cloudbuild.yaml

this seems to have bene a regression (we extended this time already).

fix: deploy takes >20m now

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

fix(Build Cop): keep existing labels when marking as flaky

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

* If a test passes and fails in the same build, mark the issue as flaky. That way, we will stop commenting on it.
* Only comment once per build about a failure. This means we will possibly make more API calls, but I think it's OK. We only get the issues for failing tests that failed again, in which case we were already commenting that it failed again. But, sometimes, we won't comment again (because there is already a failure comment).
* Some python-docs-samples issues get spammed by 4+ comments for the same build ID.
I also fixed a bug where we would `return` too early after finding a flaky issue. Switched to a `continue` to continue processing the rest of the issues.
Updates #282 🦕
Note: I plan to mark this issue as fixed if this PR sufficiently reduces the amount of noise.

fix(Build Cop): make fewer comments

---

packages/merge-on-green/src/merge-logic.ts

I observed this recently trying to automerge [these PRs](https://github.com/googleapis/nodejs-recommender/pull/28), we saw the error:
`failed to merge "'commit_message' cannot be null: " googleapis/nodejs-asset/269`, @chingor13 saw similar behavior yesterday.
I've confirmed this fix, it must be that GitHub is returning `null`.

fix: GitHub API can return a null value for body, breaking merge logic

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

I noticed https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2999#issuecomment-591736913 looks a little weird saying it's flaky without giving the context that it passed in another build. It would be helpful to include that info.
Also, https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2822#issuecomment-591742480 is an example of a duplicate failure comment when there are many comments on the issue. The default page size is 30 and we weren't handling pagination before this, so we didn't find the previous failure message then made a duplicate comment.
Updates #282.

fix(Build Cop): handle comment pagination and elaborate on flaky issues

---

synth.py

I noticed in #110 synth was still trying to synchronize kokoro, and was trying to sync up github workflows.  Trying to see if this works.

build: ignore synth workflows

---

renovate.json

See https://docs.renovatebot.com/configuration-options/#packagerules.

chore(deps): only update google.golang.org/genproto once per week

---

packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

Example this will shorten (will deal with renaming/duplicates manually): https://github.com/googleapis/google-cloud-go/issues/1836

fix(Build Cop): shorten cloud.google.com/go tests

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

Once this is fully deployed and we're sure no more builds will send the
buildID field, we can delete it.
Updates #393.

chore(Build Cop): rename build ID to commit

---

packages/buildcop/README.md
packages/buildcop/buildcop.go
packages/buildcop/buildcop_test.go

When you're adding the bot to a repo, you usually want to test that it works on a PR. But, it's easy to forget until you get an error that the repo could not be detected. So, you add the `-repo` flag and try again, and will probably leave it forever, because why risk another build just to remove a flag that definitely works.
This PR adds repo detection for PRs and simplifies the process.
Updates #355.

feat(Build Cop): check for KOKORO_GITHUB_PULL_REQUEST_URL

---

packages/sync-repo-settings/src/required-checks.json
packages/sync-repo-settings/test/test.ts

I'm not sure how this isn't a problem yet 🤣

fix: do not require node8 status checks

---

packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts
packages/buildcop/test/fixtures/testdata/empty_results.xml

Some logs have empty testsuites and they were causing errors.
Before, every invocation would comment about the same issues being flaky
and not closing them. By moving it below the pass/fail check, we'll only
log the message when the test explicitly passed.
I added the build URL to a few log messages to be able to look up the
corresponding build and raw XML output.
I also added a log message to the very beginning of the invocation to
make it easier to correlate particular builds with errors.

fix(Build Cop): check for undefined suites and clean up logging

---

scripts/serverless-scheduler-proxy-deploy.sh

this makes `npm i` inside a cloud function run out of memory.

fix: do not install chromium in bots

---

packages/merge-on-green/src/merge-logic.ts
packages/merge-on-green/src/merge-on-green.ts
packages/merge-on-green/test/merge-on-green.ts

This seems to be breaking merge on green, with:
```
Error in getting statuses: TypeError: Cannot read property 'context' of undefined
```
Reverts googleapis/repo-automation-bots#440

Revert "fix(merge-on-green): address bugs related to status check name detection"

---

packages/buildcop/test/buildcop.ts
packages/buildcop/test/fixtures/testdata/no_tests.xml

I also replaced `tbpg` with `GoogleCloudPlatform`. `java-vision` is not in `GoogleCloudPlatform`, but that's OK.
Fixes #448.

chore(Build Cop): refactor tests to reduce duplication

---

packages/buildcop/README.md
packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

Locked issues shouldn't be reopened.
Issues that have been closed for more than 10 days (chosen arbitrarily) will also stay closed after this change.
I included a link to the old issue when opening a new one. It might be relevant to see the history of a given test when working on a new fix.
Fixes #444.
Unrelated change: I added an extra test case to verify the bot doesn't comment on issues about failures for the same build.

feat(Build Cop): don't mark locked and old issues as flaky

---

scripts/publish-functions.sh

address bug with task queue creation.

fix: max-dispatches-per-second is 500,  no parenthesis needed

---

scripts/publish-functions.sh

paren was in wrong spot so `$functioname` was not defined.

fix: closing paren should be after deploy_queue

---

packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
scripts/publish-functions.sh

queues have stricter rules about naming than functions:
```
ERROR: (gcloud.tasks.queues.create) INVALID_ARGUMENT: Queue ID "auto_label" can contain only letters ([A-Za-z]), numbers ([0-9]), or hyphens (-). Queue ID must be between 1 and 100 characters.
```

fix: queue name rules

---

scripts/publish-functions.sh

functions are expected to always have `_`, whereas queues don't support an `_`.

fix: queue naming logic and function naming logic are opposite

---

packages/publish/src/publish.ts

having a token already named publish caused issues for @orthros's migration to Secret Manager for secrets in general.

fix: switch to new default publish token

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

Fixes #513.
cc @ace-n (GitHub won't let me add you as a reviewer)
Here is an example of what one of the comments would look like:
----
This test failed!
To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).
If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.
---
commit: 123
buildURL: http://example.com
status: failed
<details><summary>Test output</summary><br><pre>
snippet_test.go:242: got output \"\"; want it to contain \"4 Venue 4\" snippet_test.go:243: got output \"\"; want it to contain \"19 Venue 19\" snippet_test.go:244: got output \"\"; want it to contain \"42 Venue 42\"
</pre></details>

feat(Build Cop): include test logs in comments

---

packages/buildcop/package.json
packages/buildcop/src/buildcop.ts

This will hopefully lead to catching more errors and fewer missing reports. The upgraded gcf-utils will retry invocations using Cloud Tasks.
Updates #532.

chore(Build Cop): update gcf-utils, drop try/catch

---

packages/sync-repo-settings/src/required-checks.json

Firestore conforms with the standard library checks.
Conformance tests do not run integration tests

fix(sync-repo-settings): fix java config

---

packages/buildcop/package.json
packages/buildcop/src/buildcop.ts

Some build logs are too large to fit in a Task, so they would get
silently dropped.
Fixes #532.

fix(Build Cop): downgrade gcf-utils to stop using Tasks

---

packages/blunderbuss/src/blunderbuss.ts
packages/blunderbuss/test/fixtures/config/on_label.yml

Before this, if the config didn't have an `assign_issues` value, the issue was skipped.

fix(Blunderbuss): make assign_issues_by work without assign_issues

---

packages/auto-label/src/auto-label.ts
packages/auto-label/test/auto-label.ts

This adds support for some Python issues that have the API as the part before the period (for example, https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3923).
This also adds support for APIs that are prefixed with `cloud` like `cloudiot` and `cloudkms`.
I updated the auto-detect function signature a bit to make it easier to write tests. Let me know if there is a more idiomatic way to write a table-driven style test.

feat(auto-label): support more APIs and issue titles

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts
packages/buildcop/test/fixtures/testdata/node_one_failed.xml

This will not rename or close old "Mocha Tests: ..." issues; the bot will file duplicates.

feat(Build Cop): grab the right package for Node.js tests

---

packages/buildcop/README.md
packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts
packages/buildcop/test/fixtures/testdata/node_group.xml
packages/buildcop/test/fixtures/testdata/node_group_pass.xml

If the common setup code for 100 tests fails, in some cases all 100 tests with "fail." Before this change, the bot would file a separate issue for each of those tests, which was very annoying.
This change groups tests into a single issue when 10 or more fail in a single build.
I made the choice to leave existing individual issues open when opening a "grouped" issue. People may be actively discussing a broken test in one of the issues; it would be rude if the bot decided to close the existing issue and end the discussion.
Note: I refactored some of the existing logic into a `findExistingIssue` function. The diff does not make that very clear.
Areas to watch out for in review:
* The choice to leave existing issues open.
* README docs, the grouped issue body, and grouped issue comments. Are …

feat(Build Cop): group tests into a single issue when 10+ fail

---

packages/gcf-utils/package.json
packages/gcf-utils/src/promise-events.ts

Takes a collection of `@types` modules, and moves them from `devDependencies`
into `dependencies`.  Every bot we were building needed to randomly `npm install`
these dependencies, and it was leading to a general confusion about what was
actually required.
I also moved the promise events type information from a `d.ts` into a `.ts` file.
This ensures the interface gets packaged in a `d.ts` in the `build/src` dir,
and means we can delete this file from every other package.  After this version of
`gcf-utils` ships, we can run around and delete all of the `index.d.ts` files,
and remove a bunch of dependencies from `package.json` across the board.

fix(gcf-utils): prepackage required type modules and interfaces

---

packages/gcf-utils/src/gcf-utils.ts

This field is used when fetching config.

fix(gcf-utils): populate repository.owner

---

packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts

we were not paginating over all repos, so we would have only had a partial result set.

fix: paginate result set when listing installations

---

packages/buildcop/buildcop.go
packages/buildcop/buildcop_test.go

I'm not 100% sure of this design. So, I'm open to other ideas. Perhaps we should put the long error message in a custom error type?
I thought about having `func newConfig`, but that had the same issue of having too many arguments and being confusing.
We could also use something like Viper, but it doesn't seem necessary.

feat(buildcop): use tested config type

---

packages/failurechecker/.gitignore
packages/failurechecker/package.json
packages/failurechecker/src/app.ts
packages/failurechecker/src/failurechecker.ts
packages/failurechecker/test/failurechecker.ts

This is me poking at a few things which may not need to be poked.  For some reason I'm bothered by the way we need to pin all of the exportable methods to a single function.  It makes the code harder to read in other bots.  I kind of wanted to test this out here, and see if I could make things work without doing it.  Someone please check me to make sure I'm not breaking something :)
Second - cleaning up some dependencies.

refactor(failurechecker): clean up dependencies and exports

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts

See https://github.com/googleapis/google-cloud-go/issues/2571#issuecomment-656331671 for an example of the accidental title formatting.

fix(buildcop): add extra newline to prevent title formatting

---

packages/release-please/src/release-please.ts
packages/release-please/test/release-please.ts

The cron task does not (_currently, see [tracking issue](https://github.com/googleapis/repo-automation-bots/issues/676)_) populate all repo meta data, like repo language.
For now, we can assume that snapshots are being created for Java.

fix(release-please): default to java language for snapshots

---

packages/gcf-utils/package.json

`@types/sonic-boom` is required to compile gcf-utils and is therefore required as a devDependency.
Fixes https://github.com/googleapis/repo-automation-bots/issues/697

fix(gcf-utils): add missing dev dependency @types/sonic-boom

---

packages/buildcop/package.json
packages/buildcop/src/app.ts
packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

We should add a test for this, but I thought it would be good to get a hot fix in for build cop quickly.
This also unblocks @azizsonawalla's work  as well, which requires that bots have `@types/sonic-boom` available.
Refs: https://github.com/googleapis/repo-automation-bots/issues/699 (tracking issue for test).

feat(gcf-utils): some bots have large payloads not appropriate for cloud task payload 

---

packages/auto-label/package.json
packages/blunderbuss/package.json
packages/conventional-commit-lint/package.json

Upgrade auto_label, blunderbuss and conventional_commit_lint to gcf-utils 5.2.2

build: upgrade some bots to gcf-utils 5.2.2

---

packages/sync-repo-settings/src/app.ts
packages/sync-repo-settings/src/sync-repo-settings.ts
packages/sync-repo-settings/test/test.ts

When syncing settings, we previously were looking for an `ignored` flag, and then not running any of the repo setup code if ignored.  For master branch protection and repo settings, this makes sense.  For adding teams that have access though, it's creating problems where access is manually managed.  Since it's rare that someone would want to prevent adding the team membership, we're ignoring ignore now for that scenario.

fix(sync-repo-settings): always add team memberships

---

packages/sync-repo-settings/src/required-checks.json

@software-dov Could you check the list of required checks? They were accidentally erased (and replaced with "kokoro") when I added proto-plus to Sloth's list of repos.

chore: add repo override for proto-plus-python

---

packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
packages/merge-on-green/package.json
packages/merge-on-green/src/app.ts

Merge on green already has retry logic, I believe using background tasks for it was leading to a thundering herd of retries.

fix(mog): do not double schedule work

---

packages/sync-repo-settings/src/sync-repo-settings.ts

_@sofisl @JustinBeckwith this is what I had in mind, and is closer to how I've approached handling errors in production Node.js applications._
1. you should catch the error close to the source.
2. rather than suppressing all errors, you should make an error to suppress the specific errors you understand.
In this PR I worked through all the jobs that were failing and retrying, due to some state of a repository on googleapis, and documented the potential failures.
This does not revert back to catching all errors, so should continue to appropriately bubble issues with nock.

fix(sync-repo-settings): catch specific categories of errors

---

packages/buildcop/package.json
packages/buildcop/src/app.ts
packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/src/logging-octokit-plugin.ts
packages/gcf-utils/test/gcf-bootstrapper.ts
packages/gcf-utils/test/logging-octokit-plugin.ts
packages/merge-on-green/package.json
packages/merge-on-green/src/app.ts
packages/release-please/package.json
packages/release-please/src/app.ts

The release of `gcf-utils` with a custom logger seems to be causing issues with `release-please`.
I think this is probably a snowflake, because release-please bot passes the GitHub instance around, and uses many more methods than most of our bots. However, I still think we should try rolling out the logger gradually given this hiccup.
A bot can simply opt in via:
```js
gcf(handler, {
background: true,
logging: true
})
```
_Note: I've already tested this code with release-please._
**I've turned logging on for build cop to start, since it already had configuration, let's QA this tomorrow @azizsonawalla.**

feat: logger must be turned on with config option

---

packages/auto-label/package.json
packages/auto-label/src/app.ts
packages/auto-label/test/auto-label.ts

Enable Octokit logging for auto-label. This one is the guinea pig, and if everything looks solid I'll do another PR to upgrade a few more bots, and then all.

build: upgrade and enable Octokit logging for auto-label

---

packages/release-please/package.json

Now it seems that `@octokit/types` would prefer not to be pinned.

fix(release-please): now pinning @octokit/types breaks compile

---

packages/sync-repo-settings/src/required-checks.json

release-please is a slightly different shape than other repos, in terms of the required checks needed.

chore(sync-repo-settings): ignore release-please

---

packages/conventional-commit-lint/src/conventional-commit-lint.ts
packages/conventional-commit-lint/test/conventional-commit-lint.ts

Looking in the logs, somehow we're running into situations where the list of commits on the PR appears to be empty?  When this situation comes up, specifically logging it as an error, but letting the program continue.

fix(conventional-commit-lint): handle PRs with no commits

---

packages/auto-label/.gitignore
packages/auto-label/src/auto-label.ts
packages/auto-label/test/auto-label.ts
packages/conventional-commit-lint/src/conventional-commit-lint.ts
packages/label-sync/src/label-sync.ts
packages/merge-on-green/src/merge-logic.ts
packages/merge-on-green/src/merge-on-green.ts
packages/monitoring-system/data-processor/src/data-processor-factory.ts
packages/publish/test/publish.ts
packages/slo-stat-bot/src/slo-stat-label.ts

If we're consistent about our usage of `console.error`, we can use this to build better alerting systems in the backend. 
===== UPDATE =====
Ok @bcoe @sofisl I learned something tonight!  Google Cloud Logging (and error reporting) will not automatically log `console.error` messages as a `ERROR` level in logs.  The only way to trigger that behavior is to specifically log an `Error` object.  This means we have to be _super_ careful about the way we log errors.

fix: use console.error for errors

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/test-helpers.ts

Support Cloud Logging severity levels so that logs can be filtered be severity in logs viewer
Fixes https://github.com/googleapis/repo-automation-bots/issues/4

feat(GCFLogger): support Cloud Logging/Stackdriver severity levels

---

packages/auto-label/src/auto-label.ts
packages/conventional-commit-lint/src/conventional-commit-lint.ts
packages/failurechecker/src/failurechecker.ts
packages/gcf-utils/src/gcf-utils.ts
packages/label-sync/src/label-sync.ts
packages/merge-on-green/src/merge-logic.ts
packages/merge-on-green/src/merge-on-green.ts

Migrate some of the bots to the logging API available in gcf-utils. Doing this in 2 stages so as to not make this one massive PR.
`console.log()` --> `logger.info()`
`console.*()` --> `logger.*()`

refactor(repo-automation-bots): migrate some bots from console logging to GCF Logger

---

.github/publish.yml
.github/release-please.yml
packages/gcf-utils/package.json
packages/publish/src/publish.ts
packages/release-please/package.json
packages/release-please/src/release-please.ts

`release-please` now has support for generating a release from a folder other than root.
This PR adds similar support to `publish` bot, and enables the automated publication of `gcf-utils`.

build: use release-please/publish for gcf-utils

---

packages/publish/src/publish.ts

* we were appending `opts.path` before traversing into the top level folder in tarballs returned by GitHub.
* also noticed we suppress errors from npm, let's not do this as it can hide broken publishes.

fix: append opts.path at end of install path

---

packages/sync-repo-settings/src/sync-repo-settings.ts

The API call I was making here required a fancy header based on the use of the `required_approving_review_count` field.  Sorry bout that 🙃

fix(sync-repo-settings): send magic header

---

packages/gcf-utils/src/logging-octokit-plugin.ts
packages/gcf-utils/src/octokit-request-parser.ts

The Octokit logging plugin in gcf-utils has some great request parsing logic that should be reusable. Hence pulling that logic out to a separate module.

refactor(gcf-utils): extract Octokit request parsing logic to separate module

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts
packages/buildcop/test/fixtures/testdata/ruby_one_failed.xml

I confirmed the test case failed with the same error message as #768 before making the corresponding src/buildcop.ts changes.
Fixes #768.

fix(buildcop): add support for Ruby logs

---

packages/gcf-utils/src/gcf-utils.ts

In debugging the issues with merge on green on GoogleCloudPlatform,
we ultimately were able to isolate the problem to the fact that
Cloud Scheduler tasks for googlapis were parsed as objects upon
arrival to our Cloud Function, whereas payloads for GoogleCloudPlatform
were still a Buffer.
We already have a helper that conditionally decodes the payload
appropriately let's use this.
Note: we should still try to root cause this, if only because it's
bizarre.

fix(merge-on-green): payload switches between Buffer and object

---

packages/release-please/package.json

Remove the caret on release-please's @octokit/webhooks dependency to not pull in a newer version which causes tests to break. Full explanation here: https://github.com/googleapis/repo-automation-bots/issues/792
This is a temporary fix to unblock some PRs until we fully support the newer versions

build(release-please): remove caret from webhooks import

---

packages/sync-repo-settings/src/sync-repo-settings.ts

@bcoe I have a hunch about the crashes in private repos for sync-repo-settings.  I think this is an error with the bot trying to read the config, because we never specified the application needs code read access.  For public repos it's fine, and for private it's bombing.  We probably need to update the app settings and re-review permissions (I don't have the keys to this castle).  In the interim, this should maybe catch the failure.

fix(sync-repo-settings): error handling for file read

---

packages/sync-repo-settings/src/sync-repo-settings.ts

Somehow we're getting weird overrides for repositories. Adding more debug logging for which required checks are being set.

chore(sync-repo-settings): add debug for required status checks

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/src/logging/gcf-logger.ts
packages/gcf-utils/src/logging/trigger-info-builder.ts
packages/gcf-utils/test/gcf-bootstrapper.ts
packages/gcf-utils/test/gcf-logger.ts
packages/gcf-utils/test/integration/gcf-logger-integration.ts
packages/gcf-utils/test/trigger-info-builder.ts

* Adds support for initializing GCFLogger with bindings
* Adds support for child loggers (with bindings) to GCFLogger
* Uses above mentioned child logger functionality to bind trigger information to all log statements for an execution
Resulting log statements will look something like this:
```ts
(in gcf-utils.ts)
const triggerInfo  = {
trigger: {
trigger_type: 'GITHUB_WEBHOOK',
trigger_sender: 'some sender',
payload_hash: '123456',
trigger_source_repo: {
owner: 'foo owner',
owner_type: 'Org',
repo_name: 'bar name',
url: 'some url',
},
},
};
...
bindTriggerInfoToLogger(triggerInfo);
```
```ts
(in some-bot.ts)
// after gcf-utils has done all the trigger parsing and logged the trigger information the first time
logger.info({ some-property: 'some-value' });
```
```ts
(Cloud Logs Viewer)
{ …
```

feat(gcf-utils): add trigger info as bindings to all log statements

---

packages/sync-repo-settings/src/required-checks.json

`google-cloudevents-nodejs` contains  auto-generated proto bindings, and has different testing requirements than our standard Node.js repos.

fix(sync-repo-settings): add google-cloudevents-nodejs to exclude rules

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/src/logging/gcf-logger.ts
packages/gcf-utils/src/logging/trigger-info-builder.ts
packages/gcf-utils/test/gcf-bootstrapper.ts
packages/gcf-utils/test/gcf-logger.ts
packages/gcf-utils/test/integration/gcf-logger-integration.ts
packages/gcf-utils/test/trigger-info-builder.ts

This reverts the changes in this commit https://github.com/googleapis/repo-automation-bots/commit/157c768e6de8e3067e24a6dd17be152ae98c25d8 (but keeps some of the JSDocs and message changes).
This is a quick fix for the issue described in https://github.com/googleapis/repo-automation-bots/issues/808 until we can figure out the root cause.

fix(gcf-utils): Revert binding trigger information to logger

---

packages/sync-repo-settings/src/required-checks.json

Is `requiresStrictStatusChecks` ==  "require branches to be up to date before merging."?
cc @tseaver

chore: disable strict status checks for python-bigtable

---

packages/failurechecker/src/failurechecker.ts
packages/failurechecker/test/failurechecker.ts

Turning off un-label issue for the time being.

chore(failurechecker): turn off failure checker, while debugging un-label issues

---

packages/snippet-bot/package.json
packages/snippet-bot/src/snippet-bot.ts
packages/snippet-bot/test/snippet-bot.ts

also pin octokit version
Somehow the previous combination of the dependencies caused problems on Cloud Function environment. I'm still not 100% sure it's going to fix the problem, but I don't have local repro anyways, I think I need to try.

chore(snippet-bot): remove problematic deps

---

packages/snippet-bot/README.md
packages/snippet-bot/__snapshots__/snippet-bot.js
packages/snippet-bot/package-lock.json
packages/snippet-bot/src/snippet-bot.ts
packages/snippet-bot/test/snippet-bot.ts

With this PR, you need to have `.github/snippet-bot.yml` config file to enable `snippet-bot`. The config file can be an empty file.

feat(snippet-bot): require the config file to enable the bot

---

packages/auto-label/src/auto-label.ts
packages/auto-label/test/auto-label.ts

As we've moved away from trying to throw in too many cases, we started recognizing errors by logging.  The problem is, that means we don't see these errors as a problem in our tests.  UNTIL NOW!  This stubs out `logger.error`, and ensures we don't log there unless we intend to, plus the fixes needed to get the tests passing again.

test(auto-label): throw on logger errors in tests

---

packages/release-please/package-lock.json
packages/release-please/package.json
packages/release-please/src/release-please.ts

go's CHANGELOG has a different name.

feat(release-please): allow changelog path to be configured

---

packages/auto-label/src/auto-label.ts
packages/auto-label/test/auto-label.ts

Issues don't always follow Conventional Commits. But, more and more languages are following Conventional Commits for PR titles. This PR adds support for the auto-label bot to detect labels from the scope of a Conventional Commit.
This is closely related to https://github.com/googleapis/repo-automation-bots/pull/871, which starts auto-labeling PRs.

feat(auto-label): auto-detect from Conventional Commit scopes

---

packages/snippet-bot/package.json

We don't need `prepare` script for our bots. It also causes deployment failure on nodejs12 runtime.

fix(snippet-bot): fix deployment for nodejs12 runtime

---

.github/workflows/ci.yaml

Now we only have node=12 because majority of the bots are running on
nodejs12 runtime.
We can add a new job by adding an element in `include` section of the
matrix.
For example, if you want to run the test for snippet-bot on node 14, we
can do something like:
```
include:
- node: 14
package: snippet-bot
```
Fixes #892

testing: introduce `node` matrix

---

packages/trusted-contribution/src/app.ts

Some of the tasks are running over the Cloud Tasks size limit.
Fixes #920.

fix(trusted-contribution): don't use Cloud Tasks

---

metrics/dashboards.sql

Adds context aware commits to our dashboard, using the 3.5 minute estimate we were given by teammates on survey:

feat(metrics): add context aware commits to dashboard

---

packages/auto-label/README.md
packages/auto-label/src/auto-label.ts
packages/auto-label/test/auto-label.ts

Support for issues like https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4543.

feat(auto-label): auto-detect before underscores

---

packages/buildcop/__snapshots__/buildcop.js
packages/buildcop/src/buildcop.ts
packages/buildcop/test/buildcop.ts

When deciding whether to reopen an old issue or to open a new one, we
want to find the old issue that was most recently closed. That way, if
the most recently closed issue was closed within 10 days, we know to
reopen it.
Fixes #975 🦕

fix(buildcop): sort dup closed issues by closed_at

---

packages/label-sync/src/label-sync.ts
packages/label-sync/test/test.ts

This will allow [api-linter](https://github.com/googleapis/api-linter/labels) to ignore our label sync logic.
CC: @lukesneeringer

feat(label-sync): allow a repo to be ignored

---

packages/sync-repo-settings/README.md
packages/sync-repo-settings/src/schema.json
packages/sync-repo-settings/src/sync-repo-settings.ts
packages/sync-repo-settings/src/types.ts

Fixes two issues appearing in the logs.  
1. The `maintain` and `triage` permissions are not actually available in the GitHub API yet 🙄  Backed that out of the config.
2. When there's an exception updating permissions or other settings, don't crash.  Just log the error and move on.

fix(sync-repo-settings): maintain and triage not available yet

---

packages/gcf-utils/src/logging/gcf-logger.ts
packages/gcf-utils/test/gcf-logger.ts

We are seeing quite a few errors in auto-label, I believe due to code like this:
```js
await context.github.issues
.addLabels({
owner,
repo,
issue_number: issueNumber,
labels: [githubLabel],
})
.catch(logger.error);
```
When a method is passed by reference like this, it will lose reference to its `this`, making it throw, see:
```js
class Logger {
error(msg) {this.log(msg)}
log(msg) {console.info(msg)}
}
const logger = new Logger()
setTimeout(logger.error, 10) <-- if you do this in JavaScript this goes away.
```

fix(logger): allow log methods to be used in isolation

---

packages/failurechecker/src/failurechecker.ts
packages/failurechecker/test/failurechecker.ts

Reads `release-please.yml`, and for some language flavors doesn't treat an old `autorelease: tagged` label as a failure.

feat(failure-checker): autorelease: tagged is not considered failure for some languages

---

packages/sync-repo-settings/src/required-checks.json

@python-samples-owners is currently a child team of @yoshi-python.
This results in more notification spam to samples reviewers

chore(python): make python-samples-owners writers

---

packages/blunderbuss/.eslintignore
packages/blunderbuss/__snapshots__/blunderbuss.js
packages/blunderbuss/src/blunderbuss.ts
packages/blunderbuss/test/blunderbuss.ts
packages/blunderbuss/test/fixtures/config/pr_on_label.yml

Allows blunderbuss to use the same configuration structure for issues by labels for assigning PRs.

feat(blunderbuss): support assign_prs_by config

---

scripts/build-function.sh

For repeatable builds, we should be running the latest version that was tested.
Note that this may actually downgrade dependencies that are currently running in production. The runtime was ignoring our package-lock.json, but our tests and compilation was respecting it. By providing the package-lock.json to the GCF runtime, this will likely snap some dependencies back to the last versions that were tested.
I believe this behavior was the intention of #130

build: also copy the package-lock.json during deployment

---

packages/release-please/package-lock.json
packages/release-please/package.json
packages/release-please/src/release-please.ts

Pass the additional flag `monorepoTags` through, for the benefit of the `go` monorepo release process.

feat(release-please): support go monorepo release process

---

packages/snippet-bot/README.md
packages/snippet-bot/src/api-labels.ts
packages/snippet-bot/src/violations.ts
packages/snippet-bot/test/snippet-bot.ts

fixes #1101
Locally it works fine with using the dev bucket. Currently the new `products.json` file is not yet deployed to the prod bucket, so we can not merge this yet.

fix(snippet-bot): use products.json for region_tag_prefix

---

packages/snippet-bot/src/snippet-bot.ts

fixes #1108 
fixes #1110
At least, this will avoid the bot from dying.

fix(snippet-bot): ignore 403 error as well

---

renovate.json

The Go genproto repo updates every day after a human reviews and merges
a PR. However, this can lead to two Renovate PRs on Monday, which is
annoying. So, I updated the Renovate config to update genproto later in
the day, hopefully _after_ the Monday genproto generation is merged.

chore: update Go genproto later in day on Monday

---

packages/gcf-utils/src/gcf-utils.ts

fixes #1160
Now a bot can utilize the following two functions for adding an issue
comment and providing a checkbox for refreshing the comment.
- addOrUpdateIssueComment
- getCommentMark
snippet-bot has an example implementation.

feat(gcf-utils): export a function for the comment mark

---

.github/workflows/interrogate.js

When merging to the main branch, there is no GITHUB_BASE_REF.
Because we use a squash based workflow, we can use HEAD~1 instead.
Fixes #1156

build: use HEAD~1 if on main branch

---

packages/release-please/README.md
scripts/publish-function.sh

Deployment was yelling about there being no `s` on `max-retry-duration` (for the second format).
I also pulled us out to 12 hours, to give us more time to log a bug when alerts are going off.

fix(build): builds failing due to format

---

packages/release-please/README.md
scripts/publish-function.sh

we were also missing a newline, grumble.

build: also need to escape newline

---

packages/sync-repo-settings/src/sync-repo-settings.ts
packages/sync-repo-settings/test/test.ts

Previously, if a language wasn't listed in the global config of `required-checks.json`, no changes would be made to settings.  With this change, the `cloud-dpe` and `cloud-devrel-pgm` groups now are *always* added to every repository with write access where this GitHub app is installed.

fix(sync-repo-settings): ensure cloud dpes are always added

---

packages/failurechecker/__snapshots__/failurechecker.js
packages/failurechecker/package.json
packages/failurechecker/src/failurechecker.ts
packages/failurechecker/test/failurechecker.ts

This PR does a few things:
* track multiple release PR failures (shown as a list)
* updates the issue body when a new release fails
* ignores release PRs that are marked as both `autorelease: failed` and `autorelease: published` (in case you retry and it succeeds)
* closes the open issue when release failures are resolved

feat(failurechecker): track multiple failures and autoclose after success

---

.github/CODEOWNERS
.github/auto-label.yml
.github/blunderbuss.yml

* adds users as CODEOWNERS to bots they authored (note we keep the github-automation team as an owner to prevent blocking and in case a solo author/owner submits a PR)
* enables auto-label for PRs by code path
* enables blunderbuss auto assignment by bot label

build: auto assign issues and pull requests by bot

---

packages/header-checker-lint/README.md

docs(header-checker-lint): fix README configuration file name

---

packages/generated-files-bot/README.md
packages/generated-files-bot/src/generated-files-bot.ts
packages/generated-files-bot/test/fixtures/config/ignore-authors.yml
packages/generated-files-bot/test/generated-files-bot.ts

feat(generated-files-bot): configurable list of PR authors to ignore

---

packages/auto-label/package-lock.json
packages/merge-on-green/src/merge-logic.ts
packages/merge-on-green/src/merge-on-green.ts
packages/merge-on-green/test/merge-logic.ts
packages/merge-on-green/test/merge-on-green.ts

Attempt to readdress #1159, fixing the issue that caused reverting in #1264.
I believe the issue was that reaction IDs were not being added to stored PRs, causing the main (merge-logic) to fail. This was because I was attempting to make reaction and reaction IDs optional. To fix, I've essentially copied the exact format in which PRs are currently being added, and made it into its own function (addPR). 
I have also been doing some manual testing in the GCF function just to confirm this works. I was able to spot another potential bug, which is that we need to perform scans for missing PRs on different cron jobs with different installation IDs depending on the org, otherwise we won't have access to info like branch protection, etc.
I've also rescoped tests, which was a hanging comment left …

fix(merge-on-green): second attempt to add cron to pick up hanging PRs

---

packages/bazel-bot/docker-image/generate-googleapis-gen.sh

The "git pull" was designed to make the following "git push" more likely to succeed in the face of a race condition.  However, if the push fails for any reason, I think it's safer to fail and retry later.

fix: avoid unpredictable repo state

---

packages/bazel-bot/docker-image/generate-googleapis-gen.sh
packages/bazel-bot/test-generate-googleapis-gen.sh

Avoids a potential race condition.  The test repo must use the same branch names as the real googleapis-gen repo, so that means using master instead of main.  I'll switch it back when we migrate later.

fix: push two refs with one 'git push statement'

---

packages/owl-bot/package-lock.json
packages/owl-bot/package.json

This gets us upgraded to the latest and greatest version of gcf-utils, with support for probot 11.
Note, `@octokit/webhooks@7.21.0` has been pinned for the time being due to https://github.com/octokit/webhooks.js/issues/436.

build(owl-bot): update gcf-utils with probot 11

---

packages/owl-bot/package.json

We can't have a prepare that requires dev dependencies, as these are not installed during Cloud Build deploy.

build(owl-bot): no prepare

---

packages/bazel-bot/docker-image/generate-googleapis-gen.sh
packages/bazel-bot/test-generate-googleapis-gen.sh

before building with -k.  Otherwise, we can't distinguish a build failure due to a bad proto
from a build failure due to transient network issue.

fix: confirm that bazel can fetch remote build dependencies

---

.github/CODEOWNERS
synth.py

I messed this up in the recent CODEOWNERS rollout to the other regular repos

chore: restore CODEOWNERS and synth ignore

---

scripts/publish-function.sh

This change moves us towards updating environment variables, rather than replacing all environment variables.
The reason for this is that owl-bot has a couple special variables it sets:
* `APP_ID`: the ID of the GitHub app.
*  `TRIGGER`: the cloud build trigger.

build: update environment variables rather than replacing

---

serverless-scheduler-proxy/main.go

Add an additional endpoint for redirecting PubSub messages from the container registry to owl-bot.
Authentication will be handled within Owl Bot itself, so there is no need for an installation token.

feat(redirect): add redirect for container subscription

---

packages/owl-bot/src/database.ts
packages/owl-bot/test/database.ts

the code was just escaping just the first instance of each special character

fix: escape all the special characters in firestore ids

---

packages/gcf-utils/src/gcf-utils.ts
packages/owl-bot/src/handlers.ts
packages/owl-bot/test/owl-bot.ts

There was no await during loading in gcf-utils, this meant that our async
load step would not have loaded routes yet, before requests are handled.
I also found a missing await in handlers, which could have lead to perf
issues

fix(owl-bot): fix two timing related bugs

---

packages/monitoring-system/data-processor/cloudbuild.yaml
packages/monitoring-system/data-processor/test/unit/data-processors/github-data-processor.spec.ts

We are not currently using the data from data-processor (_not to say we might not in the future._).
Turning off for now, until someone can look in to quota issues:
Fixes #876

build: stop deploying data-processor

---

packages/owl-bot/src/handlers.ts
packages/owl-bot/test/handlers.ts

* we were not using the branch name stored in configuration.
* we were using a branch name that would collide if multiple lock updates were made at once.

fix(owlbot): use branch from config

---

packages/owl-bot/src/bin/commands/validate.ts
packages/owl-bot/src/bin/owl-bot.ts
packages/owl-bot/src/handlers.ts

Adds a command line helper for validating configuration (my first attempt at adding config to phishing protection had a validation issue).

feat(owlbot): add command line helper for validation

---

packages/gcf-utils/src/gcf-utils.ts

Fixes #1444, and hopefully a bunch of our other bots that use a cron job as well.

fix: authenticate octokit instance properly when receiving payload from cloud scheduler

---

.github/workflows/ci.yaml

chore(.github): upgrade CI to Go 1.16

---

packages/owl-bot/cloud-build/update-pr.yaml

We were using the wrong email address for OwlBot post processor updates.

fix(owlbot): contributor should be gcf-owl-bot[bot]@users.noreply.git

---

packages/flakybot/flakybot.go
packages/flakybot/flakybot_test.go
packages/flakybot/go.mod

I'm hoping the optimization in Go 1.16 to call `lstat` less often will avoid the error in #1475. But, I'm not 100% as that was caused by a filesystem race condition.
I also added a test by faking out PubSub publishing.
Fixes #1475.

fix(flakybot): use os.WalkDir to hopefully avoid lstat error

---

packages/owl-bot/cloud-build/update-pr.yaml
packages/trusted-contribution/src/trusted-contribution.ts

PRs made by OwlBot were erroring with:
```bash
Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```
This moves username/email configuration earlier.
---
This PR also adds `gcf-owl-bot[bot]` to trusted contributors so that tests kick off.

fix(owl-bot): set email/username and add to trusted contributors

---

packages/owl-bot/src/copy-code.ts

That's fine.  We enumerate the list of pull requests and issues and will still find the hash if it's there.

fix: owl-bot doesn't currently have permission to search

---

packages/auto-label/src/helper.ts
packages/auto-label/test/auto-label.ts

I tried to do this in #1062, but that missed some title formats.
Related to #1483, but fixes one reason people might need to disable the bot.

fix(auto-label): never auto-detect label for docs or build

---

packages/owl-bot/src/copy-code.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

Even though we clone googleapis/googleapis-gen to a local directory,
we always want the source linke to point to
https://github.com/googleapis/googleapis-gen.
Fixes https://github.com/googleapis/repo-automation-bots/issues/1502

fix: bad Source-Link path in pull requests

---

packages/owl-bot/src/core.ts
packages/owl-bot/src/handlers.ts
scripts/publish-function.sh

We bumped into a few rate limit issues when we bootstrapped OwlBot across dozens of repos the first time:
1. GitHub's abuse detection algorithm was triggered when opening PRs for updating all docker containers in sequence (I've added a delay to hopefully make this less likely).
2. We were hitting the Concurrent Get requests on Cloud Build (I've increased our polling interval to hopefully reduce this issue).
3. we were retrying almost immediately upon receiving an exception in Cloud Tasks, this lead to odd behavior where multiple jobs attempted to concurrently create the same PR, let's wait 5s making it less likely that this thundering herd happens.
---
Unsolved Problem:
* we're very close to the limit on Cloud Build for creating a maximum number of concurrent builds (we're allowed to …

fix(owlbot): address rate limit issues

---

packages/sync-repo-settings/README.md
packages/sync-repo-settings/src/bot.ts
packages/sync-repo-settings/test/test.bot.ts

Fixes #1517.  This uses the `push` event webhook, looks at the commits in the push, and then runs the sync if the settings file was among the list of changed files.

feat(sync-repo-settings): apply config after pushing to default branch

---

.kokoro/common.cfg
.kokoro/publish.sh
.kokoro/release/publish.cfg
packages/release-brancher/package.json

This token was causing a build failure, and does not appear to be used.

fix(release-brancher): fix build configuration and set private to false

---

scripts/sync-triggers.sh

Will need to delete the existing deploy triggers and let them be recreated.
Fixes #1556

build: fix trigger branch pattern to be more restrictive

---

packages/policy/src/bot.ts
packages/policy/test/test.bot.ts

If the call to `submitFixes` failed, it threw for the whole loop, and put the task back into the retry queue.   This led to records getting written into BigQuery every time it retried, and muddied up the logs something fierce.  This will now log the error, and move on if autofix fails.

fix(policy): exit gracefully if autofix fails

---

packages/policy/package-lock.json
packages/policy/package.json
packages/policy/src/changer.ts

Otherwise we keep stomping on the same branch, and ideally we will use this code for other PRs as well.  Also, it was causing failures in the case that the branch name already existed, but was behind the default branch

fix(policy): use uuid for branch names

---

packages/owl-bot/src/bin/commands/copy-code.ts

I thought giving it a default would be sufficient to avoid demanding it on the command line.  I was wrong.

fix: don't demand a source-repo-commit-hash argument

---

packages/failurechecker/src/failurechecker.ts
packages/failurechecker/test/failurechecker.ts

I'm not 100% how this could be possible, but I'm hoping this protects against behavior seen here:
https://github.com/googleapis/google-api-go-client/issues/958

fix(failurechecker): check that PR returned has labels

---

packages/policy/src/bot.ts
packages/policy/src/changer.ts
packages/policy/src/cli.ts
packages/policy/test/test.changer.ts

This fixes an issue where repositories which use `main` as the default branch aren't currently accepting PRs for autofixing.

fix(policy): submit PRs against the default branch

---

.release-please-manifest.json

Add the current release to the manifest for mono-repo-publish.

build(mono-repo-publish): update manifest to reflect currently published version

---

packages/mono-repo-publish/package.json

Missed migrating links over, which caused a publication error:
```
npm ERR!   bcoe cannot push repo https://github.com/sofisl/mono-repo-publish. push permission required to publish.
```

fix(mono-repo-publish): links should point to repo-automation-bots

---

packages/failurechecker/src/failurechecker.ts

`simple` release type only updates `version.txt` and does not do anything else. Skip the check for this type.

fix: do not trigger on the missing releases for 'simple' release type

---

packages/owl-bot/src/bin/commands/trigger-build.ts
packages/owl-bot/src/core.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

Include a details URL that links to the Cloud Build job, so that it's easier for folks in DPE to debug their builds.

feat(owlbot): link to cloud build job from post processor

---

packages/owl-bot/src/handlers.ts

Should cause less confusion when a massive update for OwlBot.lock happens.

fix(owlbot): explain what the lock file does

---

packages/label-sync/src/labels.json

In the short term, to be applied to PRs opened by renovate-bot in which dependencies require Node 12.

feat(label-sync): added label for end of life

---

packages/bazel-bot/docker-image/generate-googleapis-gen.sh
packages/bazel-bot/test-generate-googleapis-gen.sh

- updates bazel query that creates the list of the build targets to include rules instead of tar.gz output files
- updates script docs
- updates test with new targets
see https://github.com/googleapis/repo-automation-bots/issues/1338

feat: update bazel query to include rules instead of tar.gz output files

---

packages/merge-on-green/src/merge-on-green.ts

fix(merge-on-green): ignore 404 when removing a label

---

packages/auto-label/src/helper.ts
packages/auto-label/test/auto-label.ts

This removes another known prefix from titles (see https://github.com/GoogleCloudPlatform/python-docs-samples/issues/5657). Alternatively, we could build fancy auto-detect logic, but that would be much more complex. So, I kept it simple for now.
Fixes #1649.

feat(auto-label): support dashes and more prefixes

---

packages/sync-repo-settings/src/required-checks.json
packages/sync-repo-settings/src/sync-repo-settings.ts
packages/sync-repo-settings/test/test.bot.ts

This is the start of a broader config refactoring.  I want to push repo specific config away from the bot, and eventually multiple configs to `googleapis/.github` centralized config.  
It does a few things:
- removes the ability to have centralized ignored repos
- removes the ability to have centralized repo overrides
- drops the centralized ruby configs, since they had nothing in common
Blocked by:

fix(sync-repo-settings): remove local ignore and override configs

---

packages/trusted-contribution/README.md
packages/trusted-contribution/package-lock.json
packages/trusted-contribution/package.json
packages/trusted-contribution/src/trusted-contribution.ts
packages/trusted-contribution/test/fixtures/gcbrun.yml
packages/trusted-contribution/test/trusted-contribution.ts

Fixes #1678.  This introduces a config option so that repositories which use Cloud Build can opt into a comment instead of a label.  The config would look like this:
```yaml
annotations:
- type: comment
text: "/gcbrun"
``` 
Also some vanity test additions to get coverage to 100%.

feat(trusted): add optional comment configuration

---

packages/sync-repo-settings/README.md
packages/sync-repo-settings/src/bot.ts
packages/sync-repo-settings/src/config.ts
packages/sync-repo-settings/test/test.config.ts

This is part of a broader effort to enable organization level configuration for sync-repo-settings.  It starts by:
- Fixing a gaffe I tripped on in the README
- Splitting config validation and fetching out into it's own file
- Introducing config specific tests instead of relying on the bot tests
- Moving away from probot's built in config fetcher, and instead just directly fetching the files.
On the last bit - I did this because eventually I would like to be able to _merge_ the configurations between a local repo, and the upstream `.github` repository where a centralized config will be stored.   The current probot implementation doesn't allow for that, so this should be behaviorally compatible.

refactor(sync-repo-settings): split config out from the bot

---

renovate.json

The `genproto` package updates every day. When we upgrade in the morning, then `genproto` updates again, we get a second PR. This schedules the Renovate update to be later in the day so we hopefully only get one PR.

chore: configure Renovate to update genproto later

---

serverless-scheduler-proxy/main.go

Otherwise, the Client never closes its underlying connections and causes OOM errors.
Fixes #1687, which contains more detail about the memory leak.
cc @orthros (can't add as a reviewer).

fix(serverless-scheduler-proxy): Close secretmanager Client

---

metrics/trusted-contribution-label-added.sql
packages/trusted-contribution/src/trusted-contribution.ts

policy-bot should be a trusted bot, and have kokoro kicked off. Added metrics while I was there.

fix(trusted-contribution): policy-bot is trusted

---

packages/trusted-contribution/package-lock.json
packages/trusted-contribution/package.json

We need the latest gcf-utils for metrics.
Refs: https://github.com/googleapis/repo-automation-bots/pull/1721

fix(trusted-contribution): should use latest gcf-utils for logs

---

packages/label-sync/src/labels.json

So that we can bundle changes on repos and reduce the amount of breaking changes

build: add next major label

---

packages/owl-bot/src/copy-code.ts

so that owl-bot can also clone private repos
Fixes https://github.com/googleapis/repo-automation-bots/issues/1738

fix: use a token when cloning library repos

---

packages/datastore-lock/.c8rc.json
packages/datastore-lock/.eslintignore
packages/datastore-lock/.eslintrc.json
packages/datastore-lock/.gitignore
packages/datastore-lock/.mocharc.js
packages/datastore-lock/.prettierignore
packages/datastore-lock/.prettierrc.js
packages/datastore-lock/CHANGELOG.md
packages/datastore-lock/LICENSE
packages/datastore-lock/README.md
packages/datastore-lock/package-lock.json
packages/datastore-lock/package.json
packages/datastore-lock/src/datastore-lock.ts
packages/datastore-lock/test/datastore-lock.ts
packages/datastore-lock/tsconfig.json

This small library is initially implemented in `blunderbuss`, but it should be useful for some other bots, so I'm trying to make it a npm package.

feat(datastore-lock)!: factoring out datastore-lock

---

packages/blunderbuss/package-lock.json
packages/blunderbuss/package.json
packages/blunderbuss/test/blunderbuss.ts

We don't need to test DatastoreLock in blunderbuss.

cleanup(blunderbuss): use sinon instead of datastore-emulator

---

.release-please-manifest.json
release-please-config.json

chore: add release config for bot-config-utils

---

packages/bot-config-utils/src/bot-config-utils.ts
packages/bot-config-utils/test/bot-config-utils.ts

fixes #1784
@github-automations/bot-config-utils 1.0.0 has a bug in getConfig and getConfigWithDefault.
This is because of the weirdness of the response type of getContent.
The tests were passing because the tests were incorrectly returning config files.
Now the tests are returning responses similar to the actual API.

fix(bot-config-utils): fix getConfig

---

packages/bot-config-utils/README.md
packages/datastore-lock/README.md

This PR is just to fix the package name in the READMEs.

docs(google-automations): fix the package name in README

---

packages/bazel-bot/docker-image/Dockerfile

Using actools' team's docker image makes it less likely that bazel bot will fail when the googleapis/googleapis kokoro build test succeeds.
cc @vam-google

fix: use the docker image provided by actools team for bazel bot

---

packages/flakybot/package-lock.json
packages/flakybot/package.json
packages/flakybot/src/flakybot.ts
packages/flakybot/test/flakybot.test.ts

fixes #483
I think this will fix #483.
This PR acquires a lock per issue. Another approach is to acquire a lock per repo, but I think it'll be problematic because one build may contain many test failures and taking a long time to process.

fix(flakybot): use lock for updating an issue

---

packages/bot-config-utils/README.md
packages/bot-config-utils/src/bot-config-utils.ts
packages/bot-config-utils/test/bot-config-utils.ts

part of #1038
To fix #1038, obviously we'll need to use the config from the PR
head in header-checker-lint.

feat(bot-config-utils): allow fetching the config from the PR head

---

packages/bot-config-utils/src/bot-config-utils.ts
packages/bot-config-utils/test/bot-config-utils.ts

I made a mistake in 2.1.0.
I should match the return type of ConfigChecker.getConfig() and
getConfig().
This PR fixes this inconsistency.
Strictly saying this is a breaking change, so I'd release it as 3.0.0.

fix(bot-config-utils)!: match the return type of getConfigs

---

packages/header-checker-lint/README.md
packages/header-checker-lint/__snapshots__/header-checker-lint.js
packages/header-checker-lint/package-lock.json
packages/header-checker-lint/package.json
packages/header-checker-lint/src/header-checker-lint.ts
packages/header-checker-lint/test/header-checker-lint.ts

fixes #1038
With this PR, the bot will start using config from PR head.
This will allow users to add header-checker-lint.yml file to suppress
false positives in the same PR.
With #1802, the code will be cleaner, but not a blocker.

fix(header-checker-lint): use config from PR head

---

packages/sync-repo-settings/src/bot.ts
packages/sync-repo-settings/test/test.bot.ts

The `ref` payload is actual `refs/heads/[BRANCH_NAME]`.
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
Fixes #1753
Fixes #1615

fix(sync-repo-settings): check against the correct ref structure

---

cloudbuild-test/Dockerfile
cloudbuild-test/cloudbuild.yaml
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
packages/gcf-utils/test/integration/gcf-logger-integration.ts

fixes #1825
fixes #1827 
This change fixed the snippet-bot scheduler run at least locally.
According to:
https://github.com/octokit/auth-app.js/
We need to pass `{auth: opts}` instead of just `opts`.
This is a significant change, so I'm marking this as a breaking change.

fix(gcf-utils)!: fix getAuthenticatedOctokit

---

packages/snippet-bot/package-lock.json
packages/snippet-bot/package.json

fixes #1825
gcf-utils@8.0.0 should fix the broken scheduler handler for organization tasks.
I'd like to start with snippet-bot because I know its behavior well (easy to tell if it's working).

fix(snippet-bot): fix the scheduler handler

---

packages/cron-utils/src/cron-utils.ts

Currently, unset defaults to UTC

fix(cron-utils): set timezone to Americas/Los_Angeles

---

packages/merge-on-green/cron.yaml
packages/slo-stat-bot/cron.yaml

Deployments failed for slo-stat-bot and merge-on-green because the cron schedules with `/` broke the yaml syntax

build: quote cron schedules

---

packages/trusted-contribution/__snapshots__/validation-test.js
packages/trusted-contribution/package-lock.json
packages/trusted-contribution/package.json
packages/trusted-contribution/src/config-schema.json
packages/trusted-contribution/src/config.ts
packages/trusted-contribution/src/trusted-contribution.ts
packages/trusted-contribution/test/fixtures/broken.yml
packages/trusted-contribution/test/fixtures/disabled.yml
packages/trusted-contribution/test/trusted-contribution.ts
packages/trusted-contribution/test/validation-test.ts
packages/trusted-contribution/tsconfig.json

The bot will start validating config schema on PRs.
It will create a failing status check if the config doesn't follow the schema.
I also added `disabled` field for opting out from this bot.
Related: #131
The bot needs Read/Write permission on Checks.
I added the permission to the bot. The org admins need to approve the requests.

feat(trusted-contribution): migrate to bot-config-utils

---

packages/owl-bot/.gitignore
packages/owl-bot/package-lock.json
packages/owl-bot/package.json
packages/owl-bot/src/app.ts
packages/owl-bot/src/bin/commands/test-webhook.ts
packages/owl-bot/src/bin/owl-bot.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/src/run-probot-locally.ts
packages/owl-bot/test/owl-bot.ts

Introduces the command line option `test-webhook` which allows a troublesome webhook payload to be tested from the CLI in isolation.
This is in pursuit of addressing bugs with the `owlbot:run` label noticed in #1877.

feat(owlbot): allow webhook events to be run from CLI

---

packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

If we retry running as a result of `owlbot:run`, we should not crash if label has already been removed.

fix(owlbot): do not crash on missing label

---

packages/owl-bot/src/bin/commands/test-webhook.ts
packages/owl-bot/src/core.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

API calls that interact with the PR must be made against base, but API calls that
clone source should be made against the fork.
See: https://github.com/googleapis/nodejs-phishing-protection/pull/300
Fixes #1717

fix(owlbot): address bugs with running owlbot against fork

---

packages/snippet-bot/__snapshots__/snippet-bot.js
packages/snippet-bot/package-lock.json
packages/snippet-bot/package.json
packages/snippet-bot/src/snippet-bot.ts

Reverts googleapis/repo-automation-bots#1920
It turns out that bot-config-utils throws an error for an empty config file. I think snippet-bot is the only bot which uses empty config file.

Revert "feat(snippet-bot): start validating config schema upon retrieval"

---

packages/bot-config-utils/src/bot-config-utils.ts
packages/bot-config-utils/test/bot-config-utils.ts

fix(bot-config-utils): handle an empty config file

---

packages/datastore-lock/.mocharc.js
packages/datastore-lock/package-lock.json
packages/datastore-lock/package.json
packages/datastore-lock/src/datastore-lock.ts

fixes #1943
In our use case, the targets are very similar (URL of the PR),
so in order to avoid datastore contention, it's better to use
hashed value for the datastore key.

fix(datastore-lock): use hashed value for datastore key

---

scripts/update-package-locks.sh

This script will iterate all the packages and do the following:
rm package-lock.json
npm i --no-color
npm run fix --no-color
npm run test --no-color
When something bad happens, it restores the subdirectory, so all the changes
after running this script should be tested.
After that, you can create multiple PRs from those unstaged changes.

chore: add a script for updating package-lock.json

---

packages/bazel-bot/cloudbuild.yaml

Actually pass the substitution variable into the action.

fix: _BROKEN_SHAS should be passed to job

---

packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/src/logging/logging-octokit-plugin.ts
packages/gcf-utils/test/gcf-bootstrapper.ts
packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts

This update has a change for @octokit/rest, from 18.5.3 to 18.5.6.
There is a known type imcompatibility (see: #1908).
Marking this as a breaking change.
fixes #1987
It looks like we don't need the pin any more.

chore(gcf-utils)!: lock file maintenance

---

scripts/update-dependencies.sh
scripts/update-package-locks.sh

I changed the name of the script to `update-dependencies.sh`.
You need to install npm-check-updates in order to use this script now.
```
npm i -g npm-check-updates
```
The script will try to update everything to the latest version (including major bump) with `ncu -u`, then run
`npm i`, `npm audit fix`, `npm run fix`, then `npm run test`.
When the first trial fails, it falls back to do the same thing without
updating `package.json` file.
If you give arguments to this script, it only iterates the given directories.
Example:
```
$ scripts/update-dependencies.sh packages/snippet-bot packages/bot-config-utils
```
fixes #2036 
#2040 and #2042 are example results.
This solves some problems with the current renovate solutions.
- Gives flexibility of how many packages in one single PR
- This …

build: add npm-check-updates to update-package.locks.sh

---

packages/gcf-utils/src/gcf-utils.ts

cleanup(gcf-utils): use Probot constructor instead of createProbot

---

packages/gcf-utils/src/gcf-utils.ts

Reverts googleapis/repo-automation-bots#2066
At a certain point in the past, `createProbot(options)` was marked as deprecated, but I just noticed the current form of `createProbot` is not deprecated.
I think we should stick with createProbot for populating some options from the environment variables.
Is it correctly handled by release-please?

Revert "cleanup(gcf-utils): use Probot constructor instead of createProbot"

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

* For all requests, verify the signature before taking any actions.
* When queuing a task, re-sign the request body (which is not necessarily the webhook payload)
Not really a breaking change, but forcing a major version bump.

fix!: verify payload signatures

---

packages/canary-bot/src/app.ts

I have a theory that the scheduler proxy is incorrectly signing the requests

fix: temporarily disable canary payload verification

---

packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

OwlBot will now default to a successful status check if it's not configured on a repository (as indicated by the presence of a `.OwlBot.lock`).
This will allow OwlBot to be configured as a required check mid-migration.
Refs: #1714

feat(owlbot): indicate success if OwlBot is not enabled

---

serverless-scheduler-proxy/main.go

Fixes 2 issues with the signing:
1. We are not prepending the `sha1=`
2. We are not using the correct secret value. The secret from Secret Manager is actually a JSON blob and the secret is one value from it that we need to parse out. (previously, we were using the entire secrets blob as the secret)
3. The signatures should be hex encoded, not base64
Fixes #2092

fix: fix serverless proxy signing

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

`@octokit/auth-app` distinguishes between unset and falsy. We need to make sure we do not set installation id if we want an installationless octokit instance.
Fixes #2107

fix: only provide the installationId if set

---

packages/owl-bot/src/core.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts
packages/owl-bot/test/owl-core.ts
packages/trusted-contribution/src/config-schema.json
packages/trusted-contribution/src/config.ts
packages/trusted-contribution/src/trusted-contribution.ts
packages/trusted-contribution/test/trusted-contribution.ts

Along with running `kokoro:run` for trusted contributors, we need to make sure to run `owlbot:run`.
Refs #1714

fix(owlbot): add owbot:run for trusted contributors

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

* Introduces 3 new configuration parameters:
* `maxRetries` - max retries for GitHub webhook events. defaults to 10
* `maxCronRetries` - max retries for cron events. defaults to 0
* `maxPubSubRetries` - max retries for pubsub events. defaults to 0
* All handlers now go through Cloud Tasks - no requests are handled directly by the webhook source (Pub/Sub, Cron, or GitHub webhook).
* Deprecates the `background` configuration option. It now sets retries to 0 for all payload types. This option was originally there when the payload size was too large for Cloud Tasks, but that was resolved by writing the payload to the GCS.

feat: add max retries config options

---

packages/merge-on-green/index.yaml

We added a filter in the datastore query for PRs. This is the index.yaml used to configure the now necessary index.

build: add index.yaml for datastore indexes

---

cloudbuild-test/Dockerfile
packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts
packages/gcf-utils/test/server.ts

* Changes the constructor argument from positional args to an options object (technically breaking, but the only usage is in our tests).
* Default options to reading from the environment variables
* Throws errors early if required options are not set (rather than crashing later or having unexpected behavior)
* Refactors the tests to only set env variables for the duration of a single test.
Fixes #2139

feat: allow configuration of GCFBootstrapper via constructor arguments

---

packages/owl-bot/cloudbuild.yaml

In #2141, I forgot to add a step for deploying scheduler jobs from
cron.yaml.

fix(owl-bot): deploy scheduler jobs in cron.yaml

---

packages/cron-utils/src/cron-utils.ts

fix #2163
Sorry I thought I tested the last change locally, but I didn't test it
properly. This time I started from 180s scheduler job and updated it to
540s deadline with the updated code.

fix(cron-utils): correctly set attemptDeadline at top level

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/fixtures/payload.json
packages/gcf-utils/test/gcf-bootstrapper.ts

The `req.body` is a parsed json object. We should use the raw body
for signature verification.

fix(gcf-utils): use raw body for signature verification

---

packages/canary-bot/package-lock.json
packages/canary-bot/package.json

This version of gcf-utils started to use rawBody for signature
verification.
We want to make sure this change works.

chore(canary-bot): update to gcf-utils@11.3.1

---

packages/canary-bot/src/canary-bot.ts
packages/canary-bot/test/test.ts

This will allow us to run multiple copies of canary bot (GCF & Cloud Run). Since they will have different installation ids, both bots can comment on the same repository issue.
The cron behavior is now:
* if the specially named issue is found, find or update the comment with diagnostics
* otherwise, open the issue with diagnostics

fix: canary comments on issue instead of updating issue body

---

packages/owl-bot/cloudbuild.yaml
scripts/publish-cloud-run.sh

for deploying Cloud Run
gcloud complains with longer timeout:
```
Timeout duration must be less than 15m. Timeouts above 15m are in Beta.
Use "gcloud beta run ..." to set timeouts above 15m.
```

fix: use gcloud beta run

---

packages/owl-bot/src/app.ts

We performed a real world stress tests with 80 PRs labeled with
`owlbot:run`. While owl-bot finished all the jobs, some tasks are
retried 4 or 5 times already.
Since we made the owl-bot check a mandatory check, we should minimize
the posibility of discarding the job. Maybe we should change to pull
model, but it needs some design changes.

fix(owl-bot): bump the maxRetries to 30

---

packages/snippet-bot/src/region-tag-parser.ts
packages/snippet-bot/test/region-tag-parser.ts

part of #2246
This is not a complete solution, but pragmatically it will work well.
The bot used to die when there is a file larger than 1MB.
With this PR, the bot ignores such an error. Most of the cases, those
large files are data files and they normally don't include region tags.

fix(snippet-bot): skip errors when fetching renamed files

---

packages/release-please/src/release-please.ts

We are logging the full label objects as strings which makes the logs appear like `[object], [object]`. We actually want to log the label names.

fix: log label names rather than objects

---

packages/owl-bot/cloudbuild.yaml
scripts/publish-cloud-run.sh

I recommend that we set minInstances to 3 for not dropping webhook
requests and set concurrency to 40 because we have seen some errors in
gRPC stack (#2265) with the default 80 concurrency.

fix(owl-bot): Set minInstances to 3, concurrency to 40.

---

packages/release-please/package-lock.json
packages/release-please/package.json

We're seeing a ton of exceptions `PathNotFoundError: Could not find requested path: google-api-client/src/main/java/com/google/api/client/googleapis/GoogleUtils.java` starting 18 hours ago which matches up with this release
See #2335

Revert "deps(release-please): release please with fix for pre-releases"

---

packages/owl-bot/src/core.ts

Once we've swapped branch over we should invoke job against `main`.

fix(build): run OwlBot from main

---

packages/owl-bot/src/octokit-util.ts
packages/owl-bot/src/owl-bot.ts

Allow a certificate to be passed in to Octokit factory, rather than always reading from disk.

fix(owlbot): allow a certificate to be passed in

---

scripts/cron-deploy.sh

We still need to add the environment variable in cloudbuild.yaml in each package

fix(cron-deploy): support different project for cron deployment

---

packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

When updating an existing pull request, Owl Bot should be pushing changes to the pull request's branch, not the main branch.
Error as seen in the wild:
```
Cloning into '/tmp/tmp-1-nvrfgINIetD7/dest'...
git checkout -b master
fatal: A branch named 'master' already exists.
```

fix: used wrong branch name in pull request

---

packages/owl-bot/cloud-build/copy-code-again.yaml

Earlier steps properly call `git config --global user.name 'Owl Bot'`, with the environment variable `HOME=/workspace`.  I think git couldn't find it those credentials in the final step because `HOME` was not set.

fix: git commit failed with "please tell me who you are"

---

packages/owl-bot/src/copy-code.ts

The need for this feature arose while discussing: https://github.com/googleapis/java-spanner/pull/1356.
The spanner library maintainers want to play with proto changes and see how they would affect the library.  They'll need to invoke copy-code on a bazel-bin output directory which has no commithash.

feat: allow copy-code to use non-repo dirs as sources

---

packages/release-trigger/cloudbuild.yaml
scripts/publish-cloud-run.sh

Deploys the release-trigger bot as the `autorelease@repo-automation-bots.iam.gserviceaccount.com` service account

build(release-trigger): use custom service account

---

packages/release-trigger/src/bot.ts
packages/release-trigger/src/release-trigger.ts
packages/release-trigger/test/bot.ts
packages/release-trigger/test/release-trigger.ts

When installed org-wide, this was incorrectly triggering for all repositories rather than making sure a config file existed
fix: provide auth token to releasetool

fix: check for config file presence, then merge in defaults

---

packages/auto-label/src/auto-label.ts

I used a single metric with additional data to separate the types of
labeling. Alternatively, I could create a different metric for each `mode`.

chore(auto-label): add metrics

---

packages/owl-bot/create-post-processor-subscription.sh
packages/owl-bot/src/handlers.ts

One step towards fixing https://github.com/googleapis/repo-automation-bots/issues/1790

chore: listen to post processors being published to cloud-devrel-public-resources

---

packages/owl-bot/src/bin/commands/copy-bazel-bin.ts
packages/owl-bot/src/bin/commands/copy-code.ts

fix: loadOwlBotYaml should use path to .OwlBot.yaml file

---

packages/owl-bot/src/core.ts
packages/owl-bot/test/owl-core.ts

Reverts googleapis/repo-automation-bots#2482
I think the logic gives us false positive when there's only one commit from owlbot.

Revert "fix(owl-bot): Determine loop by the last few commits"

---

packages/mono-repo-publish/bin/mono-repo-publish.js
packages/mono-repo-publish/src/main.js
packages/mono-repo-publish/test/main.test.js

A stale node_modules folder one level up from src/apis was breaking the publication
of submodules for google-api-nodejs-client. This PR adds logic to cleanup the
node_modules folders after publication.
It also now throws if any errors occur during publication, so that we can more
easily detect failed publications.

fix(mono-repo-publish): root node_modules folder broke typescript compilation

---

packages/release-trigger/requirements.txt

Reverts googleapis/repo-automation-bots#2515
There's a bug in the explicit triggering of a PR where it should not use the language allowlist.

revert: "chore(deps): update dependency gcp-releasetool to v1.8.1"

---

packages/owl-bot/src/core.ts
packages/owl-bot/test/owl-core.ts

This should ease the pain for certain jobs that may require multiple, repeated owl-bot jobs

fix(owl-bot): Increase circuit breaker

---

packages/policy/policy-bigquery-schema.json
packages/policy/src/policy.ts
packages/policy/test/test.changer.ts
packages/policy/test/test.policy.ts

This adds a new policy check, `hasDefaultMain` which checks if `main` is the name of the default branch.

feat(policy): add a check for default branch name

---

scripts/publish-cloud-run-secret-rotator.sh

Fixes:
```
Already have image (with digest): gcr.io/cloud-builders/gcloud
./scripts/publish-cloud-run-secret-rotator.sh: line 27: pushd: secret-rotator: No such file or directory
```

build: fix deployment script for secret rotator

---

packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

We have logic in place that attempts to detect too many updates from OwlBot in a row and break loops (_this was because we've had bad releases of post processors in the past that created infinite commits_).
This PR updates the logic so that this safety is skipped if an `owlbot:run` label has explicitly been added.

fix(owlbot): always run post-processor if "owlbot:run" label added

---

packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

I worry that we still might end up with infinite loop if trusted contributor bot keeps adding `owlbot:run` and we're in a looping update situation.

fix(owlbot): break loop if bot account added label

---

packages/release-brancher/__snapshots__/release-brancher.js
packages/release-brancher/src/release-brancher.ts
packages/release-brancher/test/release-brancher.ts

Before this fix, the release-brancher command-line tool was not working. See #2617. I think this is the recent change in https://github.com/googleapis/code-suggester/pull/262/files.
After this fix, the tool works to create pull requests:
Fixes #2617 🦕

fix(release-brancher): provide default branch name for PRs

---

packages/release-brancher/__snapshots__/release-brancher.js
packages/release-brancher/src/release-brancher.ts
packages/release-brancher/test/release-brancher.ts

Use "ci: " suffix in the commit message when it creates a workflow pull request for initializing the protected branch. This addresses @chingor13 's comment in https://github.com/googleapis/repo-automation-bots/pull/2615#discussion_r717957080
Fixes #2568 🦕

fix(release-brancher): use "ci:" (non-releasable) in init

---

packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
packages/owl-bot/test/commit-post-processor-update.ts

The problem is that "git commit --amend --no-edit" always replaces
the most recent commit even when no changes are pending.

fix: prevent post processor running infinite times

---

packages/owl-bot/cloud-build/update-pr.yaml

First step in using a cloud build account with very few permissions
for post processor.

chore: write logs to a dedicated bucket

---

packages/owl-bot/src/scan-and-retry-failed-lock-updates.ts
packages/owl-bot/test/scan-and-retry-failed-lock-updates.ts

Fixes https://github.com/googleapis/repo-automation-bots/issues/2796

fix: owl bot endlessly retried failed owl-bot-lock builds

---

packages/do-not-merge/src/do-not-merge.ts

For do-not-merge it's safe to default to defaultConfig if we fail to load
remote configuration
Fixes #2739

fix(do-not-merge): ignore failures loading config

---

packages/policy/src/policy.ts
packages/policy/test/test.bot.ts
packages/policy/test/test.policy.ts

If there's an intermittent error loading config files, prior to this change this
was treated as a 404. Rather than doing this, bubble the error. This will allow
us to investigate how common of an occurrence this is.
Fixes #1924

fix(policy): bubble error when fetching files

---

packages/auto-label/src/auto-label.ts

Add some extra logs to help debug and track staleness feature
Fixes #[2751](https://github.com/googleapis/repo-automation-bots/issues/2751) 🦕

chore: add more log printouts for staleness fix

---

packages/auto-label/src/config-schema.json

Fix the schema for staleness configuration
Fixes #[2751](https://github.com/googleapis/repo-automation-bots/issues/2751) 🦕

fix(auto-label): add staleness to config schema

---

packages/bazel-bot/cloudbuild.yaml
packages/bazel-bot/docker-image/docker-main.sh
packages/bazel-bot/docker-image/generate-googleapis-gen.sh

We assume that both googleapis and googleapis-gen have been checked
out on the desired branches, and then push to the same branch after
generation.
Note that this won't automatically start synching preview branches - it just allows us to create a new trigger that *will* do so.
(Discussed internally prior to coding. I can create an issue specifically to be fixed by this if that's desirable.)

feat(bazel-bot): allow Bazel Bot to push to non-default branches

---

packages/bazel-bot/docker-image/Dockerfile

Allow the update command to continue downloading data from a repository which changed its information of the release contained in the repository indicating e.g a new major release.
We should be mindful rolling out this update to bazel-bot, due to above warning. The actual tag that changed was stable to oldstable, which makes me think it's not actually a breaking change just one of our dependencies moving locatoins.

build(bazel-bot): build with --allow-releaseinfo-change

---

packages/bazel-bot/docker-image/generate-googleapis-gen.sh

We should upgrade the Docker base image eventually so we get a new version
of git, but for now this will at least unblock Bazel Bot (without
removing preview functionality).

fix(bazel-bot): Temporary fix for #2996 to specify the branch

---

packages/owl-bot/cloudbuild.yaml
packages/owl-bot/package.json
packages/owl-bot/src/fetch-configs.ts

Upgrading owl-bot's cloud function to v14. The Dockerfiles were already running on v14.

build(owl-bot): Upgrade `owl-bot` Cloud Function to Node v14

---

packages/bazel-bot/docker-image/generate-googleapis-gen.sh

fix(bazel-bot): skip declaring bash variable read-only

---

packages/repo-metadata-lint/cloudbuild.yaml

Use an alternate service account key for repo-metadata-lint.

build(repo-metadata-lint): use alternate key

---

packages/repo-metadata-lint/cron.yaml
packages/repo-metadata-lint/src/repo-metadata-lint.ts
packages/repo-metadata-lint/test/repo-metadata-lint.ts

Wires together the moving parts of the linter, but currently only logs to console.

feat(repo-metadata-lint): wire up logging-only version of linter

---

packages/auto-label/README.md

Add spacing to packages/auto-label/README.md to improve readability

docs(auto-label): add spacing to README.md

---

packages/owl-bot/src/config-files.ts
packages/owl-bot/src/copy-code.ts
packages/owl-bot/src/create-pr.ts
packages/owl-bot/src/owl-bot-yaml-schema.json
packages/owl-bot/src/update-lock.ts
packages/owl-bot/test/config-files.ts
packages/owl-bot/test/create-pr.ts
packages/owl-bot/test/update-lock.ts

The repo maintainers need to specify an `api-name` in `.OwlBot.yaml`.  This is annoying, but necessary because:
1. Split repos don't want the API name in the PR title, so there has to be a way of turning it on and off.
2. If there's going to be a flag in `.OwlBot.yaml`, then may as well make it the name of the API instead of using a boolean flag and writing clever code to guess the API name from directory structure.
Fixes #3028

feat(owl-bot): Include the API name in the title of pull requests.

---

packages/repo-metadata-lint/src/repo-metadata-lint.ts
packages/repo-metadata-lint/test/repo-metadata-lint.ts

The opener method closes PRs if they no longer have problems, so it
should always be run.

fix(repo-metadata-lint): always run opener

---

packages/owl-bot/src/copy-code.ts
packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

because it's a private repo now

fix: use a token when cloning googleapis-gen

---

packages/owl-bot/src/bin/commands/copy-code.ts
packages/owl-bot/src/cmd.ts
packages/owl-bot/src/copy-code.ts

Make it possiblet to continue running local copy of copy-code by passing in a user access token.

fix(owlbot-cli): allow token to be passed to copy-code

---

packages/release-please/src/release-please.ts

The manifest caches the release config so reload it after a release.
Towards https://github.com/googleapis/release-please/issues/1208

fix: reload manifest after creating a release

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

This will allow us to run a separate frontend service from the backend service. The frontend will still queue to the task queue named after the bot, but it can target a different backend GCF/Cloud Run instance. This will allow us to tune the frontend/backend scaling differently.
To use, add `taskTargetName` option when initializing `GCFBootstrapper`.
Towards #2744

feat: allow overriding the backend service name

---

packages/canary-bot/cloudbuild.yaml
scripts/publish-cloud-run.sh

Fixes canary deployment. The bot uses the bot name to fetch it's credentials.

fix: allow overriding Cloud Run service name in deployment

---

packages/release-trigger/cloudbuild-test.yaml
packages/release-trigger/cloudbuild.yaml
packages/release-trigger/package-lock.json
packages/release-trigger/package.json
packages/release-trigger/src/server.ts
packages/release-trigger/test/bot.ts
scripts/publish-cloud-run.sh

Deploys a separate release-trigger backend that only runs with concurrency of 4. This allows the front-end to handle all the webhooks which require a 10 second response at 80 concurrency. This actual backend work which requires significantly more memory is now throttled at 4 concurrent requests.
Fixes #3105 
Fixes #2744

fix(release-trigger): split deployment of front/backend

---

packages/owl-bot/src/bin/commands/scan-and-retry-failed-lock-updates.ts

Follow up to https://github.com/googleapis/repo-automation-bots/pull/3117
Fixes https://github.com/googleapis/repo-automation-bots/issues/2709

fix: flip flag to create PRs for failed lock updates

---

packages/release-please/package-lock.json
packages/release-please/package.json

* Manifest.fromFile no longer ignores manifestFile arg
* multi-component manifest release notes for single component release
* release notes should parse initial version heading
* delegate empty commit handling to strategies
* extra file should include strategy path

deps: update release-please to 13.4.4

---

packages/release-please/src/release-please.ts
packages/release-please/test/release-please.ts

In v13, release-please is more capable of detecting the default package name. This GitHub app does not have enough knowledge to accurately determine the default package name.

fix: allow release-please to handle default package name

---

packages/owl-bot/src/copy-code.ts
packages/owl-bot/src/create-pr.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/src/update-lock.ts
packages/owl-bot/test/create-pr.ts
packages/owl-bot/test/owl-bot.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
packages/owl-bot/test/update-lock.ts

The fundamental problem was that `git log --format=%s%n%n%b` considers multiple lines at the top of a commit message to be the "subject".  It expects the subject and body to be separated by a blank line.
Instead, use `git log --format=%B` which gives one raw text of the combined subject and body.  Then, owl-bot takes the first line.
Fixes #3039

fix: run-on pull request titles

---

packages/cherry-pick-bot/__snapshots__/cherry-pick.js
packages/cherry-pick-bot/package-lock.json
packages/cherry-pick-bot/package.json
packages/cherry-pick-bot/src/cherry-pick.ts
packages/cherry-pick-bot/test/cherry-pick.ts

Currently, the cherry-picked PR title is something like `chore: cherry-pick <SHA> to <branch>`. If this is auto-merged or squash merged, the commit message will be incorrect.

fix: cherry-pick PR title should match commit message

---

packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
packages/conventional-commit-lint/src/conventional-commit-lint.ts
packages/conventional-commit-lint/test/conventional-commit-lint.ts

fix(conventional-commit-lint): check if automerge is enabled before using commit message vs title message

---

packages/repo-metadata-lint/src/repo-metadata-schema.json
packages/repo-metadata-lint/test/validate.ts

feat(repo-metadata-lint): Allow 'unreleased' as a release_level

---

packages/owl-bot/src/core.ts
packages/owl-bot/src/maybe-create-pull-request-for-copy.ts
packages/owl-bot/test/maybe-create-pull-request-for-copy.ts
packages/owl-bot/test/owl-bot.ts

Calls were failing with ` HttpError: Reference does not exist`
The ref needs a `heads/` prefix to delete a branch, as described here https://github.com/octokit/octokit.rb/issues/363
Fixes https://github.com/googleapis/repo-automation-bots/issues/3071

fix: calls to github.git.deleteRef

---

packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
packages/owl-bot/src/bin/commands/copy-code-into-pull-request.ts
packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
packages/owl-bot/src/copy-code.ts
packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

Flags prevented these obsolete code paths from executing, so they're safe to delete.

chore: delete obsolete code paths

---

packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

So remove the flag, and make the copyStateStore argument required.

fix: owl-bot now only tracks copies in firestore

---

packages/owl-bot/src/copy-code.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

fix: filter commit messages when regenerating a pull request

---

packages/auto-approve/README.md
packages/auto-approve/__snapshots__/check-config.test.js
packages/auto-approve/src/check-pr-v2.ts
packages/auto-approve/src/process-checks/java/apiary-codegen.ts
packages/auto-approve/src/process-checks/php/apiary-codegen.ts
packages/auto-approve/src/valid-pr-schema-v2.json
packages/auto-approve/test/java-apiary-codegen.test.ts
packages/auto-approve/test/php-apairy-codegen.test.ts

With the migration off of autosynth, apiary codegen for PHP and Java is using GitHub actions PRs from forks. We can no longer auto-approve via the GitHub actions workflows.
This adds 2 new auto-approve rules that check author and title patterns.

feat(auto-approve): add rules for Java/PHP apiary codegen

---

packages/datastore-lock/README.md
packages/datastore-lock/src/datastore-lock.ts
packages/datastore-lock/test/datastore-lock.ts

Add a peek method, for checking if lock exists without claiming a lock.

feat(datastor-lock): add peek method

---

packages/owl-bot/package-lock.json
packages/owl-bot/package.json
packages/owl-bot/src/app.ts
packages/owl-bot/src/bin/commands/test-webhook.ts
packages/owl-bot/src/cmd.ts
packages/owl-bot/src/core.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/src/run-probot-locally.ts
packages/owl-bot/test/owl-bot.ts

If a label and synchronize event happen in conjunction, it leads to two post-processor
runs kicking off. We now lock for 60s on SHA to prevent this from happening.
Fixes #3225

fix(owlbot): lock post-processor on SHA to prevent race conditions

---

packages/release-please/src/config-schema.json
packages/release-please/test/config-schema.ts
packages/release-please/test/fixtures/config/extra_files_json.yml
packages/release-please/test/fixtures/config/extra_files_xml.yml
packages/release-please/test/fixtures/config/invalid.yml

In release-please 13.6.0, we added the ability to specify generic JSON and XML files for updating with jsonpath/xpath specifiers respectively.
This PR adds those config options to the config file validation and adds a few tests to verify that the new schema works.

fix(release-please): allow json/xml extraFiles configuration options

---

packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

Currently, owlbot obtains a lock on a owner/repo/sha as soon as an event that could trigger a post-processor event runs. Instead, it should only attempt to run the post-processor under a lock.
This change moves the lock acquisition to a helper that wraps the run post-processor logic. This allows the webhook handlers to do their pre-checks and clean up no matter if it actually ends up running the post-processor or not.
Fixes #3257

fix(owl-bot): only use lock around running post-processor

---

packages/owl-bot/Dockerfile.backend
packages/owl-bot/cloudbuild.yaml
packages/owl-bot/package.json
packages/owl-bot/src/server-backend.ts

This should be safely deployed because there's no changes in the
frontend and cloud functions deployment.
After deploying the backend, we can change the task target in the
frontend to switch the backend.
Towards #3318

build(owl-bot): deploy backend in cloud run

---

packages/owl-bot/src/server-frontend.ts

fixes #3318 
This PR will change the task target to the backend deployed in Cloud Run.

build(owl-bot): route traffic to the cloud-run backend

---

packages/owl-bot/src/server-frontend.ts

Reverts googleapis/repo-automation-bots#3322
This PR is to revert the routing change in #3322.

Revert "build(owl-bot): route traffic to the cloud-run backend"

---

packages/auto-label/README.md
packages/auto-label/src/helper.ts
packages/auto-label/test/auto-label.ts
packages/auto-label/test/fixtures/events/pr_updates_size_change.json

Changing the T-Shirt size categories and providing an ability to mark empty pull requests
Fixes #[3324](https://github.com/googleapis/repo-automation-bots/issues/3324) 🦕

fix: Auto-label/size-label bot size calculations should be changed

---

packages/owl-bot/src/docker-api.ts
packages/owl-bot/system-test/docker-api.ts

Fixes https://github.com/googleapis/repo-automation-bots/issues/3293
Fixes https://github.com/googleapis/repo-automation-bots/issues/3251

fix: ignore tags in dockerUri when fetching config

---

packages/canary-bot/src/server.ts

Otherwise it enqueues a task with a wrong target name
(canary_bot_cloud_run).

fix(canary-bot): specify the correct task target name

---

packages/canary-bot/package-lock.json
packages/canary-bot/package.json

chore(canary-bot): use debug version of gcf-utils

---

packages/label-sync/src/labels.json

Start differentiating between automation work and core Node.js work.

feat(label-sync): add label for automation-team

---

packages/gcf-utils/src/gcf-utils.ts

towards #3344
I'll test this with the canary bot.

feat(gcf-utils): add an oicd token of the task caller service account

---

packages/canary-bot/cloudbuild.yaml
packages/canary-bot/package-lock.json
packages/canary-bot/package.json
packages/canary-bot/src/server.ts
scripts/publish-cloud-run.sh

Also route the canary-bot-cloud-run to the Cloud Run backend and narrow the backend access.

chore(canary-bot): Use gcf-utils 13.3.0

---

packages/label-sync/src/labels.json

I broke label sync by having colors that weren't unique (TIL).
I changed both colliding labels because I believe we're not in a broken state.

fix(label-sync): colors must be unique

---

packages/owl-bot/src/server-frontend.ts

This reverts commit 023b62716a172e94fb225e0a2b0960183ae879cc.
This is to roll back owl-bot.

Revert "build(owl-bot): route traffic to the cloud run backend (#3383)"

---

packages/owl-bot/src/server-frontend.ts

The third trial for owl-bot Cloud Run backend.

build(owl-bot): route tasks to Cloud Run backend

---

packages/owl-bot/src/server-frontend.ts

Reverts googleapis/repo-automation-bots#3387
This reverts Cloud task to the original owl-bot Cloud Functions backend.

Revert "build(owl-bot): route tasks to Cloud Run backend"

---

packages/owl-bot/src/server-backend.ts

This is solely for debugging purposes.
I will craft a Cloud Task task pointing to the Cloud Run service and verify the backend service is working correctly.

build(owl-bot): temporarily disable signature verification

---

packages/owl-bot/cloudbuild.yaml

I just created the service account "owl-bot-web-backend@repo-automation-bots.iam.gserviceaccount.com" and added necessary permissions.

build(owl-bot): use owl-bot service account for the backend

---

packages/owl-bot/src/server-backend.ts

Reverts googleapis/repo-automation-bots#3392
It should be reverted after debugging.

Revert "build(owl-bot): temporarily disable signature verification"

---

packages/owl-bot/src/core.ts

Make it easier to detect a build error in logs.
Refs: #3402

debug(owl-bot): log build error

---

packages/auto-label/src/auto-label.ts

We are getting "HttpError: Label does not exist" on `addLabels` call. Based on https://octokit.github.io/rest.js/v18, such error could be thrown only on `removeLabel` API only - to be sure to outcome GitHub bug, the fix should be wrap calls in `catch` to avoid crash.  
Fixes #[3429](https://github.com/googleapis/repo-automation-bots/issues/3429) 🦕

fix: receiving unhandled rejection applying label to java-cloud-bom

---

packages/auto-approve/cloudbuild.yaml
packages/auto-label/cloudbuild.yaml
packages/blunderbuss/cloudbuild.yaml
packages/cherry-pick-bot/cloudbuild.yaml

`web-backend` is a new service account dedicated for running our bots.
This PR will use `web-backend` service account for the following 4 bots:
- auto-approve
- auto-label
- blunderbuss
- cherry-pick-bot
Part of #3424

build: use web-backend service account for deployments

---

packages/owl-bot/package-lock.json
packages/owl-bot/package.json
packages/owl-bot/src/owl-bot.ts

There are legitimate reasons this error might happen, e.g., lock times out and another post-processor build kicks off in the interim.
Still warn, but stop throwing.

fix(owlbot): stop crashing on DatastoreLockError

---

packages/release-please/package-lock.json
packages/release-please/package.json

* bump retries for pull request iterator from 1 to 3
* don't crash when pull request iterator GraphQL returns no response
* fixed maxResults check in tag and release iterators
* GraphQL retry now uses exponential backoff
* **java:** snapshots should bump versionsMap versions
* **ruby-yoshi:** Remove bolded scope and fix link removal

deps: update release-please to 13.10.2

---

packages/release-please/cloudbuild.yaml
packages/snippet-bot/cloudbuild.yaml
packages/sync-repo-settings/cloudbuild.yaml
packages/trusted-contribution/cloudbuild.yaml

for the following 4 bots:
- release-please
- snippet-bot
- sync-repo-settings
- trusted-contribution
part of #3424

build: use web-backend service account for bot deployments

---

packages/generated-files-bot/cloudbuild.yaml
packages/header-checker-lint/cloudbuild.yaml
packages/merge-on-green/cloudbuild.yaml
packages/policy/cloudbuild.yaml

for the following 4 bots:
- generated-files-bot
- header-checker-lint
- merge-on-green
- policy
The policy-bot is using its own service account because it needs
BigQuery permission.
part of #3424

build: use dedicated service accounts

---

packages/label-sync/cloudbuild.yaml

part of #3424 
This is the last one.

build(label-sync): use web-backend service account

---

.github/.OwlBot.lock.yaml
.github/sync-repo-settings.yaml

Reverts googleapis/repo-automation-bots#3443
We don't want to use the same branch protection as our other nodejs libraries

Revert "build: sdd srs yaml file (#1419)"

---

packages/gcf-utils/src/gcf-utils.ts

Having moved to Cloud Run, jobs can run longer than 9 minutes, however the default cloud task duration is 10 minutes.
This pulls it out to 30 minutes
Refs: #3303
---
Note: I looked through the last 1000 Cloud Build jobs, only one job took longer than 10 minutes.

fix(owl-bot): allow 30 minutes of execution before retry

---

.kokoro/release/publish.cfg

Using v16 LTS should pull in a version of npm compatible with v2 of lockfile.

fix(build): use newer npm for publication

---

packages/mono-repo-publish/src/main.js
packages/mono-repo-publish/test/main.test.js

We want to publish to wombat, but not install from wombat.
Also, we should use `npm ci` if a package-lock.json exists, which performs the install hermetically.

feat(monororepo-publish): use npm ci/install from registry

---

packages/bazel-bot/cloudbuild.yaml

We are hitting an issue where we need to rebuild every API and it's taking over 2 hours

fix: bump bazel-bot timeout to 3 hours

---

packages/owl-bot/cloud-build/scan-googleapis-gen-and-create-pull-requests.yaml

It's getting stuck on google-cloud-ruby's single mono-repo PR.
Towards #3507

fix(owl-bot): bump scan-googleapis-gen-and-create-pull-requests timeout to 4h

---

packages/owl-bot/src/cmd.ts
packages/owl-bot/src/copy-code.ts
packages/owl-bot/src/create-pr.ts
packages/owl-bot/src/logger.ts
packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts

to see where scan-googleapis-gen-and-create-pull-requests is using its time.

feat: add timestamps to log statements

---

packages/owl-bot/src/copy-code.ts

by only globbing the directory structures once.

fix: accelerate copying code into monorepos

---

scripts/serverless-scheduler-proxy-deploy.sh

fixes #3424 
Depends on an internal cl to get merged first.

build(serverless-scheduler-proxy): use scheduler-proxy service account

---

serverless-scheduler-proxy/cloudbuild-test.yaml

Future PRs touching the serverless-scheduler-proxy directory will trigger this build as a presubmit

build: create GCB test that ensures the image builds

---

serverless-scheduler-proxy/Dockerfile

The last few deployments failed.

fix(serverless-scheduler-proxy): use golang:1.18-alpine

---

packages/gcf-utils/src/gcf-utils.ts

Downstream automations may need to reference this class.

fix: export GCFLogger class

---

packages/blunderbuss/package-lock.json
packages/blunderbuss/package.json
packages/bot-config-utils/package-lock.json
packages/bot-config-utils/package.json
packages/cherry-pick-bot/package-lock.json
packages/cherry-pick-bot/package.json
packages/conventional-commit-lint/package-lock.json
packages/conventional-commit-lint/package.json
packages/datastore-lock/package-lock.json
packages/datastore-lock/package.json
packages/do-not-merge/package-lock.json
packages/do-not-merge/package.json
packages/failurechecker/package-lock.json
packages/failurechecker/package.json
packages/flakybot/package-lock.json
packages/flakybot/package.json
packages/generated-files-bot/package-lock.json
packages/generated-files-bot/package.json
packages/header-checker-lint/package-lock.json
packages/header-checker-lint/package.json
packages/label-sync/package-lock.json
packages/label-sync/package.json
packages/label-utils/package-lock.json
packages/label-utils/package.json
packages/merge-on-green/package-lock.json
packages/merge-on-green/package.json
packages/policy/package-lock.json
packages/policy/package.json
packages/snippet-bot/package-lock.json
packages/snippet-bot/package.json

Updates previously updated bots from gcf-utils 13.5.1 to 13.5.2 to fix trigger information for Cloud Task requests

deps: update gcf-utils to 13.5.2

---

packages/bot-config-utils/src/bot-config-utils.ts
packages/bot-config-utils/test/bot-config-utils.ts

Towards #3647 
Instead of a generic `Error`, we now throw a custom `InvalidConfigurationFormat` error.

fix: throw InvalidConfigurationFormat error on validation error

---

packages/release-please/package-lock.json
packages/release-please/package.json
packages/release-please/src/release-please.ts
packages/release-please/test/release-please.ts

Fixes #3649
Rather than crashing with a missing file error, we will log the misconfiguration. In the future, we could opt to open an issue on the repository.

fix: handling misconfigured manifest repos

---

packages/release-please/package-lock.json
packages/release-please/package.json
packages/release-please/src/release-please.ts

We already have a presubmit check that verifies the config format on a pull request. If the error is something like an extra field, we should not prevent release-please from running.
Fixes #3647

fix: skip schema validation when trying to run release-please

---

packages/canary-bot/cloudbuild.yaml
scripts/cron-deploy.sh
serverless-scheduler-proxy/main.go

See #2143
Unblock #3774 
fix: cloud run urls have `-uc` in them.
build: allow overriding the service name in the cron-deploy script

build(canary-bot): target cloud run with cron

---

packages/release-trigger/cron.yaml

This name field is directly used as the name field for the scheduler task and cannot contain spaces

build: fix cron scheduler job name

---

packages/release-trigger/cloudbuild.yaml
serverless-scheduler-proxy/main.go

Cron requests to the `release-trigger` Cloud Run service are failing because the proxy is looking for a secret with `release-trigger` when the actual secret is named `release_trigger` (it's using the `Name` field from the cron payload).
Canary bot for cloud run happened to work because we somehow have the bot secret twice (`canary-bot-cloud-run` and `canary_bot_cloud_run`).
This change make the `Name` in the cron payload `release_trigger` and makes the serverless proxy replace `_` with `-` when generating the Cloud Run URL.

fix: bot name is underscored, Cloud Run URL is dasherized

---

packages/release-trigger/src/bot.ts
packages/release-trigger/src/release-trigger.ts
packages/release-trigger/test/bot.ts

release-trigger is occasionally looking for tagged PRs before release-please has added the tagged label to the release PR.
Fixes #3734

fix: delay finding pending PRs on release event

---

packages/release-please/package-lock.json
packages/release-please/package.json
packages/release-please/src/release-please.ts
packages/release-please/test/release-please.ts

Updates release-please to 13.18.3 which now handles:
* bad manifest JSON files throw a `ConfigurationError`
* bad factory options in manifests throw a `ConfigurationError`
The bot now catches `ConfigurationError`s globally and maintains an issue on the repository with the `ConfigurationError`'s message.
Fixes #3870 
Fixes #3867

fix: handle bad manifest configuration files

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

Also catch GitHub API errors for secondary rate limits and return 503s
Towards #3878

fix: also handle secondary rate limit errors from GitHub API

---

packages/canary-bot/package-lock.json
packages/canary-bot/package.json

With gcf-utils 13.7.0, the task scheduler control the flow.
We want to make sure this works for canary bot's repository cron.

testing(canary-bot): enable flow control

---

packages/release-trigger/package-lock.json
packages/release-trigger/package.json

gcf-utils 13.8.0 has faster flow control by default
Testing canary bot with #3887

deps(release-trigger): use gcf-utils 13.8.0

---

packages/auto-approve/cloudbuild.yaml
packages/auto-approve/package-lock.json
packages/auto-approve/package.json

deps(auto-approve): use gcf-utils 13.8.1

---

packages/auto-label/cloudbuild.yaml
packages/auto-label/package-lock.json
packages/auto-label/package.json

deps(auto-label): use gcf-utils 13.8.1

---

packages/do-not-merge/cloudbuild.yaml
packages/do-not-merge/package-lock.json
packages/do-not-merge/package.json

deps(do-not-merge): use gcf-utils 13.8.1

---

packages/repo-metadata-lint/cloudbuild.yaml
packages/repo-metadata-lint/package-lock.json
packages/repo-metadata-lint/package.json

deps(repo-metadata-lint): use gcf-utils 13.8.1

---

packages/trusted-contribution/cloudbuild.yaml
packages/trusted-contribution/package-lock.json
packages/trusted-contribution/package.json

deps(trusted-contribution): use gcf-utils 13.8.1

---

packages/release-please/cloudbuild.yaml
packages/release-please/package-lock.json
packages/release-please/package.json

deps(release-please): use gcf-utils 13.8.1

---

packages/label-sync/cloudbuild.yaml
packages/label-sync/package-lock.json
packages/label-sync/package.json

deps(label-sync): use gcf-utils 13.8.1

---

packages/blunderbuss/README.md
packages/blunderbuss/src/blunderbuss.ts
packages/blunderbuss/src/config-schema.json
packages/blunderbuss/src/config.ts
packages/blunderbuss/test/blunderbuss.ts
packages/blunderbuss/test/fixtures/config/ignore.yml

This adds support to ignore some prs/issues based on the author. 
- Not sure what the best config name would be. 
- Also could split issues and prs.
Fixes #4023

feat(blunderbuss): allow ignoring issues and prs by some authors

---

.release-please-manifest.json
packages/issue-utils/.c8rc.json
packages/issue-utils/.eslintignore
packages/issue-utils/.eslintrc.json
packages/issue-utils/.gitignore
packages/issue-utils/.mocharc.js
packages/issue-utils/.prettierignore
packages/issue-utils/.prettierrc.js
packages/issue-utils/LICENSE
packages/issue-utils/README.md
packages/issue-utils/package-lock.json
packages/issue-utils/package.json
packages/issue-utils/src/issue-utils.ts
packages/issue-utils/test/issue-utils.ts
packages/issue-utils/tsconfig.json
release-please-config.json

Extracts `addOrUpdateIssue` into a new helper utility library. This was extracted from `release-please` which is using this to notify installed repositories of configuration errors.
Example PR: https://github.com/googleapis/google-cloud-java/issues/7948
Towards #3869

feat: add new issue-utils package

---

packages/release-please/package-lock.json
packages/release-please/package.json

This version of gcf-utils includes the fix to handle GraphQL rate limit errors with our Cloud Tasks backoff (returning 503s).
Fixes #4020

deps: update gcf-utils to 13.8.3

---

packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
packages/owlbot-bootstrapper/common-container/mono-repo.ts
packages/owlbot-bootstrapper/common-container/split-repo.ts
packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
packages/owlbot-bootstrapper/common-container/test/split-repo.test.ts
packages/owlbot-bootstrapper/common-container/test/utils.test.ts
packages/owlbot-bootstrapper/common-container/utils.ts

Turns out, owlbot looks in the commit history for the copy tag info, see: https://github.com/googleapis/repo-automation-bots/blob/82f37f98169aa63c3fb2d5fd3ea8de3c45999da3/packages/owl-bot/src/copy-code.ts#L633
Confirmed with @SurferJeffAtGoogle
This PR only implements the copy-tag logic in the commit for mono-repos, not split repos. In looking at it more closely, I think I'm going to need to refactor the split repo process to mirror the mono-repo process a bit more. I will do this in a later PR.

fix(owlbot-bootstrapper): add Copy-Tag logic in commit as well

---

packages/owlbot-bootstrapper/common-container/post-process.ts
packages/owlbot-bootstrapper/common-container/pre-process.ts

Just cosmetic, we no longer use env variables (instead we use arguments and the interContainerVars file) and this cleans them up.

chore: remove unused env variables

---

packages/owl-bot/cloud-build/copy-code-again.yaml
packages/owl-bot/src/bin/commands/copy-code-into-pull-request.ts
packages/owl-bot/src/bin/commands/test-webhook.ts
packages/owl-bot/src/copy-code.ts
packages/owl-bot/src/core.ts
packages/owl-bot/src/labels.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/core.ts
packages/owl-bot/test/owl-bot.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

Owl Bot Bootstrapper labels a pull request with 'owlbot:copy-code' to request Owl Bot to copy the source code from googleapis-gen.  The pull request must have a copy tag.
While adding this feature, I removed the obsolete command line options source-repo-commit-hash and owl-bot-yaml-path.  Owl bot already inspects the copy-tag to learn these two details.  So they were obsolete before this pull request.  It was easier to remove them than to update them for the new code path.
Fixes #4072

feat: implement owlbot:copy-code label

---

packages/sync-repo-settings/README.md

These options were already in use and described in https://github.com/googleapis/repo-automation-bots/blob/main/packages/sync-repo-settings/src/schema.json, but were missing in the README
Fixes #4081

docs(sync-repo-settings): describe all supported options

---

packages/sync-repo-settings/src/app.ts

We are seeing tons of warning logs:
```
`background` option has been deprecated in favor of `maxRetries` and `maxCronRetries`
```
sync-repo-settings is setting `background=true` which is the default and deprecated -- so we will remove the option.

chore: cleanup warning logs from unnecessary default wrap option

---

packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
packages/conventional-commit-lint/src/utils.ts

Now the bot lists all the errors first, then add the input as a
reference.
fixes #3155

fix(ccl): change the order of the error message

---

packages/mono-repo-publish/package-lock.json
packages/mono-repo-publish/src/bin/mono-repo-publish.ts
packages/mono-repo-publish/src/main.ts
packages/mono-repo-publish/test/cli.ts
packages/mono-repo-publish/test/main.test.ts

This allows you to run a custom publish script within each directory. Usage:
```bash
mono-repo-publish custom --pr-url=<github-url> --script=/path/to/publish/script.sh
```
This will allow maintainers to have their own logic about which command is run. `mono-repo-publish` will determine which folders it will need to run the script from within. For example, the custom publish script could publish to npm, then also build and publish documentation somewhere.
Additionally, we now allow providing the appId, privateKey and installationId paths via CLI arguments (can still provide via environment variables). We also added tests for the CLI parsing/argument handling.
Fixes #4096

feat: add custom command for running arbitrary publish script

---

.release-please-manifest.json
packages/mono-repo-publish/CHANGELOG.md
packages/mono-repo-publish/package-lock.json
packages/mono-repo-publish/package.json

This reverts commit 3866c91c56b494bcb5959062f85f3966cbdece30.
Attempt to fix broken finale test.
Fixes https://github.com/googleapis/repo-automation-bots/issues/4108

Revert "chore: release main (#4100)"

---

packages/release-please/package-lock.json

Attempts to fix `npm ERR! fsevents not accessible from chokidar` by regenerating package-lock.json.
Ran `rm -rf node_modules package-lock.json && npm i`.

deps: regenerate package-lock.json

---

packages/header-checker-lint/package.json

This looks like some copy-pasta from the creation of the header lint bot that was never updated.

docs: fix description of header checker lint bot

---

packages/bot-config-utils/README.md
packages/bot-config-utils/src/bot-config-utils.ts
packages/bot-config-utils/test/multi-config-checker.ts

validateConfigChanges will now resolve true or false depending on
whether the config file is valid.
Refs: https://github.com/googleapis/repo-automation-bots/pull/4115
---
This will allow automations that themselves create checks to short-circuit when a check has been created for a bad configuration file.

feat(bot-config-utils): resolve false on invalid config files

---

packages/bot-config-utils/src/bot-config-utils.ts

The `Checker` class had been updated, but not the public interface.
The method signature of the public interface changes, so calling this a breaking change.

feat(bot-config-utils)!: validateConfigChanges now resolve boolean for valid config

---

packages/auto-label/src/auto-label.ts

fix(auto-label): throws an Error when installation id is not provided

---

.github/workflows/links.yaml

When I ran it manually, it resulted in many 429 errors.
Example run:
https://github.com/googleapis/repo-automation-bots/actions/runs/2915039381
According to https://github.com/lycheeverse/lychee-action/issues/97 we can fix it by limiting concurrency.

chore: limit concurrency for link checking job

---

packages/owlbot-bootstrapper/common-container/cloudbuild-deploy-container.yaml

Error from cloud build:
```
"docker push" requires exactly 1 argument.
See 'docker push --help'.
Usage:  docker push [OPTIONS] NAME[:TAG]
```

fix(owlbot-bootstrapper): push docker image to artifact registry

---

packages/snippet-bot/src/utils.ts
packages/snippet-bot/test/utils.ts

fix(snippet-bot): make formatBody resilient to an empty body

---

packages/snippet-bot/src/utils.ts
packages/snippet-bot/test/utils.ts

fix(snippet-bot): convert null value to an empty string

---

packages/cherry-pick-bot/src/bot.ts
packages/cherry-pick-bot/test/bot.ts

The pull request API is returning a SHA value for `merge_commit_sha` on an unmerged pull request - we were using this field as a proxy for merged status. Now, use the explicit `merged` (boolean) field to determine merge status.
Fixes #4239

fix: look at pull `merged` field to determine merged status

---

.github/workflows/links.yaml
renovate.json

also added version tag at the end of the current commit hashes
I think this PR will stop renovate to create PR like #4287

chore: configure renovate to use commit hash for github actions

---

packages/release-please/src/release-please.ts

The sentence-case plugin has been tested, let's turn it on for googleapis.
_Example of it working:_

feat(release-please): enable sentence-case for googleapis

---

packages/mono-repo-publish/package-lock.json
packages/mono-repo-publish/package.json
packages/mono-repo-publish/src/bin/mono-repo-publish.ts
packages/mono-repo-publish/src/main.ts
packages/mono-repo-publish/test/cli.ts
packages/mono-repo-publish/test/main.test.ts

Towards https://github.com/googleapis/google-cloud-node/issues/3332
Allows you to provide a `--exclude-files=<some glob>` to ignore certain paths. For example, in googleapis/google-cloud-node, we could set `--exclude-files=**/samples/*` to skip all the samples modules from being published.

feat(mono-repo-publish): add --exclude-files option

---

renovate.json

Currently, all the lock file update PRs have the same title, even though they are grouped by parent directory. This should add context to the renovate lock file PRs.
The [docs](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance) do not mention if the `{{parentDir}}` macro is available, but it's worth a try.

chore: add parent directory to lock file update PRs

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts
packages/gcf-utils/test/gcf-utils.ts

This should make Cloud Error Reporting great again.

feat(gcf-utils): Add @type property for unhandled errors.

---

packages/repo-metadata-lint/package-lock.json
packages/repo-metadata-lint/package.json

deps(repo-metadata-lint): update gcf-utils to V14.2.0

---

packages/blunderbuss/package-lock.json
packages/blunderbuss/package.json

deps(blunderbuss): update gcf-utils to V14.2.0

---

packages/conventional-commit-lint/package-lock.json
packages/conventional-commit-lint/package.json

deps(conventional-commit-lint): update gcf-utils to V14.2.0

---

packages/failurechecker/package-lock.json
packages/failurechecker/package.json

deps(failurechecker): update gcf-utils to V14.2.0

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

Because it doesn't change within a single deployment lifecycle.
fixes #4469

fix(gcf-utils): cache Cloud Run service URL

---

packages/canary-bot/package-lock.json
packages/canary-bot/package.json

With this version, gcf-utils will cache Cloud Run URL.

deps(canary-bot): update gcf-utils to V14.2.1

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

A bot can throw ServiceUnavailable when it experiences resource limitation. The next task attempt will be delayed with some backoff.
fixes #4495

feat(gcf-utils): introduce ServiceUnavailable

---

packages/release-please/package-lock.json
packages/release-please/package.json

Includes:
* fix for google-cloud-java's maven-workspace plugin
* fix for erroneously adding schema to versions manifest

deps: update release-please to 14.10.2

---

packages/release-trigger/src/bot.ts
packages/release-trigger/src/release-trigger.ts
packages/release-trigger/test/bot.ts
packages/release-trigger/test/release-trigger.ts

This gives maintainers an idea of what release-trigger tried to do. It also comments about how to retry the build.
It should comment with something like:
```
Triggered job: <my-job-name> (<iso-date>)
To trigger again, remove the 'autorelease: triggered' label (in a few minutes).
```
fix(release-trigger): use the context logger in the bot

feat(release-trigger): comment on PR after triggering

---

packages/snippet-bot/src/configuration.ts
packages/snippet-bot/test/fixtures/diff-owl-bot.txt
packages/snippet-bot/test/snippet-bot.ts

I chose to hard code this. Ideally it's better to have it in default config, but currently we don't have a nice way to merge arrays in default config and the user config, also it's unlikely the directory will be used for other purpose.
part of #4520

fix(snippet-bot): always ignore "owl-bot-staging"

---

.github/workflows/links.yaml

Access to npmjs occationally fails with HTTP 429.
Example: #4554

chore: exclude npmjs for link checking

---

packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml
packages/owlbot-bootstrapper/cli/run-trigger-command.ts
packages/owlbot-bootstrapper/cli/run-trigger.ts
packages/owlbot-bootstrapper/cli/test/run-trigger.test.ts
packages/owlbot-bootstrapper/common-container/commands/post-process.ts
packages/owlbot-bootstrapper/common-container/commands/pre-process.ts
packages/owlbot-bootstrapper/common-container/interfaces.ts
packages/owlbot-bootstrapper/common-container/mono-repo.ts
packages/owlbot-bootstrapper/common-container/package-lock.json
packages/owlbot-bootstrapper/common-container/post-process.ts
packages/owlbot-bootstrapper/common-container/pre-process.ts
packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
packages/owlbot-bootstrapper/common-container/test/post-process.test.ts
packages/owlbot-bootstrapper/common-container/test/pre-process.test.ts
packages/owlbot-bootstrapper/common-container/test/utils.test.ts
packages/owlbot-bootstrapper/common-container/utils.ts

This feature corresponds to the work in the internal doc,`Design Doc: Providing API-specific information in owlbot-bootstrapper`. We've agreed to store the paths in env variables as opposed to constants. 
There's a small refactor in this PR as well that corresponds to the env variables. I separated out a `writeToWellKnownFile` function so that it corresponds to the environment variable that you want to write to, instead of being hidden in an `openABranch` function. This makes the env variable more obvious as to where it's being used.

feat: create, require and read env variables for MONO_REPO_PATH, SERVICE_CONFIG_PATH, INTER_CONTAINER_VARS_PATH

---

packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts

The actual command that we run is `scan-googleapis-gen-and-create-pull-requests`. This sets the default config to use nested commits.
Fixes #4535

feat: enable nested commit delimiters

---

packages/sync-repo-settings/src/schema.json
packages/sync-repo-settings/src/sync-repo-settings.ts
packages/sync-repo-settings/src/types.ts

Adds an enabled flag to turn off the sync-repo-settings bot.
Workaround for #4617

feat: add enabled flag to sync-repo-settings

---

packages/release-please/package-lock.json
packages/release-please/package.json

* php-yoshi: Add "misc" as trigger, hide "chore" (https://github.com/googleapis/release-please/issues/1725) ([f7a9d09](https://github.com/googleapis/release-please/commit/f7a9d091670f0a70a13a1b641fbc6d07ec000da2))
* Extract and return the created release id (https://github.com/googleapis/release-please/issues/1719) ([ef1c156](https://github.com/googleapis/release-please/commit/ef1c156ab1d44969548b4cb30b412b2066568aa4))
* deps: Update dependency type-fest to v3 (https://github.com/googleapis/release-please/issues/1649) ([d3c3a3e](https://github.com/googleapis/release-please/commit/d3c3a3eae6557994ad244c0bdd79e1782971d2c1))
* python: Version updater updates patch versions >= 10 (https://github.com/googleapis/release-please/issues/1708) …

deps: update release-please to 14.15.1

---

packages/release-please/package-lock.json
packages/release-please/package.json

* Allow overlapping paths when splitting commits (https://github.com/googleapis/release-please/issues/1733) ([adcb99a](https://github.com/googleapis/release-please/commit/adcb99acdbff9ddeea527b673bc8820edff68f2a))
* cargo-workspace: Update target dependencies in Cargo workspace packages (https://github.com/googleapis/release-please/issues/1730) ([3ca3bbc](https://github.com/googleapis/release-please/commit/3ca3bbcef729a359805473fdc798b5af5ab22861))
Fixes #4632

deps: update release-please to 14.15.2

---

packages/header-checker-lint/README.md
packages/header-checker-lint/__snapshots__/header-checker-lint.js
packages/header-checker-lint/src/config-schema.json
packages/header-checker-lint/src/config.ts
packages/header-checker-lint/src/header-checker-lint.ts
packages/header-checker-lint/test/header-checker-lint.ts

There are scenarios in which it is helpful to ignore the license year check, such as migrating code across repos. This PR introduces a new option `ignoreLicenseYear` to `header-checker-lint`. The default setting is `false`, so there are no changes to the current behavior.

feat: add option to ignore year in license header bot

---

packages/mono-repo-publish/src/bin/mono-repo-publish.ts

Rather than throwing an error if the app credentials are not provided, mono-repo-publish will try to use an unauthenticated client for its API calls.

feat: allow unauthentiated GitHub API usage

---

packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
packages/owlbot-bootstrapper/common-container/fetch-api-info.ts
packages/owlbot-bootstrapper/common-container/pre-process.ts
packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
packages/owlbot-bootstrapper/common-container/test/utils.test.ts
packages/owlbot-bootstrapper/common-container/utils.ts

Fixes #4675 
We were looking for the service_config.yaml file in 'main', but it should have been 'master'.
I also added a function to get the default branch for when we're creating PRs, since we don't know what each library has as their default branch. I didn't do this for requests against googleapis/googleapis though, since it will always be a constant, and it would be wasteful to grab that default branch each time.

fix(owlbot-bootstrapper): get correct default branch for bootstrapper

---

packages/release-please/package-lock.json
packages/release-please/package.json

- add always-bump-major versioning strategy (https://github.com/googleapis/release-please/issues/1744) ([7526ca8](https://github.com/googleapis/release-please/commit/7526ca8be4fec4d785b44bfb8c8c70078ad7fc73))
- Add always-bump-minor versioning strategy (https://github.com/googleapis/release-please/issues/1744) ([7526ca8](https://github.com/googleapis/release-please/commit/7526ca8be4fec4d785b44bfb8c8c70078ad7fc73))

deps: update release-please to 14.17.0

---

packages/release-please/README.md

As release-please's configuration options have gotten more and more complex, we only want to support them if you are using the manifest (json) configuration. This PR updates the documentation to recommend using a manifest config and to point to further documentation about the available configuration options.

docs: deprecate most configuration options

---

packages/gcf-utils/src/logging/gcf-logger.ts
packages/gcf-utils/test/gcf-logger.ts

When creating a child GCFLogger, also include the current bindings (context attributes).
Fixes #4439

fix: logger.child() should preserve original bindings

---

packages/snippet-bot/package-lock.json
packages/snippet-bot/package.json

gcf-utils 14.4.0 starts to upload smaller payloads directly to Cloud Task.
Related: #4480
Let's monitor snippet-bot's behavior for a while and if it works ok, maybe we can wait for rennovate to update other bots.

chore(snippet-bot): upgrade gcf-utils to 14.4.0

---

packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
packages/conventional-commit-lint/src/conventional-commit-lint.ts
packages/conventional-commit-lint/src/schema.json
packages/conventional-commit-lint/src/utils.ts
packages/conventional-commit-lint/test/conventional-commit-lint.ts
packages/conventional-commit-lint/test/fixtures/config/always_check_pr_title.yaml

When set to true, the bot will always use PR title for checking against conventional commit spec.
This new config defaults to false.
fixes #4769

feat(ccl): introduce `always_check_pr_title` config

---

packages/owl-bot/cloud-build/update-pr.yaml
packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
packages/owl-bot/test/commit-post-processor-update.ts

Fixes https://github.com/googleapis/repo-automation-bots/issues/4768

feat: post processors can specify new PR title and body

---

packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
packages/owl-bot/src/copy-code.ts
packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

The flag is initially set to infinity to preserve existing behavoir. After the code bakes for a few days, we'll set the flag to 20.
Step 1 of 2 towards fixing
https://github.com/googleapis/repo-automation-bots/issues/4763

feat: flag controls the maximum # of APIs to combine in one PR

---

packages/auto-approve/src/get-pr-info.ts

There's no point in throwing a new Error with less context than the original error.
Fixes #4479

fix(auto-approve): rethrow original request error

---

packages/cherry-pick-bot/__snapshots__/cherry-pick.js
packages/cherry-pick-bot/src/bot.ts
packages/cherry-pick-bot/src/cherry-pick.ts
packages/cherry-pick-bot/test/bot.ts
packages/cherry-pick-bot/test/cherry-pick.ts

The cherry-pick logic will throw a new `MergeConflictError` if we receive a 409 response when attempting to merge branches. The bot catches this error and will comment on the PR being cherry-picked.
Fixes #4501
Fixes #4507

feat: detect MergeConflict errors and comment on PR on failure

---

packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json

See https://github.com/googleapis/repo-automation-bots/pull/4799
4.9 chokes on a dependency.
```
node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
72 declare var AbortSignal: {
~~~~~~~~~~~
node_modules/typescript/lib/lib.dom.d.ts:2071:13
2071 declare var AbortSignal: {
~~~~~~~~~~~
'AbortSignal' was also declared here.
Found 1 error in node_modules/@types/node/globals.d.ts:72
```

fix: lock the version of typescript to 4.8.4

---

packages/bot-config-utils/package-lock.json
packages/bot-config-utils/package.json
packages/cron-utils/package-lock.json
packages/cron-utils/package.json
packages/datastore-lock/package-lock.json
packages/datastore-lock/package.json
packages/git-file-utils/package-lock.json
packages/git-file-utils/package.json

Upgrading to typescript 4.9 results in the same error for all these bots:
```
node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.
72 declare var AbortSignal: {
~~~~~~~~~~~
node_modules/typescript/lib/lib.dom.d.ts:2071:13
2071 declare var AbortSignal: {
~~~~~~~~~~~
'AbortSignal' was also declared here.
```
After merging, I'll close the following PRs:
https://github.com/googleapis/repo-automation-bots/pull/4803 https://github.com/googleapis/repo-automation-bots/pull/4796 …

fix: pin typescript to 4.8.4 for four more bots

---

packages/blunderbuss/package-lock.json
packages/blunderbuss/package.json

Instead of https://github.com/googleapis/repo-automation-bots/pull/4786.
I looked at the error, googled it,  and still I don't know how to fix it.

fix: pin typescript to 4.8.4 for blunderbuss

---

.github/workflows/interrogate.js
.github/workflows/list-node-paths-for-deps.js
.github/workflows/list-node-paths.js
packages/gcf-utils/README.md

To prevent potential leaking of output data: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Fixes #4855

build(actions): switch output to use output file

---

packages/git-file-utils/src/git-file-utils.ts
packages/git-file-utils/test/git-file-utils.ts

When a repository is uninitialized, GitHub throws a 409 error on file operations. In this library, we want to silently handle this scenario as if the repository has no files.
Towards #4474

fix: handle empty repository as if it has no files

---

packages/bot-config-utils/package-lock.json
packages/bot-config-utils/package.json
packages/cron-utils/package-lock.json
packages/cron-utils/package.json
packages/datastore-lock/package-lock.json
packages/datastore-lock/package.json
packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json
packages/git-file-utils/package-lock.json
packages/git-file-utils/package.json

Instead of:
https://github.com/googleapis/repo-automation-bots/pull/4882
https://github.com/googleapis/repo-automation-bots/pull/4881
https://github.com/googleapis/repo-automation-bots/pull/4880
https://github.com/googleapis/repo-automation-bots/pull/4879
https://github.com/googleapis/repo-automation-bots/pull/4878

chore: upgrade some packages to typescript 4.9.4

---

packages/owl-bot/src/core.ts
packages/owl-bot/src/owl-bot.ts

While debugging #4946, I found that many logs are incorrectly attributed due to using importing the default GCFLogger rather than injecting an instance with request context. When we import the shared one, the context can be incorrect because the instance is shared between concurrent requests.

fix: pass context logger to post-processor handlers

---

packages/owl-bot/src/core.ts

Allows the post-processor check to wait as long as the build before it returns to GH
Example: https://github.com/googleapis/google-cloud-node/pull/3821/checks?check_run_id=10890026001
Fixes #4946

build: increase timeout for post processor check

---

packages/owl-bot/src/core.ts

If the owlbot event handler times out waiting for the status of the post-processor GCB job, then return a better error status.
Towards #4946

fix: improve timeout error message

---

packages/policy/src/issue.ts

policy bot will no longer open an issue if the repository is not configured with renovate. We will continue to update the BigQuery dataset.

fix: ignore renovate state from opening issues

---

.release-please-manifest.json
release-please-config.json

Somehow, we never configured tagging flakybot binary releases.
We probably should move the binary to its own directory for releases separate from the webhook handler app.

build: track flakybot in releases

---

packages/release-trigger/requirements.in
packages/release-trigger/requirements.txt

Allows us to trigger the golang Kokoro jobs

deps: update releasetool to 1.12.0

---

packages/release-trigger/requirements.in
packages/release-trigger/requirements.txt

Supports triggering the correct job for google-cloudevents-ruby.

deps: update releasetool to 1.13.0

---

packages/auto-approve/README.md
packages/auto-approve/src/process-checks/node/dependency.ts
packages/auto-approve/test/additional-validation-for-versioning.test.ts

In moving to the mono-repo, we no longer have package.json in one fixed spot; this PR updates the rules to reflect that. Also, we may have more than 3 files being changed, so this updates that rule.

fix(auto-approve): update node dependency for mono repo migration

---

packages/owl-bot/cloud-build/copy-code-again.yaml

Related https://github.com/googleapis/repo-automation-bots/issues/5066

fix: set buffer size for copy-code-again flow

---

packages/repo-metadata-lint/package-lock.json
packages/repo-metadata-lint/package.json
packages/repo-metadata-lint/src/store-metadata.ts
packages/repo-metadata-lint/src/validate.ts
packages/repo-metadata-lint/test/validate.ts

Store validated fields from .repo-metadata.json in a BigQuery table, so that it can feed into team analytics, e.g., library coverage.

feat: store validated .repo-metadata in table

---

packages/owl-bot/src/copy-code.ts
packages/owl-bot/test/fake-octokit.ts
packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts

If there were no found individual PRs, make sure we look for an
existing bulk PR and append to that PR before attempting to create a
new bulk PR.
Fixes #5075

fix: update existing bulk copy-code PRs

---

packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts

This reverts commit 7b5ef7eb6e652cc05335ce801477c74f68d6aa74.
Creating draft pull requests works, but owl bot never follows up and removes the draft label.
Fixes https://github.com/googleapis/repo-automation-bots/issues/5160

Revert "fix: flip flag to turn on *draft* copy code PRs (#5157)"

---

packages/cherry-pick-bot/src/bot.ts

We have a presubmit check that does the validation. If the schema is invalid at runtime, let it fail.
Fixes #4928

fix: don't revalidate bot schema when trying to execute

---

packages/owl-bot/src/owl-bot.ts

Debugging why owl-bot is still skipping draft PRs that it shouldn't.
Debugging https://github.com/googleapis/repo-automation-bots/issues/5179

fix: log the labels when owl-bot skips draft PR

---

.github/workflows/ci.yaml
packages/gcf-utils/.eslintrc.json
packages/gcf-utils/.mocharc.js
packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json
packages/gcf-utils/src/configuration.ts
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/src/installations.ts
packages/gcf-utils/test/gcf-bootstrapper.ts
packages/gcf-utils/test/gcf-utils.ts

feat!: require node 18
feat!: remove `addOrUpdateIssueComment` which is moved to issue-utils.

refactor: use sinon to mock octokit methods

---

release-please-config.json

The root package/path is being included in releases and should not.

build: root package is not releaseable

---

packages/issue-utils/.eslintrc.json
packages/issue-utils/src/issue-comments.ts
packages/issue-utils/src/issue-utils.ts
packages/issue-utils/test/issue-comments.ts

This function was removed from gcf-utils v15 as it's not a core method needed by each bot.

feat: migrate addOrUpdateIssueComment to issue-utils

---

packages/gcf-utils/package-lock.json
packages/gcf-utils/src/installations.ts

fix
```
TypeError: Cannot read properties of undefined (reading 'getAuthenticatedOctokit')
at eachInstallation (/usr/src/app/node_modules/gcf-utils/build/src/installations.js:26:32)
at eachInstallation.next (<anonymous>)
at GCFBootstrapper.handleScheduledInstallation (/usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:492:30)
at GCFBootstrapper.handleScheduled (/usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:447:24)
at /usr/src/app/node_modules/gcf-utils/build/src/gcf-utils.js:290:32
```

fix: getAuthenticatedOctokit is a standalone method

---

packages/owlbot-bootstrapper/common-container/package-lock.json
packages/owlbot-bootstrapper/common-container/package.json

Trying to resolve a dependabot alert. snap-shot-it is a dep dependency, not used at runtime.

deps: change snap-shot-it to dev dependency

---

packages/owl-bot/src/copy-code.ts

The contents of the repo are the source of truth.  scan-googleapis-gen-and-create-pull requests queries firestore to find .OwlBot.yaml files.  Firestore may have stale data.  So if Owl Bot queries firestore, finds an .OwlBot.yaml, and then can't find the .OwlBot.yaml in the repo, then that's not actually a problem.
Fixes https://github.com/googleapis/repo-automation-bots/issues/5242

fix: don't open bug when .OwlBot.yaml is missing

---

packages/flakybot/__snapshots__/flakybot.test.js
packages/flakybot/src/flakybot.ts
packages/flakybot/test/flakybot.test.ts

Outputting build logs directly to issue runs the risk of exposing data leaked in build logs.
This removes the "test output" log functionality, but leaves the link and failure status.

security: do not output build logs in issue body

---

packages/repo-metadata-lint/src/validate.ts

Fixes https://github.com/googleapis/python-runtimeconfig/issues/175

fix(repo-metadata-lint): add runtimeconfig to the list of non-gRPC APIs

---

packages/release-please/src/config-schema.json

Adding "always-bump-minor" and "always-bump-major" to the allowed values for versioning.
Reference PR: https://github.com/googleapis/release-please/pull/1744

chore: Update config-schema.json to allow "always-bump-minor" and "always-bump-major" versioning strategies.

---

packages/release-trigger/requirements.in
packages/release-trigger/requirements.txt

* Add appengine-plugins to repo list ([#530](https://github.com/googleapis/releasetool/issues/530)) ([ae19e0e](https://github.com/googleapis/releasetool/commit/ae19e0e11d4d060599992b326af4a7ef21b7baf5))
* Update PHP tags ([#518](https://github.com/googleapis/releasetool/issues/518)) ([cdc159b](https://github.com/googleapis/releasetool/commit/cdc159ba86c22be9d6eba64a1b69f14200bcd4eb))

fix(deps): update releasetool to 1.17.0

---

packages/owl-bot/src/should-ignore-repo.ts
packages/owl-bot/test/should-ignore-repo.ts

owl-bot is opening some PRs against sharded, non-php repos. We should not be opening copy-code PRs against these repos.
example: https://github.com/googleapis/php-shopping-merchant-reports/pull/5
These repos `googleapis/php-<something>`, are non-cloud and split of the primary PHP monorepo `googleapis/google-cloud-php`.

fix(owl-bot): ignore non-cloud php repos

---

packages/flakybot/Dockerfile

fix: update base node image for flakybot to node:18-slim

---

.github/workflows/ci.yaml
packages/owl-bot/package-lock.json
packages/owl-bot/package.json

Fixes #5295 
deps: update `@octokit/endpoint` to v7
build: test owl-bot against node 18
ci: use `no-experimental-fetch` for nock/node18 compatibility

feat: require node 18 for owl-bot

---

packages/owl-bot/src/core.ts

The logs url is a `.txt` file. Also add a newline for formatting

fix: add correct file extension to gs log url

---

packages/trusted-contribution/.eslintrc.json
packages/trusted-contribution/README.md
packages/trusted-contribution/__snapshots__/comments.js
packages/trusted-contribution/package-lock.json
packages/trusted-contribution/package.json
packages/trusted-contribution/src/comments.ts
packages/trusted-contribution/src/config-schema.json
packages/trusted-contribution/src/config.ts
packages/trusted-contribution/src/trusted-contribution.ts
packages/trusted-contribution/test/comments.ts
packages/trusted-contribution/test/fixtures/comments.yml
packages/trusted-contribution/test/trusted-contribution.ts

Fixes #5307
Adds a new `commentInstructions` boolean configuration for the bot (opt-in feature). If set and the PR author is not "trusted", comment on the PR with reminder instructions for the maintainers on how to apply labels/comment in order to trigger CI (whatever the bot would do for a trusted contributor).

feat: add ability to comment on pull request

---

packages/auto-approve/src/process-checks/node/owlbot-template-changes.ts
packages/auto-approve/test/node-owlbot-template-changes.test.ts

Also, make logging a little less confusing. Instead of saying:
```
{"severity":"INFO","level":30,"message":"Check otherOwlBotPRs for testRepoOwner/testRepoName/1 for no particular file is false"} // which means there are no otherowlbotPRs, so the check passes
{"severity":"INFO","level":30,"message":"Check otherCommitAuthors for testRepoOwner/testRepoName/1 for no particular file is false"} // which means there are no otherowlbotPRs, so the check passes
```
say:
```{"severity":"INFO","level":30,"message":"Check otherOwlBotPRs for testRepoOwner/testRepoName/1 for no particular file is true"} 
{"severity":"INFO","level":30,"message":"Check otherCommitAuthors for testRepoOwner/testRepoName/1 for no particular file is true"}```

fix: make sure regex checking is at the start of the title, and that test catches it appropriately

---

packages/auto-approve/README.md
packages/auto-approve/__snapshots__/auto-approve.test.js
packages/auto-approve/__snapshots__/check-config.test.js
packages/auto-approve/src/check-pr-v2.ts
packages/auto-approve/src/process-checks/node/owlbot-template-changes.ts
packages/auto-approve/src/process-checks/node/owlbot.ts
packages/auto-approve/src/valid-pr-schema-v2.json
packages/auto-approve/test/node-owlbot.test.ts

See: https://docs.google.com/document/d/1PxkDU5nZihyxDJ9XvjwX7GvDDdJu8qm4TpoxMUsryz0/edit?tab=t.0#heading=h.689e00isjkgi
Adding owlbot process checks for Node:
```
Auto-approve would approve and tag owl-bot PRs if and only if:
The PR author is ‘gcf-owl-bot[bot]’
The title of the PR, and the commits in the PR, do not include breaking, BREAKING or !
The body of the PR contains a ‘PiperOrigin-RevId’
There are no other PRs in the repository opened by gcf-owl-bot[bot]
Checks that the PR does not have any commits from any other authors other than gcf-owl-bot[bot]
```

feat: add owlbot PRs process check for Node

---

packages/owl-bot/Dockerfile

This code is only tested against node-18, so only upgrading to node 18.
Addresses b/341670329

build: upgrade owlbot-cli base image to node:18-alpine

---

renovate.json5

Use renovate to update versioned Dockerfile base images.
Note: using `.json5` for a more readable config format

build: enable renovate

---

packages/auto-approve/README.md
packages/auto-approve/__snapshots__/check-config.test.js
packages/auto-approve/src/check-pr-v2.ts
packages/auto-approve/src/process-checks/ruby/apiary-codegen.ts
packages/auto-approve/src/valid-pr-schema-v2.json
packages/auto-approve/test/ruby-apiary-codegen.test.ts

This will be used for the Ruby and Elixir apiary client repos. Codegen in those repos is currently blocked due to the removal of `YOSHI_APPROVER_TOKEN`; we're migrating to auto-approve in response.
Implementation is closely based on the existing PHPApiaryCodegen.

feat(auto-approve): added a RubyApiaryCodegen process for the auto-approve bot

---

packages/bot-config-utils/package-lock.json
packages/bot-config-utils/package.json
packages/cron-utils/package-lock.json
packages/cron-utils/package.json
packages/issue-utils/package-lock.json
packages/issue-utils/package.json
packages/object-selector/package-lock.json
packages/object-selector/package.json

Updating gcf-utils and other google-cloud dependencies in other helper libraries.
datastore-lock helper still needs more work (datastore-emulator test dependency doesn't work)

fix(deps)!: update gcf-utils to v16

---

packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json

Without locking the version, downstream apps that use octokit/graphql that do not declare a version, will get an ESM version (8.0.0+). This is incompatible with what our libraries and probot can handle.

fix(deps): lock octokit/graphql to commonjs version

---

.github/workflows/ci.yaml
packages/do-not-merge/package-lock.json
packages/do-not-merge/package.json

Also updates to test against node 18 as it already runs on node 18

fix(deps): update gcf-utils to v16

---

.github/workflows/ci.yaml
packages/blunderbuss/package-lock.json
packages/blunderbuss/package.json

Also updates to test against node 18 as it already runs on node 18

fix(deps): update to gcf-utils v16

---

renovate.json5

Use `npm:unpublishSafe` to prevent updating to packages that can be unpublished/yanked.

build: re-enable npm package updates for renovate

---

.github/workflows/audit-bulk.yaml
.github/workflows/audit.yaml

Also makes the individual `npm audit fix` workflow manual trigger only

ci: add bulk npm audit workflow

---

packages/label-sync/src/labels.json

Adding a label to mark GenAI PRs for an additional reviewer, per go/code-ai-policy

feat(label-sinc): add label for PRs containing GenAI code

---

packages/gcf-utils/src/configuration.ts
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

Sometimes we don't want to throttle all tasks in case rate limits from one installation block other installations.

feat: add ability to configure app to skip throttling on rate limits

---

packages/auto-label/cloudbuild.yaml
packages/blunderbuss/cloudbuild.yaml
packages/do-not-merge/cloudbuild.yaml
packages/failurechecker/cloudbuild.yaml
packages/flakybot/cloudbuild.yaml
packages/generated-files-bot/cloudbuild.yaml
packages/header-checker-lint/cloudbuild.yaml
packages/label-sync/cloudbuild.yaml
packages/owl-bot/cloudbuild.yaml
packages/policy/cloudbuild.yaml
packages/repo-metadata-lint/cloudbuild.yaml
packages/sync-repo-settings/cloudbuild.yaml
packages/trusted-contribution/cloudbuild.yaml

All the bots are currently tested against node 18. Node 14 runtime is deprecated and scheduled for removal.
Currently a few deployments are failing because the bots cannot resolve dependencies on node 14.

build: deploy all cloud functions on node 18

---

packages/release-please/package-lock.json
packages/release-please/package.json

[16.14.1](https://github.com/googleapis/release-please/compare/v16.14.0...v16.14.1) (2024-10-01)
Bug Fixes
deps: replace jsonpath with jsonpath-plus (https://github.com/googleapis/release-please/issues/2391) ([47db9b5](https://github.com/googleapis/release-please/commit/47db9b5ce447fdc71a169c94e58480b525210679))
when parsing multiple messages from a single commit, require 2 newlines (https://github.com/googleapis/release-please/issues/2390) ([bb5e69b](https://github.com/googleapis/release-please/commit/bb5e69b958c9dd4818c30315ae99d3ecc7e41fa1))
[16.14.0](https://github.com/googleapis/release-please/compare/v16.13.0...v16.14.0) (2024-09-17)
Features
handle multiple commits in a single message (https://github.com/googleapis/release-please/issues/2358) …

deps: update release-please to 16.14.1

---

packages/trusted-contribution/package-lock.json

I ran `~/repo-automation-bots/packages/trusted-contribution$ npm audit fix`.
I see cookie is 0.7.1 already. This line didn't show up in the changed lines.
```
2654     "node_modules/cookie": {
2655       "version": "0.7.1",
2656       "resolved": "https://registry.npmjs.org/cookie/-/cookie-0.7.1.tgz",
2657       "integrity": "sha512-6DnInpx7SJ2AK3+CTUE/ZM0vWTUboZCegxhC2xiIydHR9jNuTAASBrfEpHhiGOZw/nX51bHt6YQl8jsGo4y/0w==",
2658       "engines": {
2659         "node": ">= 0.6"
2660       }
2661     },
```
The old cookie module dependency is now gone.

deps(trusted-contribution): trying to upgrade cookie to 0.7.1

---

packages/owl-bot/package-lock.json

Upgrading the dependencies to use the latest gcf-utils. I ran `npm update gcf-utils` in the owl-bot directory.

deps: upgrading owlbot dependencies

---

packages/owlbot-bootstrapper/app/package-lock.json
packages/owlbot-bootstrapper/common-container/package-lock.json

cont. of https://github.com/googleapis/repo-automation-bots/pull/5546
I confirmed the old cookie library doesn't appear in the package-lock.json.

deps: upgrading remaining owlbot-bootstreapper deps

---

packages/bazel-bot/cloudbuild.yaml

https://cloud.google.com/build/docs/optimize-builds/increase-vcpu-for-builds#increase_vcpu_for_default_pools
https://cloud.google.com/build/pricing
The E-series is the current supported machine type.
The reason why you see all line changed is that I converted the Windows-style new line characters to UNIX-style.

fix: bazelbot insufficient memory error

---

packages/release-trigger/requirements.in
packages/release-trigger/requirements.txt

For node/python repositories, we now default to a multiScmName equal to the repository name

deps: update releasetool to 2.3.0

---

scripts/publish-cloud-run.sh
scripts/publish-function.sh

service configuration including task queues are being managed by terraform instead
In a follow-up, we should be able to directly run the gcloud deploy commands to simplify the release process

build: simplify deploy scripts

---

packages/canary-bot/cloudbuild.yaml

Fixes `invalid build: invalid .steps field: build step #5 - "push-docker": the ID is not unique`

build: rename second docker push step

---

packages/canary-bot/cloudbuild.yaml
packages/cherry-pick-bot/cloudbuild.yaml

Both cloudbuild.yaml files had duplicated step ids.
canary-bot had the same step twice (from a merge conflict)
cherry-pick-bot needed to differentiate between the frontend and backend deployment

build: fix deployment for canary-bot and cherry-pick-bot

---

packages/canary-bot/Dockerfile

Resolves CVE-2024-21538 for canary-bot.
For other bots: #5575.

chore(canary-bot): remove unnecessary cross-spawn from npm

---

packages/canary-bot/package-lock.json
packages/canary-bot/package.json
packages/canary-bot/src/canary-bot.ts
packages/canary-bot/test/test.ts

This will allow us to test permissions for datastore on the canary-bot backend.

feat: use datastore-lock in issue handler

---

packages/gcf-utils/Dockerfile
packages/gcf-utils/cloudbuild-test.yaml
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

Handle better env var names (GCF_SHORT_FUNCTION_NAME -> BOT_NAME and GCF_LOCATION -> BOT_LOCATION)
fix: ensure that Cloud Function URL uses underscored name of bot
test: fix test at runtime, not docker build time
test: set test env variables at runtime not build time

feat: handle BOT_NAME and BOT_LOCATION configuration via env

---

packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/gcf-bootstrapper.ts

For Cloud Run based bots, we no longer need to specify the taskTargetName. This also allows re-using the same frontend image for both a GCF backend and Cloud Run backend by configuring via environment variables (setting BOT_RUNTIME env var).

fix: set default taskTargetName based on runtime environment

---

packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

Disable running OwlBot on fork PRs even if the `owlbot:run` label is added.
`yoshi-code-bot` is the only exception.
b/379713607
**Potential future enhancements**:
- Add a comment to the PR that OwlBot did not execute
- Do not remove the `owlbot:run` label
- Consider removing `yoshi-code-bot` from allowlist

feat(owlbot): skip running owlbot on PRs from forks

---

packages/cherry-pick-bot/package-lock.json
packages/cherry-pick-bot/package.json
packages/cherry-pick-bot/src/server.ts

Currently, the `cherry-pick-bot` is queuing backend requests to target the frontend Cloud Run service (`cherry-pick-bot`) rather than the backend (`cherry-pick-bot-backend`). This updates `gcf-utils` to correctly default to target the Cloud Run backend service which has the appropriate permissions.
Prior to gcf-utils 16.2.0, the default Cloud Run backend was the name of the bot (which is actually the frontend)

build: update gcf-utils to 16.2.1 and use environment defaults

---

packages/owl-bot/package-lock.json
packages/owl-bot/package.json
packages/owl-bot/src/server-backend.ts
packages/owl-bot/src/server-frontend.ts
packages/release-please/package-lock.json
packages/release-please/package.json
packages/release-please/src/server.ts
packages/release-trigger/package-lock.json
packages/release-trigger/package.json
packages/release-trigger/src/server-frontend.ts
packages/release-trigger/src/server.ts
packages/snippet-bot/package-lock.json
packages/snippet-bot/package.json

For the remaining Cloud Run based bots, update gcf-utils to 16.2.1 which allows for configuring the background task runner via env variables.

deps: update gcf-utils to 16.2.1

---

serverless-scheduler-proxy/main.go

This will allow us to run only the Cloud Run versions of the owl-bot backends

fix: send pubsub messages to Cloud Run version of owl-bot

---

packages/release-trigger/src/release-trigger.ts

Adding the Dataproc organization to the release-trigger allowlist.

feat(release-trigger): Add GoogleCloudDataproc to allowlist

---

packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
packages/conventional-commit-lint/src/utils.ts
packages/conventional-commit-lint/test/conventional-commit-lint.ts

Rather than commenting on the PR, we will add a separate, second failing check if the PR body does not match the single commit message.
This will allow us to remove the permission needed to write to PRs for the bot.

feat(conventional-commit-lint): add second check for mismatched PR title

---

packages/snippet-bot/src/snippet-bot.ts

We restricted snippet-bot to only run on GCP client library repos, but google maps also uses it internally, so adding to allowlist.
Fixes #5626 🦕

fix: allowlist google map repos for snippet bot

---

packages/release-please/package-lock.json
packages/release-please/package.json

Hi,
Noticed that the github app is lagging behind on release-please, which makes the newest configuration `always-update` unavailable. This should fix that.
Fixes #5628  🦕

feat(deps): upgrade release-please to 16.15.0 adding new config attribute

---

packages/cherry-pick-bot/cloudbuild-test.yaml
packages/cherry-pick-bot/cloudbuild.yaml
packages/flakybot/cloudbuild.yaml
packages/release-please/cloudbuild.yaml
packages/release-trigger/cloudbuild-test.yaml
packages/release-trigger/cloudbuild.yaml
packages/snippet-bot/cloudbuild-test.yaml
packages/snippet-bot/cloudbuild.yaml

Configure the remaining bots to use logs buckets for dedicated service accounts

build: configure logs bucket for custom service accounts

---

packages/owl-bot/cloudbuild-test.yaml
packages/owl-bot/src/core.ts
packages/owl-bot/src/owl-bot.ts
packages/owl-bot/test/owl-bot.ts

- **fix: OwlBot postprocessor to report a check when skipping a PR**
b/385183332. After https://github.com/googleapis/repo-automation-bots/pull/5587 and before this change, the post processor checks were silently skipped and those repositories that mark it as required cannot merge pull requests from external contributors.
---

fix(owl-bot): OwlBot to report a skip in pull request checks

---

packages/owl-bot/cloudbuild.yaml

The deployment failed due to logging configuration (b/385183332#comment10).
This is the same lines that I added in cloudbuild-test.yaml: https://github.com/googleapis/repo-automation-bots/pull/5643/files#diff-ae6d90a3673680601c94bddc10655dd45aecb86e240c4c9d2702b46f6c5eb7d9R27
This file matches what is in the trigger configuration.

fix(owl-bot): cloud build bucket configuration

---

packages/release-please/package-lock.json
packages/release-please/package.json

I removed `packages/release-please/package-lock.json` and ran "npm install" there. Now it got 10.2.0. Good.
```
suztomo@suztomo2:~/repo-automation-bots$ find . -name 'package-lock.json' |xargs grep jsonpath-plus
./packages/release-please/package-lock.json:    "node_modules/jsonpath-plus": {
./packages/release-please/package-lock.json:      "resolved": "https://registry.npmjs.org/jsonpath-plus/-/jsonpath-plus-10.2.0.tgz",
```
Then I observed error " Type 'Int32Array' is not generic." (see below). I upgraded the typescript version as per https://github.com/firebase/firebase-functions/issues/1664.

deps: release-please dependency upgrade

---

packages/conventional-commit-lint/package-lock.json

Fixes https://github.com/googleapis/repo-automation-bots/security/dependabot/1822

fix: upgrade dependencies in packages/conventional-commit-lint

---

packages/release-please/package-lock.json

Fixes security vulnerability https://github.com/googleapis/repo-automation-bots/security/dependabot/2037 🦕

deps: update release-please jsonpath-plus to 10.3.0

---

packages/gcf-utils/Dockerfile
packages/gcf-utils/package-lock.json
packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/server.ts

This is to fix ReDoS vulnerability found in octokit dependencies.  This was logic in choosing version:
Latest Probot version (13.4.3) is using @octokit/core 5.0.2 and octokit/Plugin-paginate-rest: 9.2.2, which was a limiting factor in upgrades:
@octokit/request:  upgrade to 8.4.1 for vulnerability fix + compatibility with  octokit/core v5
@octokit/request-error: 5.1.1 for vulnerability fix
@octokit/plugin-paginate-rest: 9.2.2 for vulnerability fix 
Could not upgrade @octokit/rest > 19 because of incompatibility with @octokit/plugin-paginate-rest > v9 , so need to manually set version of @octokit/core dependency in package-lock.json to 5.0.2
Additional changes had to be made:
Webhook verify throws error if payload is not include, so added logic to catch and propigate as a 500.
Tested via …

deps: update gcf-utils oktokit dependencies to fix ReDoS vulnerability

---

packages/gcf-utils/package.json
packages/gcf-utils/src/gcf-utils.ts
packages/gcf-utils/test/server.ts

Based on change to [verify defintion in webhooks](https://github.com/octokit/webhooks-methods.js/releases/tag/v2.0.0) we need to pass in a string for the event payload.  Cleaning this up removes the need to catch the error

fix: need to pass in string to webhooks.verify

---

packages/release-trigger/requirements.in
packages/release-trigger/requirements.txt

Fix for .NET release trigger migration

deps: update releasetool to 2.6.0

---

packages/release-please/src/release-please.ts

Some repos like google-cloud-go use multiple configurations against the same branch. The datastore locks should be separate per configuration run (branch/config file combination).

fix(release-please): distributed lock key should use config name

---

packages/owlbot-bootstrapper/common-container/package-lock.json
packages/owlbot-bootstrapper/common-container/package.json

Fixes #[2096](https://github.com/googleapis/repo-automation-bots/security/dependabot/2096)

chore(owlbot-bootstrapper): update gcf-util to latest to remove octokit vulnerability

---

packages/release-trigger/README.md

By default, the release-trigger is disabled, if the `release-trigger.yml` doesn't exist.

docs: clarify that release-trigger.yml must exist to enable

---

.github/release-please.yml

This repository creates multiple Git tags upon one release pull request (commit). Example: https://github.com/googleapis/repo-automation-bots/pull/5696
To adopt the new release pipeline based on Git tags, this `tagPullRequestNumber` creates an additional `release-please-<pr number>` tag to a release. We'll monitor that tag to trigger the release job. This doesn't change existing release tags.
Background: https://docs.google.com/document/d/1Y0Fv-sxLqYmjnXHry3WDq4XNPeQP1AEmsB83hNRCEY0/edit?usp=sharing&resourcekey=0-I2m8Z-mTD0-HY0TpkblOTQ
This design has been working good for google-cloud-go: https://github.com/googleapis/google-cloud-go/blob/main/.github/release-please.yml#L4

ci: release-please.yml to tag pull request number

---

packages/owl-bot/Dockerfile.frontend

The node:18-alpine is the lightweight container image that has the same version of the Node in the build steps.
b/418620308
The OwlBot frontend doesn't need special tools such as git. go/cloud-sdk-bot-architecture explains the architecture of the frontend and backend.

chore(owl-bot): use the alpine variant for the runtime image in OwlBot frontend

---

packages/datastore-lock/package-lock.json
packages/datastore-lock/package.json

Note google-datastore-emulator hasn't been updated in over a year, so choosing to manually override tar-fs
Fixes #[2140](https://github.com/googleapis/repo-automation-bots/security/dependabot/2140)🦕

chore: update tar-fs to fix security vuln

---

packages/trusted-contribution/src/trusted-contribution.ts
packages/trusted-contribution/test/trusted-contribution.ts

Added 6s sleep before adding the gcbrun due to race condition with other bots.
More information in b/422754703.
- [ x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/repo-automation-bots/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ x] Ensure the tests and linter pass
- [ x] Code coverage does not decrease (if any source code was changed)
- [ x] Appropriate docs were updated (if necessary)
Fixes b/422754703 🦕

feat: add 6s sleep in trusted contribution bot before adding gcbrun

---

packages/bazel-bot/docker-image/generate-googleapis-gen.sh

`bazelisk` uses a consistent version of `bazel` defined by the `.bazeliskrc` file in a bazel workspace. Every other instance of trying to run `bazel` correctly uses `bazelisk`
Should fix b/422179873

fix: use bazelisk instead of bazel CLI

---

packages/header-checker-lint/Dockerfile
packages/header-checker-lint/cloudbuild-test.yaml
packages/label-sync/Dockerfile
packages/label-sync/cloudbuild-test.yaml
packages/merge-on-green/Dockerfile
packages/merge-on-green/cloudbuild-test.yaml
packages/repo-metadata-lint/Dockerfile
packages/repo-metadata-lint/cloudbuild-test.yaml
packages/sync-repo-settings/Dockerfile
packages/sync-repo-settings/cloudbuild-test.yaml

* Use marketplace.gcr.io/google/debian12:latest instead of node:18.20.5-slim.
* Add presubmit tests
The follow packages are affected:
* header-checker-lint
* label-sync
* merge-on-green
* repo-metadata-lint
* sync-repo-settings

build: use marketplace.gcr.io/google/debian12:latest

---

packages/mono-repo-publish/README.md

Towards https://github.com/googleapis/librarian/issues/369

chore: mark mono-repo-publish library as deprecated

---

packages/release-trigger/README.md

Fixes https://github.com/googleapis/librarian/issues/376

chore: mark release-trigger as deprecated

---

packages/repo-metadata-lint/README.md

Fixes https://github.com/googleapis/librarian/issues/377

chore: mark repo-metadata-lint as deprecated

---

packages/auto-label/README.md

Fixes https://github.com/googleapis/librarian/issues/346

chore: mark auto-label as deprecated

---

packages/owl-bot/src/handlers.ts
packages/owl-bot/test/handlers.ts

Renaming this file here: https://github.com/googleapis/google-cloud-node/pull/6604/files
see: https://github.com/googleapis/repo-automation-bots/issues/4980

chore: update handlers.ts
