googleapis/repo-automation-bots

- packages/gcf-utils/src/bin/README.md
Added a README with instructions on using genkey in your own projects.
> chore(genkey): added README.md

- .bots/header-checker-lint.json
- packages/header-checker-lint/__snapshots__/header-checker-lint.js
- packages/header-checker-lint/src/header-checker-lint.ts
- packages/header-checker-lint/test/fixtures/config_ignored_files.json
- packages/header-checker-lint/test/header-checker-lint.ts
> feat: ignore configured ignoreFiles globs

- packages/header-checker-lint/src/header-checker-lint.ts
allow `// Copyright`, allow `Google LLC.`, this addresses a bunch of alerts I've seen.
> fix: loosen copyright regex

- packages/release-please/README.md
- packages/release-please/package.json
This unblocks Java releases for multiple versions in the same repo.
> fix: update release-please to 2.9.0

- cloudbuild.yaml
This is blocking function deployment
> build: temporarily skip cron-deploy

- cloudbuild.yaml
- scripts/Makefile
- scripts/README.md
- scripts/build-functions.sh
- scripts/cron-deploy.sh
- scripts/publish-functions.sh
- scripts/serverless-scheduler-proxy-deploy.sh
- scripts/test.sh
Makes build scripts more testable with `shellcheck`
> feat(build): split build steps into scripts/

- packages/trusted-contribution/src/trusted-contribution.ts
- packages/trusted-contribution/test/fixtures/pull_request_edited.json
- packages/trusted-contribution/test/trusted-contribution.ts
Acting on feedback left on PR #114
> fix(trusted contribution): limit bot to trigger on creation and edit

- packages/trusted-contribution/src/trusted-contribution.ts
- packages/trusted-contribution/test/fixtures/pull_request_edited.json
- packages/trusted-contribution/test/fixtures/pull_request_opened.json
We're currently allowing the wrong usernames
> fix(trusted contribution): correct bot usernames

- packages/trusted-contribution/src/trusted-contribution.ts
release-please PRs get closed and reopened when they're being groomed, let's also kick off a test run when this happens.
> feat: also run tests when PR is reopened

- packages/gcf-utils/package.json
- packages/label-sync/package.json
- packages/release-please/package-lock.json
- packages/release-please/package.json
Updates to latest version of release please, with support for additional version file in Java repo.
I've also fixed coverage, c8 should only be called at the top level.
> chore: update to latest version of release-please

- packages/blunderbuss/README.md
- packages/release-please/README.md
This fixes a few typos in READMEs.
> docs: fix typos

- serverless-scheduler-proxy/README.md
- serverless-scheduler-proxy/main.go
This just pulls back in @orthros's stale branch for pubsub.
> feat: add an endpoint for proxying pubsub messages

- packages/release-please/src/release-please.ts
- packages/release-please/test/fixtures/pull_request_labeled.json
- packages/release-please/test/fixtures/pull_request_labeled_other.json
> fix: pull request labels are objects

- packages/trusted-contribution/src/trusted-contribution.ts
- packages/trusted-contribution/test/fixtures/pull_request_synchronized.json
fixes: https://github.com/googleapis/repo-automation-bots/issues/198
> fix: logs indicate action is synchronize not synchronized

- packages/generate-bot/__snapshots__/generate-bot.js
- packages/generate-bot/main.js
- packages/generate-bot/run.js
- packages/generate-bot/templates/src/app.ts
- packages/generate-bot/templates/src/index.d.ts
- packages/generate-bot/templates/src/{{programName}}.ts
- packages/generate-bot/templates/test/{{programName}}.ts
- packages/generate-bot/test/generate-bot.js
Fixes:
Feature request #177 by allowing user to input hyphens and changing to underscores
Issue #202: updated license headers
Issue #199 by updating dependency and modifying test so that it does not get angry over updated dependencies
Also adds the chai library and an example of using it to the test of the actual bot in order to show its functionality
> fix: modified snapshots, added tests, fixed tests

- packages/label-sync/package-lock.json
- packages/label-sync/package.json
- packages/label-sync/src/label-sync.ts
- packages/label-sync/test/mocha.opts
- packages/label-sync/test/test.ts
~This is blocked on figuring out auth to the provided endpoint~
EDIT: this should be good to go now -- @bcoe.
> feat(label-sync): add api labels from drift

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
update to version of release-please with support for Terraform.
> feat: update to release-please with terraform support

- .github/workflows/ci.yml
let's see if `pull_request` is closer to what we were looking for, and if so make these the required checks.
> build: push does not seem to fire on renovate PRs

- scripts/build-functions.sh
- scripts/cron-deploy.sh
- scripts/publish-functions.sh
we are deploying a testing version of mog while we get ready to code review the final product; skip deploying for the time being.
> build: don't deploy mog until we're ready to code review new version

- packages/buildcop/__snapshots__/buildcop.js
- packages/buildcop/src/buildcop.ts
- packages/buildcop/test/buildcop.ts
- packages/label-sync/src/labels.json
> chore(Build Cop): update issue label and label-sync

- cloudbuild.yaml
we are hitting our 20m timeout.
> fix: our cloudbuild job was hitting timeout

- packages/buildcop/__snapshots__/buildcop.js
- packages/buildcop/src/buildcop.ts
> fix(Build Cop): fix grimacing emoji

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/src/merge-on-green.ts
added some timing logs so that we can dig into things a bit deeper.
> chore: add timing logs

- packages/merge-on-green/src/merge-on-green.ts
when we added logic to trigger GoogleCloudPlatform, with its installation ID, and googleapis instead with its installation ID, we created a condition where the wrong bot might delete the ticket in the database.
> fix: deleting might happen in the wrong cron job

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/test/merge-on-green.ts
Added logic to see if the PR has been merged before trying to merge
> fix: add logic to check if PR has been merged

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/src/merge-on-green.ts
some small tweaks to logging to make debugging easier.
> chore: slight logging improvements

- packages/gcf-utils/.gitignore
- packages/gcf-utils/package.json
- packages/gcf-utils/src/bin/genkey.ts
- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/integration/gcf-utils-integration.ts
This fixes the build errors we're seeing in other PRs (weird), and does a little house keeping.
> chore: perform cleanup of gcf-utils

- packages/buildcop/__snapshots__/buildcop.js
- packages/buildcop/src/buildcop.ts
- packages/buildcop/test/buildcop.ts
I confirmed the test case fails without the additional sorting.
Fixes #316 🦕
> fix(Build Cop): reopen the original when there is a duplicate

- packages/buildcop/README.md
> docs(Build Cop): clarify how repo is detected

- scripts/build-functions.sh
- scripts/cron-deploy.sh
- scripts/publish-functions.sh
> fix: make sure sync-repo-settings is not included in deploy

- packages/label-sync/src/labels.json
I'm looking for suggestions for the description, and if we need to update anything else. PTAL :)
> chore: add p3 label

- packages/merge-on-green/src/merge-logic.ts
> fix: add logging

- packages/buildcop/__snapshots__/buildcop.js
- packages/buildcop/src/buildcop.ts
- packages/buildcop/test/buildcop.ts
- packages/label-sync/src/labels.json
The label does not get automatically applied. Perhaps it should?
Fixes #282.
> feat(Build Cop): add support for quiet label

- README.md
merge on green was missing from list of bots.
> chore: add merge on green to list of bots

- scripts/build-functions.sh
- scripts/cron-deploy.sh
- scripts/publish-functions.sh
Cloud Build is breaking due to errant semicolons
> fix(sync-repo-settings): errant semicolons

- packages/buildcop/buildcop.go
- packages/buildcop/buildcop_test.go
- packages/buildcop/go.sum
Corresponding google-cloud-go change: https://code-review.googlesource.com/c/gocloud/+/53490
Fixes #395 🦕
> fix(Build Cop): remove special google-cloud-go repo detection

- packages/buildcop/buildcop.go
- packages/buildcop/buildcop_test.go
- packages/buildcop/src/buildcop.ts
> chore(Build Cop): remove build ID references

- packages/buildcop/README.md
- packages/buildcop/buildcop.go
Helpful for running locally or if Trampoline is not available.
> feat(Build Cop): add service_account flag

- packages/buildcop/__snapshots__/buildcop.js
- packages/buildcop/src/buildcop.ts
- packages/buildcop/test/buildcop.ts
- packages/buildcop/test/fixtures/testdata/go_failure_group.xml
Updates #258.
This does not close or link previously opened issues with the new "super issue." I left a TODO because we might want to do that in the future.
> feat(Build Cop): group Go subtests into one issue

- packages/sync-repo-settings/src/required-checks.json
these repos currently have fairly custom configurations.
> chore: ignore additionaol GoogleCloudPlatform repos

- packages/publish/src/publish.ts
this is on a hunch, let's see if moving away from blocking the process during publication helps prevent memory issues.
> fix: see whether moving to async model has better performance

- packages/release-please/src/release-please.ts
- packages/release-please/src/runner.ts
- packages/release-please/test/release-please.ts
> fix(release-please): await ReleasePR.run() and GitHubRelease.createRelease()

- packages/auto-label/package.json
- packages/blunderbuss/package.json
- packages/buildcop/package.json
- packages/conventional-commit-lint/package.json
- packages/failurechecker/package.json
- packages/gcf-utils/package.json
- packages/header-checker-lint/package.json
- packages/label-sync/package.json
- packages/merge-on-green/package.json
- packages/publish/package.json
- packages/release-please/package.json
- packages/sync-repo-settings/package.json
- packages/trusted-contribution/package.json
this will hopefully get our deploys running again.
> fix: drop prepare, which is broken with "npm ci"

- scripts/serverless-scheduler-proxy-deploy.sh
> fix: scheduler deploy script was missing quote

- packages/buildcop/__snapshots__/buildcop.js
- packages/buildcop/src/buildcop.ts
- packages/buildcop/test/buildcop.ts
> fix(Build Cop): keep existing priority and type labels

- package.json
- synth.py
Fixes #499.  Reverting #497 that does not really apply to this repository.
> fix: revert scripts and synth.py change

- packages/publish/src/publish.ts
When two publication tasks were retrying at the same time in the task queue, we observed a loop that lead to 108 pre-releases being published.
I've done two things in this PR:
1. if publish has succeeded, we no longer allow a failure on the steps which remove the label (my hunch being a 404 on label remove might have been the issue (I was however unable to find this in the logs).
2. I've capped us at three pre-releases for the time being, so that we don't end up in the same loop.
> fix: patch to protect against the publish loop bug we saw

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/test/merge-on-green.ts
Reverts googleapis/repo-automation-bots#482
> Revert "fix(merge-on-green): bug that won't let subtests pass by adding in regex"

- packages/sync-repo-settings/.gitignore
- packages/sync-repo-settings/src/index.d.ts
- packages/sync-repo-settings/src/required-checks.json
- packages/sync-repo-settings/test/fixtures/repos.json
- packages/sync-repo-settings/test/test.ts
@chingor13 mind double checking me here?
> fix: manage google-auth-library-java, google-(api|http|oauth)-java-client settings

- packages/failurechecker/package.json
~I'm not sure how this ever would have worked?~ moment had its own types, they seem to have been broken with the last publication.
> fix(deps): the most recent release of moment seems to have broken types

- packages/buildcop/__snapshots__/buildcop.js
- packages/buildcop/src/buildcop.ts
- packages/buildcop/test/buildcop.ts
Please check the updated snapshots. Can we make the messages better?
Fixes #500
> feat(Build Cop): add more detail when marking an issue flaky

- packages/sync-repo-settings/src/required-checks.json
> fix(sync-repo-settings): update checks for google-api-java-client-services

- packages/buildcop/src/buildcop.ts
- packages/buildcop/test/buildcop.ts
- packages/buildcop/test/fixtures/testdata/go_skip.xml
> fix(Build Cop): ignore skipped tests

- packages/sync-repo-settings/src/required-checks.json
> fix(sync-repo-settings): fix google-cloud-java checks

- packages/buildcop/src/buildcop.ts
> chore(Build Cop): add more logging

- packages/buildcop/src/buildcop.ts
> fix(Build Cop): await async function calls

- packages/release-please/package.json
- packages/release-please/src/release-please.ts
This updates to the latest version of `release-please` which has a simple `version.txt` based releaser.
> feat(deps): newest release please with simple version.txt releaser

- packages/sync-repo-settings/src/required-checks.json
> fix(sync-repo-settings): Java Pub/Sub Lite is Java 8+

- packages/sync-repo-settings/src/required-checks.json
> fix(sync-repo-settings): manage gax-java required checks

- packages/blunderbuss/README.md
I also updated the example usernames a bit.
> docs(Blunderbuss): update README config location

- packages/release-please/package.json
I believe this broke our last deploy.
> fix(deps): release-please expects 18.x.x of octokit

- packages/sync-repo-settings/src/required-checks.json
To align with changes made in: https://github.com/googleapis/synthtool/pull/639
> build(java): update required status checks for dependencies

- packages/sync-repo-settings/src/required-checks.json
Reverts googleapis/repo-automation-bots#616
> revert: "build(java): update required status checks for dependencies"

- packages/merge-on-green/src/merge-logic.ts
> chore: test new label system

- packages/merge-on-green/README.md
- packages/merge-on-green/src/merge-logic.ts
> chore(merge-on-green): add to mog read me

- packages/buildcop/README.md
- packages/buildcop/buildcop.go
- packages/buildcop/buildcop_test.go
Fixes #642.
cc @dinagraves (can't add as a reviewer)
> feat(buildcop): add build_url flag

- packages/label-sync/src/label-sync.ts
- packages/label-sync/test/test.ts
In the logs for labelSync, we're getting errors like this:
It looks like we're possibly getting some sketch data back from GCS, and we need this to debug what's happening.
> fix(label-sync): handle drift data with no short name

- packages/gcf-utils/package.json
It's silly that we need to do this ... if anyone feels like taking the time to write a mono repo releaser for release please, I would happily help you through the process.
> feat: release gcf-utils with logging

- scripts/build-functions.sh
- scripts/cron-deploy.sh
- scripts/migrate-secrets.sh
- scripts/publish-functions.sh
> fix: exclude monitoring-system from builds

- packages/sync-repo-settings/src/required-checks.json
Should address #721 
fixes #721
> fix(sync-repo-settings): ignore googleapis/aip

- packages/merge-on-green/src/merge-on-green.ts
Fix minor logging issue with MOG
Fixes https://github.com/googleapis/repo-automation-bots/issues/744
> fix(merge-on-green): stringify object before logging

- packages/sync-repo-settings/README.md
Also add example of setting `requiresStrictStatusChecks` (require up-to-date branches)
> docs(sync-repo-settings): fix example config yaml comments

- scripts/publish-functions.sh
> fix(slo-stat-bot): Added slo-bot to deploy

- packages/trusted-contribution/src/trusted-contribution.ts
This bot should ask for the ability to read code, but it doesn't.  As a result, any time it checks for config on a private repository, it leads to a process crash due to a lack of permissions.  This wraps the config call in a try catch, logs the error, and allows execution to continue.  We need to update the bots requested scopes to ask for code access, but even after that's added existing repositories would need to re-authorize the app.
> fix(trusted-contribution): fail gracefully if config read fails

- packages/sync-repo-settings/src/required-checks.json
> chore: add repo override for python-crc32c

- packages/slo-stat-bot/src/slo-bot.ts
> fix(slo-stat-bot): Does not lowercase label names from scheduled event

- packages/monitoring-system/data-processor/config/config.yml
- packages/monitoring-system/data-processor/package.json
- packages/monitoring-system/data-processor/src/config-util.ts
- packages/monitoring-system/data-processor/src/data-processor-factory.ts
- packages/monitoring-system/data-processor/src/data-processors/cloud-functions-data-processor.ts
- packages/monitoring-system/data-processor/src/task-service.ts
- packages/monitoring-system/data-processor/test/unit/data-processor-factory.spec.ts
- packages/monitoring-system/data-processor/test/unit/data-processors/cloud-functions-data-processor.spec.ts
- packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-cloud-functions-client.ts
* Adds the implementation of the Cloud Functions data processor with tests
* Fixes some naming inconsistencies
> feat(data-processor): add a Cloud Functions data processor

- packages/release-please/package.json
- packages/release-please/src/release-please.ts
Related: googleapis/release-please#514
Related: googleapis/google-cloud-go#2716
> feat(release-please): support Go

- packages/slo-stat-bot/data/schema.json
> docs: update schema of slo rules

- .github/header-checker-lint.yml
> chore(header-checker-lint): ignore snapshot files

- packages/snippet-bot/package.json
Just in case, upgrading to the newest.
> chore(snippet-bot): update to the gcf-utils 5.5.1

- .github/workflows/ci.yaml
Add `monitoring-system/data-processor` to the GitHub CI pipeline and run tests/lint on every pull request
> process(github): add data processor to ci checks

- packages/release-please/src/release-please.ts
This should give us the nicer structured logging for release-please
> chore(release-please): switch to gcf-utils logger

- packages/release-please/.c8rc.json
- packages/release-please/.gitignore
- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
- packages/release-please/test/release-please.ts
> fix(release-please): clean up dependencies

- packages/auto-label/src/auto-label.ts
- packages/auto-label/test/auto-label.ts
Slowly deleting code, working my way towards debugging a few curiosities.
> refactor(auto-label): further simplify auto-label

- .github/header-checker-lint.yml
> chore(header-checker-lint): fixed the config file

- packages/snippet-bot/__snapshots__/snippet-bot.js
- packages/snippet-bot/src/region-tag-parser.ts
- packages/snippet-bot/src/snippet-bot.ts
- packages/snippet-bot/test/fixtures/blob_no_region_tags.json
- packages/snippet-bot/test/snippet-bot.ts
With this change, the bot will submit the check on PRs only when it
finds any region tags in the PRs.
Fixes #880 🦕
> chore(snippet-bot): only submit the check when region tags are detected

- packages/generate-bot/templates/package.json
update gcf-utils and engine version
> chore: update generate-bot template

- .github/workflows/ci.yaml
- packages/auto-label/README.md
- packages/label-sync/README.md
- packages/label-sync/src/label-sync.ts
- packages/label-sync/test/test.ts
> chore: add label-sync cron job, clean up some readme's

- packages/release-please/package-lock.json
- packages/release-please/package.json
New major version of release-please with code-suggester integrated.
> feat(release-please): release-please with code-suggester

- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
- packages/sync-repo-settings/src/schema.json
- packages/sync-repo-settings/src/sync-repo-settings.ts
- packages/sync-repo-settings/test/fixtures/bogusConfig.yaml
- packages/sync-repo-settings/test/fixtures/invalidYamlConfig.yaml
- packages/sync-repo-settings/test/test.ts
- packages/sync-repo-settings/tsconfig.json
This adds a PR status check for changes specifically to the config for this bot.
> feat(sync-repo-settings): add config validation

- packages/merge-on-green/package-lock.json
- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/src/merge-on-green.ts
- packages/merge-on-green/test/merge-on-green.ts
This is doing just a little cleanup with the way we export functions.
> chore: clean up merge-on-green

- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/src/required-checks.json
- packages/sync-repo-settings/test/test.ts
Remove repository overrides which are now configured in-repo
> chore(java): remove unnecessary settings overrides

- packages/sync-repo-settings/src/required-checks.json
In anticipation of the CODEOWNERS rollout being complete :) Please wait for @busunkim96 to give the go-ahead before merging this one.
> feat: require codeowner approval for python

- packages/sync-repo-settings/src/required-checks.json
> fix(sync-repo-settings): require codeowners reviews for java, remove java repo exceptions

- packages/release-please/package-lock.json
- packages/release-please/package.json
This should start storing payloads in storage for tasks.
> chore(deps): upgrade to latest and greatest gcf-utils

- packages/auto-label/package-lock.json
GitHub is flagging a couple security issues for deps.
> chore(deps): update deps due to security warning

- packages/auto-label/src/auto-label.ts
- packages/auto-label/test/auto-label.ts
Fixes #1021 
Added test to make sure default configs are used when there's no custom user config
> Fix: issue 1021 where auto-label bot needs to catch "config not found" on installation

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/src/merge-on-green.ts
> fix: minor clean ups relating to #1023

- packages/generated-files-bot/src/app.ts
This should fix the GCF deployment.
> fix(generated-files-bot): fix app.ts export name

- packages/snippet-bot/__snapshots__/snippet-bot.js
- packages/snippet-bot/src/snippet-bot.ts
- packages/snippet-bot/test/snippet-bot.ts
> fix(snippet-bot): ignore 404 errors upon label deletion

- packages/snippet-bot/src/region-tag-parser.ts
- packages/snippet-bot/src/snippet-bot.ts
> feat(snippet-bot): track start tags in the files

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
we weren't passing through an important flag for go.
> fix(release-please): pass relaseType config

- packages/snippet-bot/src/region-tag-parser.ts
- packages/snippet-bot/src/snippet-bot.ts
> fix(snippet-bot): avoid 404 errors

- .github/workflows/ci.yaml
> testing(go tests): use actions/setup-go@v2

- packages/snippet-bot/src/region-tag-parser.ts
- packages/snippet-bot/src/snippet-bot.ts
- packages/snippet-bot/test/region-tag-parser.ts
> cleanup(snippet-bot): reduce memory footprint for large diffs

- packages/auto-label/src/auto-label.ts
For example, see https://github.com/googleapis/google-cloud-go/issues/3296.
> feat(auto-label): label spannertest issues as spanner

- packages/trusted-contribution/src/trusted-contribution.ts
We should kick off tests for the yoshi-code-bot.
> feat(trusted-contribution): trust the yoshi-code-bot

- packages/do-not-merge/src/app.ts
The Cloud Function looks for a do_not_merge entrypoint.
> fix(dnm): export with underscores

- packages/release-please/package-lock.json
- packages/release-please/package.json
we were closing too many PRs on the go repo, leading to additional work.
> fix(release-please): do not close submodule PRs

- packages/publish/package-lock.json
- packages/publish/package.json
- packages/publish/src/app.ts
- packages/publish/src/index.d.ts
- packages/publish/src/publish.ts
- packages/publish/test/publish.ts
> build(publish): update lockfiles and typescript version

- README.md
> docs: add link to generated-files-bot pages

- packages/snippet-bot/src/snippet-bot.ts
> fix(snippet-bot): ignore empty file content

- packages/snippet-bot/src/snippets.ts
> fix(snippet-bot): allow any string value for SnippetStatus

- packages/merge-on-green/src/merge-on-green.ts
- packages/merge-on-green/test/merge-on-green.ts
> fix(merge-on-green): revert adding cron job

- packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/src/conventional-commit-lint.ts
- packages/conventional-commit-lint/test/conventional-commit-lint.ts
- packages/conventional-commit-lint/test/fixtures/commit_with_long_body_line_length.json
Changed body line length limit from 100 to 256 to accommodate longer line length
> fix(conventional-commit): Allow longer body line length

- packages/header-checker-lint/__snapshots__/header-checker-lint.js
> build: update snapshots for new year

- metrics/dashboards.sql
We came up on the distant point in the future I'd chosen.
> fix(metrics): extend metrics to 2022

- packages/header-checker-lint/src/header-parser.ts
- packages/header-checker-lint/test/fixtures/mit-header.txt
- packages/header-checker-lint/test/header-parser.ts
> fix: add additional acceptance criteria for MIT headers

- packages/release-please/package-lock.json
- packages/release-please/package.json
https://github.com/googleapis/release-please/releases/tag/v9.3.0
This should fix file search for releasing to the non-default branch.
> deps: update release-please to 9.3.0

- packages/do-not-merge/package-lock.json
- packages/do-not-merge/package.json
- packages/do-not-merge/src/do-not-merge.ts
- packages/do-not-merge/test/test.ts
> fix(do-not-merge): upgrade to probot 11/gcf-utils 7

- packages/buildcop/package-lock.json
- packages/buildcop/package.json
- packages/buildcop/src/buildcop.ts
- packages/buildcop/src/main.ts
- packages/buildcop/test/buildcop.ts
> fix(buildcop): upgrade buildcop to probot 11/gcf-utils 7

- packages/failurechecker/package-lock.json
- packages/failurechecker/package.json
- packages/failurechecker/src/failurechecker.ts
- packages/failurechecker/test/failurechecker.ts
> fix(failurechecker): upgrade to probot 11; gcf-utils 7

- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/package.json
- packages/conventional-commit-lint/src/conventional-commit-lint.ts
- packages/conventional-commit-lint/test/conventional-commit-lint.ts
Reverts googleapis/repo-automation-bots#1310
> Revert "fix(conventional-commit-lint): upgrade to gcf-utils 7/Probot 11"

- packages/failurechecker/package-lock.json
- packages/failurechecker/package.json
- packages/failurechecker/src/failurechecker.ts
- packages/failurechecker/test/failurechecker.ts
Reverts googleapis/repo-automation-bots#1312
> Revert "fix(failurechecker): upgrade to probot 11; gcf-utils 7"

- packages/do-not-merge/package-lock.json
- packages/do-not-merge/package.json
- packages/do-not-merge/src/do-not-merge.ts
- packages/do-not-merge/test/test.ts
Reverts googleapis/repo-automation-bots#1311
Fixes #1320
> Revert "fix(do-not-merge): upgrade to probot 11/gcf-utils 7"

- packages/flakybot/package-lock.json
- packages/flakybot/package.json
We were getting a 401 due to the bad release of gcf-utils.
> fix(flakybot): downgrade gcf-utils

- packages/flakybot/package-lock.json
- packages/flakybot/package.json
- packages/flakybot/src/flakybot.ts
- packages/flakybot/src/main.ts
Version _6.3.1_ had been released that pulled in probot 11, before I released _7.0.0_ (which I thought was the first release with probot 11).
I've made the latest release _6.2.0_ now, which is the last known good point in time.
> fix(flakybot): actually downgrade to probot 10

- packages/sync-repo-settings/test/fixtures/localConfigWithoutBranchProtection.yaml
- packages/sync-repo-settings/test/test.ts
> testing(sync-repo-settings): add a test for skipping branch protection

- packages/owl-bot/cloudbuild.yaml
Actually add the build config.
> build(owl-bot): add deployment config

- packages/merge-on-green/src/merge-on-green.ts
> chore: add org to allowlist

- packages/gcf-utils/package.json
> fix(gcf-utils): release as appropriate version

- packages/owl-bot/src/handlers.ts
- packages/owl-bot/src/owl-bot.ts
End to end test of `.owl-bot.lock` update.
> feat(owl-bot): update .owl-bot.lock on updated container

- packages/owl-bot/src/bin/commands/open-pr.ts
- packages/owl-bot/src/handlers.ts
- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/handlers.ts
- packages/owl-bot/test/owl-bot.ts
Add logging so that I can see what's populated by Container Store in PubSub message.
> debug(owl-bot): add logging to make debugging easier

- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
Build of gcf-utils with additional debug messages, so I can get to the bottom of missing payloads from Container Registry PubSub message.
> debug(owl-bot): debug build of owl-bot

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
- packages/release-please/test/release-please.ts
This should fix the Java release PRs
> deps: update release-please to 11.0.0-candidate.0

- packages/owl-bot/src/handlers.ts
ISO date was not valid in a branch name.
> fix(owlbot): switch to timestamp from ISO date

- packages/monitoring-system/data-processor/src/data-processors/data-processor-abstract.ts
As reported here: https://github.com/googleapis/repo-automation-bots/pull/1453/checks?check_run_id=1968813569
> fix: typescript 4.2 error

- packages/auto-label/package-lock.json
- packages/auto-label/package.json
- packages/sync-repo-settings/package.json
> build: update auto-label package-lock

- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
we were firing the post processor on events that did not update code.
> fix(owlbot): fire on less PR events

- packages/owl-bot/cloud-build/scan-googleapis-gen-and-create-pull-requests.yaml
- packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
- packages/owl-bot/src/bin/commands/copy-exists.ts
- packages/owl-bot/src/bin/commands/enqueue-copy-tasks.ts
- packages/owl-bot/src/bin/commands/open-pr.ts
- packages/owl-bot/src/bin/commands/scan-configs.ts
- packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
- packages/owl-bot/src/bin/owl-bot.ts
- packages/owl-bot/src/configs-store.ts
- packages/owl-bot/src/copy-code.ts
- packages/owl-bot/src/core.ts
- packages/owl-bot/src/database.ts
- packages/owl-bot/src/github-repo.ts
- packages/owl-bot/src/octokit-util.ts
- packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
- packages/owl-bot/test/copy-code.ts
- packages/owl-bot/test/database.ts
- packages/owl-bot/test/dir-tree.ts
- packages/owl-bot/test/fake-configs-store.ts
- packages/owl-bot/test/handlers.ts
- packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Now with tests!
Obviates https://github.com/googleapis/repo-automation-bots/pull/1480
> feat: scan-googleapis-gen-and-create-pull-requests

- packages/generate-bot/templates/.eslintrc.json
- packages/generate-bot/templates/README.md
> chore: fix spacing and year in generate-bot templates

- packages/policy/src/policy.ts
- packages/policy/test/test.policy.ts
> fix(policy): look for renovate.json5

- packages/policy/package-lock.json
- packages/policy/package.json
- packages/policy/src/bot.ts
- packages/policy/src/changer.ts
- packages/policy/src/cli.ts
- packages/policy/test/test.bot.ts
- packages/policy/test/test.changer.ts
- packages/policy/test/test.cli.ts
If we detect a missing code of conduct, use code-suggester to submit a PR adding it :)
> feat(policy): automatically propose code of conduct

- packages/policy/README.md
- scripts/publish-function.sh
> chore: update task queue config and add IAM bindings

- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
If running the OwlBot Post Processor results in a pull request with no changes, automatically close the pull request.
> feat(owlbot): close empty PRs

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/test/release-please.ts
> test(release-please): switch to use sinon for testing

- packages/release-brancher/README.md
- packages/release-brancher/package.json
> fix(release-brancher): add `@google-cloud` scope to package name

- packages/release-brancher/README.md
> docs: install releasae-brancher globally to run

- packages/release-brancher/README.md
> docs: add more context and improve instructions

- packages/owl-bot/src/copy-code.ts
- packages/owl-bot/test/copy-code.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/1575
> fix: don't commit changes when user runs owl-bot copy-code

- scripts/cron-deploy.sh
> build: fix number of args check

- packages/release-brancher/README.md
- packages/release-brancher/__snapshots__/release-brancher.js
- packages/release-brancher/package-lock.json
- packages/release-brancher/src/bin/commands/create-pull-request.ts
- packages/release-brancher/src/release-brancher.ts
- packages/release-brancher/test/fixtures/workflows/empty-objects.yaml
- packages/release-brancher/test/fixtures/workflows/non-object.yaml
- packages/release-brancher/test/fixtures/workflows/only-pull-request.yaml
- packages/release-brancher/test/fixtures/workflows/only-push.yaml
- packages/release-brancher/test/fixtures/workflows/push-pull-request-branches.yaml
- packages/release-brancher/test/release-brancher.ts
> feat: create a second pull request to the new branch duplicating ci config

- scripts/migrate-owl-bot/README.md
- scripts/migrate-owl-bot/migrate-owl-bot-nodejs.ps1
- scripts/migrate-owl-bot/migrate-owl-bot-python.ps1
And a README explaining how to use them.
> feat: scripts for migrating python and nodejs repos

- packages/release-please/README.md
- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
- packages/release-please/test/fixtures/config/extra_files.yml
- packages/release-please/test/release-please.ts
Fixes https://github.com/googleapis/release-please/issues/597
> feat(release-please): allow configuring extra files

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 11.8.0

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 11.8.1

- packages/policy/src/bot.ts
- packages/policy/test/test.bot.ts
I'd like to enable the bot specifically for sample and library repositories in the GoogleCloudPlatform org.  To signal they should be included, repos in that org should add the `samples` or `libraries` repository topic.  This is a pattern we were previously using for the sloth version of this bot.
> feat(policy): prepare to run scans on GoogleCloudPlatform org

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/src/merge-on-green.ts
- packages/release-please/src/release-please.ts
Add some additional meta information to metrics.
> metrics: add additional context to metrics

- metrics/snippet-bot-number-of-prevented-violations.sql
This is the sql used for the current dashboard.
> chore: add sql for snippet-bot metrics

- metrics/do-not-merge-labeled.sql
- metrics/flakybot-issues-opened.sql
- metrics/legacy-dashboards.sql
- metrics/merge-on-green-labeled.sql
- metrics/merge-on-green-merged.sql
- metrics/release-please-releases.sql
- metrics/total-people-hours.sql
* Get our new graphs under version control.
* Add note about deprecation for old dashboards.
> metrics: add metrics to version control

- packages/auto-approve/README.md
- packages/auto-approve/__snapshots__/check-config.test.js
- packages/auto-approve/src/valid-pr-schema.json
- packages/auto-approve/test/fixtures/config/invalid-schemas/invalid-schema5.yml
- packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema1.yml
- packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema3.yml
Add auto-approve option for approving PRs like [this one](https://github.com/googleapis/google-api-python-client/pull/1308).
> chore: Add title and author option for auto-approve

- packages/merge-on-green/README.md
> docs(m-o-g): add more details to README

- packages/snippet-bot/src/snippet-bot.ts
> fix(snippet-bot): limit the length of the issue comment

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps(release-please): update release-please to 11.10.0

- packages/owl-bot/src/copy-code.ts
- packages/owl-bot/src/core.ts
- packages/owl-bot/src/handlers.ts
- packages/owl-bot/test/owl-bot.ts
Stop owl bot from closing pull requests that have nothing to do with owl bot.
Fixes https://github.com/googleapis/repo-automation-bots/issues/1709
> fix: issue 1709

- packages/generate-bot/src/main.ts
Just trying to chip away...
Fixes #1257
> fix: look at bot name, provide more helpful error message

- packages/label-sync/src/label-sync.ts
> fix(label-sync): quit when failed to get config

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
> feat(release-please): inject gcf-utils logger into release-please

- packages/owl-bot/cloud-build/update-pr.yaml
Fixes https://github.com/googleapis/repo-automation-bots/issues/1752
> fix: clone the pull request's branch directly

- packages/generated-files-bot/package-lock.json
Fixes https://github.com/advisories/GHSA-cf4h-3jhx-xvhq
> fix(deps): update package-lock to update underscore to 1.12.1

- packages/auto-label/package-lock.json
- packages/auto-label/src/auto-label.ts
Fixes https://github.com/advisories/GHSA-f2jv-r9rf-7988
> fix(deps): update package-lock to fix handlebars version

- packages/blunderbuss/package-lock.json
Should fix #1766
Fix for the connection reset should be in grpc 1.3.1.
> deps(blunderbuss): update package-lock to update grpc version

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/test/merge-logic.ts
Add logging to see if GH's mergeability definition matches our own
See  #1439
> chore: add metrics to confirm whether GHs mergeability is correct

- .release-please-manifest.json
- packages/bot-config-utils/package-lock.json
- packages/bot-config-utils/package.json
- packages/datastore-lock/package-lock.json
- packages/datastore-lock/package.json
We decided to rename the package organization to google-automations.
> fix!: rename organization to google-automations 

- packages/release-please/src/release-please.ts
> fix(release-please): prevent crashes in findBranchConfiguration

- packages/header-checker-lint/package-lock.json
- packages/header-checker-lint/package.json
- packages/header-checker-lint/src/config-schema.json
- packages/header-checker-lint/src/config.ts
- packages/header-checker-lint/src/header-checker-lint.ts
- packages/header-checker-lint/test/fixtures/config_copyright_holder.yml
- packages/header-checker-lint/test/fixtures/config_ignored_files.yml
- packages/header-checker-lint/test/fixtures/pull_request_synchronized.json
- packages/header-checker-lint/test/header-checker-lint.ts
- packages/header-checker-lint/tsconfig.json
part of #1038
With this PR, the bot will start validating the config schema on PRs
and submit failing status checks when the config is invalid.
> feat(header-checker-lint): use bot-config-utils

- packages/cron-utils/src/cli.ts
Fixes: `Unknown commands: /usr/local/bin/node, /usr/local/bin/cron-utils`
> fix(cron-utils): slice args

- packages/failurechecker/cloudbuild.yaml
- packages/label-sync/cloudbuild.yaml
- packages/merge-on-green/cloudbuild.yaml
- packages/policy/cloudbuild.yaml
- packages/release-please/cloudbuild.yaml
- packages/slo-stat-bot/cloudbuild.yaml
- packages/sync-repo-settings/cloudbuild.yaml
- scripts/cron-deploy.sh
> build: use cron-utils to deploy crons

- packages/merge-on-green/cron.yaml
> build(merge-on-green): fix yaml spacing

- packages/cron-utils/src/cli.ts
- packages/cron-utils/src/cron-utils.ts
- packages/cron-utils/test/cron-utils.ts
Fixes #1869 
BREAKING CHANGE: adds `functionName` as a parameter to `createOrUpdateCron()`
> fix!: createOrUpdate can update all fields

- .github/trusted-contribution.yml
> chore: use /gcbrun annotation

- packages/trusted-contribution/package-lock.json
- packages/trusted-contribution/package.json
- packages/trusted-contribution/src/trusted-contribution.ts
- packages/trusted-contribution/src/utils.ts
- packages/trusted-contribution/test/trusted-contribution.ts
> fix(trusted-contribution): Use Github token from secret manager

- packages/owl-bot/src/create-pr.ts
- packages/owl-bot/test/create-pr.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/1895
> fix: never create a PR with a title > 255 characters

- packages/owl-bot/cloud-build/update-lock-branch.yaml
Look for the file `post-processor-changes.txt` in the docker image.  If it exists, use it as the commit message when updating lock files.
> feat: pull the lock-update commit message from the docker image

- packages/trusted-contribution/package-lock.json
- packages/trusted-contribution/package.json
- packages/trusted-contribution/src/trusted-contribution.ts
> feat(trusted-contribution): start validating config schema

- packages/snippet-bot/__snapshots__/snippet-bot.js
- packages/snippet-bot/package-lock.json
- packages/snippet-bot/package.json
- packages/snippet-bot/src/snippet-bot.ts
> feat(snippet-bot): start validating config schema upon retrieval

- packages/header-checker-lint/package-lock.json
- packages/header-checker-lint/package.json
- packages/header-checker-lint/src/header-checker-lint.ts
> feat(header-checker-lint): start validating config schema upon retrieval

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
> feat(release-please): start validating config schema upon retrieval

- packages/owl-bot/src/config-files.ts
- packages/owl-bot/src/database.ts
- packages/owl-bot/test/database.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/1934
> fix: cope with invalid regular expressions in .OwlBot.yaml

- .github/snippet-bot.yml
- packages/snippet-bot/__snapshots__/snippet-bot.js
- packages/snippet-bot/src/region-tag-parser.ts
- packages/snippet-bot/src/snippet-bot.ts
- packages/snippet-bot/src/utils.ts
- packages/snippet-bot/test/fixtures/afterFile.txt
- packages/snippet-bot/test/fixtures/beforeFile.txt
- packages/snippet-bot/test/fixtures/diff-rename.txt
- packages/snippet-bot/test/region-tag-parser.ts
> fix(snippet-bot): handle renaming cases correctly

- packages/auto-label/__snapshots__/config-compatibility.js
- packages/auto-label/package-lock.json
- packages/auto-label/package.json
- packages/auto-label/src/auto-label.ts
- packages/auto-label/test/auto-label.ts
- packages/auto-label/test/config-compatibility.ts
> feat(auto-label): start validating config schema upon retrieval

- packages/header-checker-lint/package-lock.json
- packages/header-checker-lint/package.json
- packages/header-checker-lint/test/header-checker-lint.ts
- packages/trusted-contribution/package-lock.json
- packages/trusted-contribution/package.json
- packages/trusted-contribution/src/trusted-contribution.ts
- packages/trusted-contribution/src/utils.ts
- packages/trusted-contribution/test/trusted-contribution.ts
> fix(header-checker-lint, trusted-contribution): use sinon.assert

- packages/generated-files-bot/package-lock.json
- packages/generated-files-bot/package.json
- packages/generated-files-bot/src/generated-files-bot.ts
- packages/generated-files-bot/test/generated-files-bot.ts
> feat(generated-files-bot): validate config schema upon retrieval

- packages/flakybot/package-lock.json
- packages/flakybot/package.json
- packages/flakybot/src/flakybot.ts
- packages/flakybot/test/flakybot.test.ts
> feat(flakybot): start validating config schema upon retrieval

- packages/blunderbuss/cloudbuild.yaml
- packages/blunderbuss/cron.yaml
- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
- packages/blunderbuss/src/blunderbuss.ts
- packages/blunderbuss/src/utils.ts
- packages/blunderbuss/test/blunderbuss.ts
> feat(blunderbuss): start syncing blunderbuss label

- packages/blunderbuss/package-lock.json
Amusingly the lock file has a git conflict. It went through the test and deployment.
> chore(blunderbuss): update lock file

- packages/snippet-bot/src/snippet-bot.ts
- packages/snippet-bot/test/snippet-bot.ts
> fix(snippet-bot): add missing schema check

- packages/snippet-bot/test/snippet-bot.ts
fixes #1946
These are the last ones and now we're good to go.
> fix(snippet-bot): fix remaining wrong calledOnceWith

- packages/mono-repo-publish/package-lock.json
- packages/release-brancher/package-lock.json
- packages/sync-repo-settings/package-lock.json
- packages/trusted-contribution/package-lock.json
Created by the script in #1978
> chore: lock file maintainance

- packages/snippet-bot/package-lock.json
- packages/snippet-bot/package.json
- packages/snippet-bot/src/utils.ts
part of #1984
We can experiment with snippet-bot and if it works, we can roll it
out to other bots.
> fix(snippet-bot): use gcf-utils@8.0.2

- packages/bazel-bot/docker-image/generate-googleapis-gen.sh
We may end up reverting this when Jeff is back in the office, but I think this is a good hot fix to unblock @parthea.
Fixes #1993
Fixes #1983
Fixes #1982
> feat: allow bad SHAs to be skipped

- scripts/update-package-locks.sh
It will update the package.json too. `npm update` will respect the semver, so it will only update the minor versions in most of the cases (since we normally use `^`).
> chore: Also run `npm update` in update-package-locks.sh

- packages/auto-label/package-lock.json
- packages/blunderbuss/package-lock.json
- packages/failurechecker/package-lock.json
- packages/label-sync/package-lock.json
> fix: upgrade to gcf-utils@8.0.2

- packages/policy/package-lock.json
- packages/release-please/package-lock.json
- packages/sync-repo-settings/package-lock.json
> fix: fix scheduler with gcf-utils@8.0.2

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
This will ensure new gcf-utils works for us.
> chore(canary-bot): update package.json and lock file

- packages/owl-bot/.dockerignore
- packages/owl-bot/src/copy-code.ts
fixes https://github.com/googleapis/repo-automation-bots/issues/2013
fixes https://github.com/googleapis/repo-automation-bots/issues/2046
> fix: don't attempt to delete files that aren't there

- packages/auto-approve/package-lock.json
- packages/auto-approve/package.json
- packages/auto-label/package-lock.json
- packages/auto-label/package.json
- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
- packages/bot-config-utils/package-lock.json
- packages/bot-config-utils/package.json
Used the script in #2041, splitting 4 packages in a PR.
> chore: update package.json and package-lock.json

- packages/generated-files-bot/package-lock.json
- packages/generated-files-bot/package.json
Somehow npm i resolved to older versions.
I needed to add explicit dev dependencies.
> chore(generated-files-bot): fix warning from dependabot

- packages/flakybot/cloudbuild.yaml
- packages/flakybot/cron.yaml
- packages/flakybot/package-lock.json
- packages/flakybot/package.json
- packages/flakybot/src/flakybot.ts
- packages/flakybot/src/labels.ts
- packages/flakybot/test/flakybot.test.ts
It only sync `flakybot: quiet` label.
part of #1673
> feat(flakybot): starts to sync its label

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/labels.ts
- packages/release-please/src/release-please.ts
- packages/release-please/test/release-please.ts
> feat(release-please): start syncing label

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/app.ts
also running canary-bot with `background:false` because we want to make
sure the cron works for "foreground" bots.
> chore(canary-bot): deploy with gcf-utils@10.0.2

- packages/flakybot/package-lock.json
- packages/flakybot/package.json
fixes #2068
Maybe we should wait for the result from #2077
> fix(flakybot): fix the broken scheduler job

- packages/merge-on-green/cron.yaml
- packages/merge-on-green/package-lock.json
- packages/merge-on-green/package.json
- packages/merge-on-green/src/labels.ts
- packages/merge-on-green/src/merge-on-green.ts
- packages/merge-on-green/test/merge-on-green.ts
> feat(merge-on-green): start syncing labels

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/app.ts
Reverts googleapis/repo-automation-bots#2077
> Revert "chore(canary-bot): deploy with gcf-utils@10.0.2"

- packages/canary-bot/cron.yaml
- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/canary-bot.ts
Updates to gcf-utils v11 and adds 2 new cron handlers that log that they ran.
> feat: add installation/global crons

- packages/owl-bot/README.md
- packages/owl-bot/cloud-build/update-pr.yaml
- packages/owl-bot/src/core.ts
> fix(owl-bot): set credentials earlier in the build

- packages/canary-bot/src/app.ts
Reverts googleapis/repo-automation-bots#2099
> Revert "fix: temporarily disable canary payload verification"

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
> fix(deps): update gcf-utils to v11.0.1 in canary-bot

- packages/sync-repo-settings/src/required-checks.json
- packages/sync-repo-settings/test/test.bot.ts
Make OwlBot a required check for Node.js.
Refs #1714
> feat(owlbot): require OwlBot before merging

- packages/snippet-bot/package-lock.json
- packages/snippet-bot/package.json
- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
- packages/trusted-contribution/package-lock.json
- packages/trusted-contribution/package.json
- packages/trusted-contribution/src/app.ts
- snippet-bot
- sync-repo-settings
- trusted-contribution
For trusted-contribution, I changed it to `background`: true.
> fix: upgrade to gcf-utils@11

- packages/gcf-utils/src/gcf-utils.ts
> fix: queue in repository tasks in parallel

- packages/snippet-bot/package-lock.json
- packages/snippet-bot/package.json
- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
- packages/trusted-contribution/package-lock.json
- packages/trusted-contribution/package.json
This should fix failing cron jobs.
> fix: update to gcf-utils@11.0.2

- packages/merge-on-green/package-lock.json
- packages/merge-on-green/package.json
Reverts googleapis/repo-automation-bots#2125
> Revert "fix(deps): update dependency gcf-utils to v10.1.0"

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
> fix: upgrade canary-bot to gcf-utils@11.1.0

- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/fixtures/suspended_installations.json
- packages/gcf-utils/test/gcf-bootstrapper.ts
> fix(gcf-utils): skip suspended installations

- packages/merge-on-green/package-lock.json
- packages/merge-on-green/package.json
> fix(merge-on-green): fix the syncLabels cron handler

- packages/cron-utils/src/cron-utils.ts
> fix(cron-utils): set attemptDeadline=540s

- packages/gcf-utils/package.json
- packages/gcf-utils/src/gcf-utils.ts
- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
- packages/owl-bot/src/app.ts
The signature validation is failing for pubsub messages.
> build(owlbot): turn off signature verification until we can debug payload

- packages/gcf-utils/src/server/server.ts
- packages/gcf-utils/test/server.ts
> fix: express server should save rawBody

- packages/merge-on-green/src/merge-on-green.ts
> fix: allow google-github-actions to use merge-on-green

- scripts/publish-function.sh
https://cloud.google.com/functions/docs/securing/function-identity#individual
Fixes #2197
> build: allow configuring GCF function identity

- scripts/publish-function.sh
Reverts googleapis/repo-automation-bots#2202
> Revert "build: allow configuring GCF function identity"

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
Should fix the dasherized queue target issue
> deps: update gcf-utils in canary_bot

- packages/owl-bot/.dockerignore
- packages/owl-bot/Dockerfile.frontend
- packages/owl-bot/cloudbuild-test.yaml
- packages/owl-bot/cloudbuild.yaml
- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
- packages/owl-bot/src/server.ts
This change itself should not break anything.
After the deployment, we test the flow from Cloud Run frontend to
the Cloud Tasks. If it works, we can change the Github bot's webhook
URL.
> feat(owl-bot): deploy frontend server in Cloud Run.

- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
We should update a PR with a failed status if the .OwlBot.lock is invalid.
Fixes #2204
> fix(owlbot): report failure if .OwlBot.lock is invalid

- packages/owl-bot/cloudbuild.yaml
- scripts/publish-cloud-run.sh
Default values
timeout: 3600 (seconds)
min-instance: 0
> feat(owl-bot): specify the min instance and timeout

- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/gcf-bootstrapper.ts
- scripts/publish-cloud-run.sh
- scripts/publish-function.sh
> fix: detect default task target runtime from environment

- trigger-sync/sync-triggers.sh
Sync triggers for cloudbuild-test files. Similar to auto-detecting cloudbuild.yaml deployments, look for cloudbuild-test.yaml files and create presubmit triggers that run if a file in that directory is modified
> build: sync presubmit triggers from detected cloudbuild-test.yaml files

- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/gcf-bootstrapper.ts
- packages/gcf-utils/test/server.ts
Returns a 400 on signature verification errors.
Fixes #2224
> fix: return a 400 on requests with missing or bad signatures

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/canary-bot.ts
- packages/canary-bot/test/test.ts
- serverless-scheduler-proxy/main.go
also add corresponding code to serverless proxy
fixes #2182
> feat(canary): add Pub/Sub handler

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/canary-bot.ts
- packages/canary-bot/test/test.ts
I needed to cast stuff to `any` in many places.
> testing(canary): use gcf-utils@12 and Probot@12

- packages/bot-config-utils/package-lock.json
- packages/bot-config-utils/package.json
- packages/datastore-lock/package-lock.json
- packages/datastore-lock/package.json
- packages/label-utils/package-lock.json
- packages/label-utils/package.json
- packages/object-selector/package-lock.json
- packages/object-selector/package.json
part of #2203
I think we need to upgrade libraries to gcf-utils@12 first, then we can upgrade our bots.
> feat: upgrade to gcf-utils@12

- packages/do-not-merge/package-lock.json
- packages/do-not-merge/package.json
- packages/do-not-merge/src/do-not-merge.ts
- packages/do-not-merge/test/test.ts
- packages/failurechecker/package-lock.json
- packages/failurechecker/package.json
- packages/failurechecker/src/failurechecker.ts
- packages/failurechecker/test/failurechecker.ts
- packages/flakybot/package-lock.json
- packages/flakybot/package.json
- packages/flakybot/src/flakybot.ts
- packages/flakybot/test/flakybot.test.ts
- do-not-merge
- failurechecker
- flakybot
> chore: upgrade gcf-utils@12

- packages/auto-label/package-lock.json
- packages/auto-label/package.json
- packages/auto-label/src/auto-label.ts
- packages/auto-label/test/auto-label.ts
- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
- packages/blunderbuss/src/blunderbuss.ts
- packages/blunderbuss/src/utils.ts
- packages/blunderbuss/test/blunderbuss.ts
- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/package.json
- auto-label
- blunderbuss
- conventional-commit-lint
> chore: upgrade to gcf-utils@12

- packages/release-please/package-lock.json
- packages/release-please/package.json
Release-please should not hit the race condition where we don't see the newly merged release PR.
Towards #2188
> deps: update release-please to 11.16.2

- packages/release-please/src/release-please.ts
- packages/release-please/test/release-please.ts
> fix: ignore MissingRequiredFileError for now

- packages/release-please/package-lock.json
- packages/release-please/package.json
> fix(deps): update release-please to 11.19.0

- packages/release-please/package-lock.json
- packages/release-please/package.json
Latest release-please with fix for https://github.com/googleapis/release-please/issues/988
Fixes https://github.com/googleapis/release-please/issues/988
> deps(release-please): release please with fix for pre-releases

- packages/release-please/package-lock.json
- packages/release-please/package.json
Release please with fixes for Python versioning.
> fix(release-please): release please with fixes for python versioning

- packages/sync-repo-settings/src/bot.ts
- packages/sync-repo-settings/src/sync-repo-settings.ts
- packages/sync-repo-settings/test/sync-repo-settings.ts
- packages/sync-repo-settings/test/test.bot.ts
> feat(sync-repo-settings): support default branch from API or payload

- packages/owl-bot/cloud-build/copy-code-again.yaml
- packages/owl-bot/src/copy-code.ts
- packages/owl-bot/src/core.ts
- packages/owl-bot/src/create-pr.ts
- packages/owl-bot/src/update-lock.ts
- packages/owl-bot/test/owl-bot.ts
- packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
- packages/owl-bot/test/update-lock.ts
See commit messages for more details.
> fix: many issues with "regenerate me" checkbox

- metrics/auto-approve.sql
- metrics/do-not-merge-labeled.sql
- metrics/generated-files-bot.sql
- metrics/github-label-metrics.sql
- metrics/merge-on-green-labeled.sql
- metrics/merge-on-green-merged.sql
- metrics/owlbot-label-metrics.sql
- metrics/release-please-releases.sql
- metrics/total-people-hours.sql
- metrics/trusted-contribution-label-added.sql
Checking in metrics currently used to build dashboards.
> metrics: updated SQL for metrics

- packages/owl-bot/cloud-build/update-pr.yaml
> fix(owl-bot): Reduce Risk of Git Conflicts When Updating PRs

- .github/workflows/deps.yaml
- .github/workflows/list-node-paths.js
This runs @tmatsuo's `update-dependencies.sh` script on a schedule and sends a pull request weekly Monday morning.
> build: add workflow for updating lock files

- packages/release-please/src/release-please.ts
- packages/release-please/test/fixtures/config/valid_handle_gh_release_alternate_branch.yml
- packages/release-please/test/release-please.ts
> fix: release-please tagging releases should handle alternate branches

- packages/owl-bot/cloud-build/copy-code-again.yaml
- packages/owl-bot/cloud-build/scan-googleapis-gen-and-create-pull-requests.yaml
- packages/owl-bot/cloud-build/update-lock-branch.yaml
- packages/owl-bot/src/create-pr.ts
Reverts googleapis/repo-automation-bots#2441
There's no evidence, but I think this PR might be causing failures in #2478 and #2503
> Revert "fix(owl-bot): Fallback to Pull, Push when Push Fails When Creating PR"

- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
> feat(owl-bot): Open Status Check on Loop

- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
> feat(owl-bot): Remove OwlBot Run Label Before Post Processor

- packages/release-please/package-lock.json
- packages/release-please/package.json
We were seeing exceptions in logs if PR body becomes too long (>65536 bytes).
> fix(release-please): release-please with fix for max PR length

- .github/release-please.yml
we missed migrating this repo (the cobblers children have no shoes).
> build: release-please should handle releases

- packages/flakybot/__snapshots__/flakybot.test.js
- packages/flakybot/src/flakybot.ts
- packages/flakybot/test/flakybot.test.ts
> fix(flakybot): add a new comparator for finding existing issue

- packages/owl-bot/src/bin/commands/trigger-build.ts
- packages/owl-bot/src/core.ts
- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
- packages/owl-bot/test/owl-core.ts
Distinguish between errors fetching the lock file and errors parsing the lock file.
Fixes https://github.com/googleapis/repo-automation-bots/issues/2609
> fix: improved error reporting lock.yaml failures

- packages/owl-bot/bootstrap-scan-and-retry-failed-lock-updates.sh
- packages/owl-bot/src/bin/commands/scan-and-retry-failed-lock-updates.ts
- packages/owl-bot/src/bin/commands/scan-configs.ts
- packages/owl-bot/src/serve.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/1777
> fix: convert retry-builds into cloud run job

- packages/release-brancher/__snapshots__/release-brancher.js
- packages/release-brancher/src/bin/commands/create-pull-request.ts
- packages/release-brancher/src/release-brancher.ts
- packages/release-brancher/test/release-brancher.ts
- packages/release-please/src/config-schema.json
Fixes #2568
```
release-brancher create-pull-request \
--branch-name="2.3.x" \
--target-tag="v2.3.4" \
--repo="<repo-owner>/<repo-name>" \
--pull-request-title="feat: next release from mainline is 2.4.0"
--release-type=java-backport
```
It worked
```
suztomo-macbookpro44% release-brancher create-pull-request --branch-name="1.40.0-sp.4" --target-tag="v1.40.0" --repo="suztomo/google-http-java-client"  --release-type=java-lts-on-patch --pull-request-title="feat: next release from mainline is 1.41.0"
creating branch 1.40.0-sp.4 as SHA f77608fbfb41410a8f62f40bc5a2df256c751d52
```
It created https://github.com/suztomo/google-http-java-client/pull/16 and https://github.com/suztomo/google-http-java-client/pull/15
---
Thank you for opening a Pull Request! Before submitting your PR, there are a few …
> feat(release-brancher): add argument to override pull request title

- packages/merge-on-green/src/merge-on-green.ts
- packages/merge-on-green/test/merge-on-green.ts
> fix: get installation Ids for m-o-g

- packages/policy/cloudbuild.yaml
It looks to have been erroneously added.
> build: remove cloud run deployment

- packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
- packages/owl-bot/src/bin/commands/copy-exists.ts
- packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
- packages/owl-bot/src/copy-code.ts
- packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
- packages/owl-bot/test/copy-code.ts
- packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
> fix: look deeper into pull request history

- packages/owl-bot/Dockerfile
> fix(owl-bot): bump the heap size

- packages/owl-bot/src/copy-code.ts
- packages/owl-bot/test/copy-code.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/2867
> fix: correctly remove nested directories

- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
> fix(owl-bot): restrict organization for running post processor

- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/fixtures/not_allowed_installations.json
- packages/gcf-utils/test/gcf-bootstrapper.ts
> feat(gcf-utils): add allowed_organizations to repository cron

- packages/owl-bot/cron.yaml
- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
> fix(owl-bot): limit organization for the cron job

- packages/merge-on-green/cron.yaml
- packages/merge-on-green/package-lock.json
- packages/merge-on-green/package.json
fixes #2901
The similar change for owl-bot works as expected.
> fix(mog): limit organization for cron

- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
> chore: update probot to 12.1.1

- packages/policy/package-lock.json
- packages/policy/src/bot.ts
- packages/policy/src/changer.ts
- packages/policy/test/test.changer.ts
> fix(policy): do not throw for missing branch

- packages/owl-bot/README.md
- packages/owl-bot/cloud-build/update-pr.yaml
- packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
- packages/owl-bot/src/fetch-configs.ts
- packages/owl-bot/test/commit-post-processor-update.ts
> feat(owl-bot): Acknowledge Ignore label Before Updating PRs

- packages/auto-label/README.md
- packages/auto-label/src/auto-label.ts
- packages/auto-label/src/config-schema.json
- packages/auto-label/src/helper.ts
- packages/auto-label/test/auto-label.ts
- packages/auto-label/test/fixtures/config/valid-config-staleness.yml
- packages/label-sync/src/labels.json
Rename staleness.critical config parameter to staleness.extraold and update README.md with staleness bot definition
> fix: Rename staleness.critical config parameter to staleness.extraold and update README.md

- packages/repo-metadata-lint/src/file-iterator.ts
Confirm our permission error is where It's believed to be.
> debug(repo-metadata-lint): add debug logging for permission issue

- packages/trusted-contribution/src/trusted-contribution.ts
- packages/trusted-contribution/test/trusted-contribution.ts
Only adds `owlbot:run` label if OwlBot configuration is found.
CC: @kurtisvg
> feat(trusted-contributor): only add owlbot:run if config found

- packages/sync-repo-settings/src/required-checks.json
- packages/sync-repo-settings/test/test.bot.ts
> feat(sync-repo-settings): switch to Node 16 in matrix

- packages/release-please/package-lock.json
- packages/release-please/package.json
This should fix java's snapshot releases
> deps: update release-please to 13.2.0

- packages/repo-metadata-lint/src/error-message-text.ts
To make it easier to know what edits to make to `.repo-metadata.json`, link to the schema and API listing.
> docs(repo-metadata-link): link to schema and API index

- packages/release-please/package-lock.json
- packages/release-please/package.json
See https://github.com/googleapis/release-please/releases/tag/v13.4.0
> deps: update release-please to 13.4.0

- packages/release-trigger/package-lock.json
- packages/release-trigger/package.json
- packages/release-trigger/src/bot.ts
- packages/release-trigger/src/release-trigger.ts
- packages/release-trigger/test/bot.ts
> fix: trigger releases under lock

- packages/owl-bot/src/bin/commands/write-lock.ts
- packages/owl-bot/src/write-lock.ts
- packages/owl-bot/test/write-lock.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/2190
> fix: add a copyright message to .OwlBot.lock.yaml files

- packages/release-please/package-lock.json
- packages/release-please/package.json
* handle windows newlines in pull request body
* **python:** fix version regex to find multiple digit patch versions
* **python:** restore default changelog config for python
https://github.com/googleapis/release-please/releases/tag/v13.4.1
> deps: update release-please to 13.4.1

- packages/owl-bot/cloud-build/force-update-lock-branch.yaml
- packages/owl-bot/src/bin/commands/maybe-create-pull-request-for-lock-update.ts
- packages/owl-bot/src/bin/commands/scan-and-retry-failed-lock-updates.ts
- packages/owl-bot/src/scan-and-retry-failed-lock-updates.ts
- packages/owl-bot/src/update-lock.ts
- packages/owl-bot/test/scan-and-retry-failed-lock-updates.ts
- packages/owl-bot/test/update-lock.ts
> fix: open a pull request for lock updates that failed

- packages/release-please/package-lock.json
- packages/release-please/package.json
* read packageName from config
* cargo workspace cargo lock handling
* krm blueprints should update yaml files
> deps: update release-please to v13.4.6

- packages/bazel-bot/docker-image/generate-googleapis-gen.sh
> fix: run on PR titles in bazel bot

- packages/owl-bot/src/bin/commands/maybe-create-pull-request-for-copy.ts
- packages/owl-bot/src/bin/owl-bot.ts
I forgot to add it to the command list.
> chore: add maybeCreatePullRequestForCopyCommand

- packages/auto-approve/src/auto-approve.ts
- packages/auto-approve/src/check-config.ts
- packages/auto-approve/src/get-pr-info.ts
- packages/auto-approve/src/interfaces.ts
> chore(auto-approve): handle config not found error as a code error

- packages/release-please/package-lock.json
- packages/release-please/package.json
I think we aren't handling FileNotFound correctly
> deps: pin release-please to 13.4.10

- packages/release-please/package.json
* handle failures during multiple release creation
> deps: update release-please to 13.4.13

- packages/owl-bot/src/owl-bot.ts
I'm suspicious that the `synchronize` event might be the issue, let's find out.
> logging: add debug logging for generator kick off

- packages/datastore-lock/src/datastore-lock.ts
Instantiating a GRPC client multiple times in the same cloud function can lead to memory overhead.
It should be safe to cache the client.
> fix(datastore-lock): cache long-running client

- packages/owl-bot/src/copy-code.ts
to debug an issue which only happens in production
> chore: more logging for regenerating pull request

- packages/snippet-bot/Dockerfile
- packages/snippet-bot/cloudbuild.yaml
- packages/snippet-bot/src/server.ts
It still uses the same backend on Cloud Function, but it will reduce missing webhooks.
> build: add snippet-bot frontend server

- packages/snippet-bot/package.json
I need to change the `start` command
> fix: fix snippet-bot frontend server

- packages/release-please/Dockerfile
- packages/release-please/cloudbuild.yaml
- packages/release-please/package.json
- packages/release-please/src/server.ts
> build: deploy release-please frontend

- .repo-metadata.json
> chore: fix repo-metadata fields

- packages/owl-bot/cloudbuild.yaml
> fix(owl-bot): fix cloudbuild.yaml

- packages/gcf-utils/Dockerfile
- packages/gcf-utils/package-lock.json
build(gcf-utils): update Dockerfile version
> build(gcf-utils): update to v2 npm lock

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/server.ts
This PR is for testing the new gcf-utils with a backend in Cloud Functions.
> testing(canary-bot): test the new gcf-utils

- packages/owl-bot/cloudbuild.yaml
- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
- packages/owl-bot/publish-cloud-run-backend.sh
Just added required envvars to owl-bot cloud run backend.
Towards #3318
I added the new substitutions to the build trigger in the project.
> fix(owl-bot): add required envs to owl-bot backend

- packages/owl-bot/src/server-frontend.ts
Now we have necessary env vars with #3325.
Time to another try.
> build(owl-bot): route traffic to the cloud run backend

- packages/owl-bot/Dockerfile.backend
> build(owl-bot): install git to the backend container

- packages/owl-bot/src/server-frontend.ts
> chore(owl-bot): change the routing to Cloud Run backend

- packages/canary-bot/cloudbuild.yaml
canary deployments with new service accounts
> build(canary): use appropriate service accounts for deployments

- packages/label-sync/package-lock.json
- packages/label-sync/package.json
- packages/label-sync/src/app.ts
> chore(label-sync): stop using Cloud Debugger

- packages/owl-bot/cloudbuild.yaml
for cloud function service and the Cloud Run frontend
part of #3424
> build(owl-bot): use dedicated service accounts

- packages/datastore-lock/src/datastore-lock.ts
switch to throwing typed error.
> feat: throw typed error

- packages/conventional-commit-lint/cloudbuild.yaml
- packages/do-not-merge/cloudbuild.yaml
- packages/do-not-merge/package-lock.json
- packages/do-not-merge/package.json
- packages/failurechecker/cloudbuild.yaml
- packages/flakybot/cloudbuild.yaml
- scripts/publish-function.sh
for the following 4 bots:
- conventional-commit-lint
- do-not-merge
- failurechecker
- flakybot
part of #3424
> build: use web-backend service account for bots

- package.json
Unblocks:
- https://github.com/googleapis/repo-automation-bots/pull/3441
- https://github.com/googleapis/repo-automation-bots/pull/3443
🦕
> build: Add `engines` in root `package.json`

- packages/owl-bot/src/server-backend.ts
> fix(owl-bot): initialize Firestore app in an early stage

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/canary-bot.ts
Updating gcf-utils and using the new context logger
> fix: update canary-bot to use context logger

- packages/header-checker-lint/package-lock.json
- packages/header-checker-lint/package.json
- packages/header-checker-lint/src/header-checker-lint.ts
> fix(header-checker-lint): update gcf-utils to 13.4.0 and use context logger

- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
- packages/blunderbuss/src/blunderbuss.ts
- packages/blunderbuss/src/utils.ts
- packages/blunderbuss/test/blunderbuss.ts
> fix(blunderbuss): upgrade gcf-utils and use context-logger

- packages/cherry-pick-bot/package-lock.json
- packages/cherry-pick-bot/package.json
- packages/cherry-pick-bot/src/bot.ts
- packages/cherry-pick-bot/src/branch-protection.ts
- packages/cherry-pick-bot/src/cherry-pick.ts
> fix(cherry-pick-bot): upgrade gcf-utils and use context-logger

- packages/failurechecker/package-lock.json
- packages/failurechecker/package.json
- packages/failurechecker/src/failurechecker.ts
> fix(failurechecker): upgrade gcf-utils and use context-logger

- packages/generated-files-bot/package-lock.json
- packages/generated-files-bot/package.json
- packages/generated-files-bot/src/generated-files-bot.ts
> fix(generated-files): upgrade gcf-utils and use context-logger

- packages/label-sync/package-lock.json
- packages/label-sync/package.json
- packages/label-sync/src/label-sync.ts
- packages/label-sync/test/test.ts
> fix(label-sync): upgrade gcf-utils and use context-logger

- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/package.json
- packages/conventional-commit-lint/src/conventional-commit-lint.ts
> fix(ccl): upgrade gcf-utils and use context-logger

- packages/merge-on-green/package-lock.json
- packages/merge-on-green/package.json
- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/src/merge-on-green.ts
- packages/merge-on-green/test/merge-on-green.ts
> fix(mog): upgrade gcf-utils and use context-logger

- packages/owl-bot/src/copy-code.ts
> fix: insert api names into updated pull request titles

- packages/policy/package-lock.json
- packages/policy/package.json
- packages/policy/src/bot.ts
> fix(policy): update gcf-utils and migrate to context-logger

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
> fix(release-please): update gcf-utils and migrate to context-logger

- packages/policy/package-lock.json
> chore(policy): lock file update

- .github/sync-repo-settings.yaml
Skipped tests pass the requirement (these tests are skipped unless a change is made to the relevant directory).
> build: make Cloud Build tests required

- packages/release-please/package.json
> fix(release-please): update gcf-utils to 13.5.2 for context logger

- packages/merge-on-green/src/merge-on-green.ts
- packages/merge-on-green/test/merge-logic.ts
- packages/merge-on-green/test/merge-on-green.ts
Overwriting the handler methods can leak between tests
> refactor(test): fix stubbing with sinon sandbox

- packages/merge-on-green/src/merge-logic.ts
- packages/merge-on-green/test/merge-logic.ts
> fix(m-o-g): check completed status and allow neutral conclusion

- packages/release-please/README.md
- packages/release-please/src/config-constants.ts
- packages/release-please/src/release-please.ts
Fixes #3119
The feature was implemented in release-please [v13.15.0](https://github.com/googleapis/release-please/releases/tag/v13.15.0).
> feat: add configuration for setting changelog host

- packages/release-please/package-lock.json
- packages/release-please/package.json
Includes hotfix for https://github.com/googleapis/release-please/issues/1424
> deps: update release-please to 13.16.1

- packages/snippet-bot/package-lock.json
Reverts googleapis/repo-automation-bots#3703
For #3707
> Revert "deps: update snippet-bot deps"

- packages/snippet-bot/package-lock.json
- packages/snippet-bot/package.json
used the script + manually installed the latest lru-cache
> build(snippet-bot): update dependencies

- packages/policy/package-lock.json
- packages/policy/package.json
manually installed the latest lru-cache
> build(policy): update dependencies

- packages/release-please/package-lock.json
- packages/release-please/package.json
> fix(deps): update release-please to 13.16.5

- packages/repo-metadata-lint/src/repo-metadata-schema.json
> style: fix typo in repo-metadata-schema

- packages/release-please/package-lock.json
- packages/release-please/package.json
> chore(deps): update package with new header level changes

- packages/merge-on-green/package-lock.json
may or may not fix #3828
I removed the lock file and node_modules directory and run `npm i` and got this lock file.
> build(merge-on-green): update lock file

- packages/release-trigger/cloudbuild.yaml
> build(release-trigger): increase memory, concurrency and minimum instance

- packages/release-trigger/package-lock.json
- packages/release-trigger/package.json
> deps: update gcf-utils for cron throttling

- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/gcf-bootstrapper.ts
Also, the default is 4x faster then before.
> feat(gcf-utils): Make the flow control delay configurable

- packages/owl-bot/src/copy-code.ts
> fix: trust copy source directory

- packages/blunderbuss/src/blunderbuss.ts
> fix: await an unawaited promise

- packages/policy/package-lock.json
- packages/policy/package.json
> deps(policy): use gcf-utils 13.8.0

- packages/policy/cloudbuild.yaml
- packages/policy/package-lock.json
> fix(policy): updated package-lock.json and use nodejs14 runtime

- .github/blunderbuss.yml
adding @SurferJeffAtGoogle back to blunderbuss config
(also testing a new behavior of conventional commit lint bot)
> chore: update blunderbuss config

- packages/cherry-pick-bot/package-lock.json
- packages/cherry-pick-bot/package.json
> deps(cherry-pick-bot): use gcf-utils 13.8.1

- packages/do-not-merge/package-lock.json
I removed node_modules and package-lock.json and run `npm i`.
fixes #3975
> deps(do-not-merge): update package-lock.json

- packages/merge-on-green/package-lock.json
I deleted node_modules and package-lock.json then ran `npm i`
fixes #3979
> deps(mog): update package-lock.json

- packages/release-please/package-lock.json
- packages/release-please/package.json
This includes the fix for when graphql fails to return a response
> deps: update release-please to 13.19.3

- packages/owl-bot/src/copy-code.ts
> fix: Reduce race condition window for appending PR

- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
- packages/sync-repo-settings/src/bot.ts
- packages/sync-repo-settings/test/fixtures/malformed.yaml
- packages/sync-repo-settings/test/test.bot.ts
We now open an issue on the installed repository with the contents of the error. We handle mismatched schema and unparsable YAML. This should help surface any bad configuration to the repository maintainer -- otherwise, it will silently fail (to them, we currently see errors).
Fixes #3869
> feat: sync-repo-settings opens an issue on installed repo for bad config

- packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
- packages/owlbot-bootstrapper/common-container/mono-repo.ts
- packages/owlbot-bootstrapper/common-container/split-repo.ts
- packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
- packages/owlbot-bootstrapper/common-container/test/split-repo.test.ts
- packages/owlbot-bootstrapper/common-container/test/utils.test.ts
- packages/owlbot-bootstrapper/common-container/utils.ts
> fix(owlbot-bootstrapper): remove regenerate textbox process, use owlbot:copy-code label instead

- packages/mono-repo-publish/package.json
> fix: need to compile as part of the prepare step

- packages/release-please/package-lock.json
- packages/release-please/package.json
https://github.com/googleapis/release-please/releases/tag/v13.19.7
> deps: update release-please to 13.19.7

- packages/owl-bot/cloud-build/copy-code-again.yaml
- packages/owl-bot/cloud-build/update-pr.yaml
Fixes https://github.com/googleapis/repo-automation-bots/issues/4087
> fix: extend post procesor timeout to 80 minutes

- packages/bazel-bot/docker-image/docker-main.sh
fixes #3134
It's not a complete fix, but at least the bug is out of the current
mysterious state. I'd close #3134 and open a new one when we see the
same failure, with a better logging output.
> fix(bazel-bot): add pipefail option for better logging

- packages/conventional-commit-lint/README.md
- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/package.json
- packages/conventional-commit-lint/src/conventional-commit-lint.ts
- packages/conventional-commit-lint/src/schema.json
- packages/conventional-commit-lint/test/conventional-commit-lint.ts
- packages/conventional-commit-lint/test/fixtures/config/enabled-false.yaml
- packages/conventional-commit-lint/tsconfig.json
Add support for configuration file, which allows automation to be turned off.
> feat(conventional-commit-lint): support configuration file

- release-please-config.json
> chore: add release config for git-file-utils

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/canary-bot.ts
- packages/canary-bot/test/test.ts
Also added some code for making sure that Octokit instances obtained by
`getAuthenticatedOctokit` work.
> deps(canary): use gcf-utils 14.0.0

- packages/auto-approve/package-lock.json
- packages/auto-approve/package.json
- packages/auto-approve/src/auto-approve.ts
- packages/auto-approve/test/auto-approve.test.ts
- packages/auto-label/package-lock.json
- packages/auto-label/package.json
- packages/auto-label/src/auto-label.ts
- packages/auto-label/test/auto-label.ts
- packages/auto-label/test/config-compatibility.ts
- packages/auto-label/test/language-path-tests.ts
for auto-approve and auto-label
part of #1885
> deps: use gcf-utils 14

- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
- packages/blunderbuss/src/blunderbuss.ts
- packages/blunderbuss/src/utils.ts
- packages/blunderbuss/test/blunderbuss.ts
* also drop node12 support
part of #1885
> deps(blunderbuss): update to gcf-utils 14

- packages/release-please/cloudbuild.yaml
- packages/release-please/src/server.ts
> build: run release-please app on Cloud Run

- packages/flakybot/flakybot.go
- packages/flakybot/package-lock.json
- packages/flakybot/package.json
- packages/flakybot/src/flakybot.ts
- packages/flakybot/test/flakybot.test.ts
> deps(flakybot): update gcf-utils to v14

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 14.1.0

- packages/release-trigger/package-lock.json
- packages/release-trigger/package.json
- packages/release-trigger/src/bot.ts
- packages/release-trigger/src/release-trigger.ts
- packages/release-trigger/src/server-frontend.ts
- packages/release-trigger/test/bot.ts
> deps(release-trigger): update gcf-utils to v14

- packages/repo-metadata-lint/package-lock.json
- packages/repo-metadata-lint/package.json
- packages/repo-metadata-lint/src/file-iterator.ts
- packages/repo-metadata-lint/src/issue-opener.ts
- packages/repo-metadata-lint/src/repo-metadata-lint.ts
- packages/repo-metadata-lint/src/utils/octokit-util.ts
- packages/repo-metadata-lint/src/validate.ts
- packages/repo-metadata-lint/test/issue-opener.ts
- packages/repo-metadata-lint/test/repo-metadata-lint.ts
- packages/repo-metadata-lint/test/validate.ts
* fix: remove OctokitType
part of #1885
> deps(repo-metadata-lint): update gcf-utils to v14

- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
- packages/sync-repo-settings/src/bot.ts
- packages/sync-repo-settings/src/sync-repo-settings.ts
- packages/sync-repo-settings/test/compatibility-test.ts
- packages/sync-repo-settings/test/fixtures/repository_transferred.json
- packages/sync-repo-settings/test/test.bot.ts
> deps(sync-repo-settings): update gcf-utils to v14

- packages/trusted-contribution/package-lock.json
- packages/trusted-contribution/package.json
- packages/trusted-contribution/src/trusted-contribution.ts
- packages/trusted-contribution/test/trusted-contribution.ts
- packages/trusted-contribution/test/validation-test.ts
> deps(trusted-contribution): update gcf-utils to v14

- packages/snippet-bot/package-lock.json
- packages/snippet-bot/package.json
- packages/snippet-bot/src/snippet-bot.ts
- packages/snippet-bot/test/snippet-bot.ts
> deps(snippet-bot): update gcf-utils to v14

- packages/owlbot-bootstrapper/app/package-lock.json
- packages/owlbot-bootstrapper/app/package.json
- packages/owlbot-bootstrapper/cli/package-lock.json
- packages/owlbot-bootstrapper/cli/package.json
- packages/owlbot-bootstrapper/common-container/package-lock.json
- packages/owlbot-bootstrapper/common-container/package.json
- packages/owlbot-bootstrapper/package-lock.json
- packages/owlbot-bootstrapper/package.json
> deps(owlbot-bootstrapper): update dependencies

- .github/workflows/links.yaml
The line 31 seems to have an error:
https://github.com/googleapis/repo-automation-bots/actions/runs/2914973019
> fix: fix labels in links.yaml

- scripts/update-dependencies.sh
> fix: forcing npm audit fix

- .github/workflows/deps.yaml
- .github/workflows/list-node-path-for-deps.js
- packages/cron-utils/.ncurc.yaml
- packages/gcf-utils/.ncurc.yaml
- packages/policy/.ncurc.yaml
- packages/secret-rotator/.ncurc.yaml
- add config files for ncu
- support sub directries like owlbot-bootstrapper/cli
> build: improve weekly dependency update

- packages/secret-rotator/package-lock.json
- packages/secret-rotator/package.json
I needed to install google-gax
> deps(secret-rotator): update dependencies

- packages/snippet-bot/package-lock.json
- packages/snippet-bot/package.json
- packages/snippet-bot/src/region-tag-parser.ts
- packages/snippet-bot/src/snippet-bot.ts
- packages/snippet-bot/test/region-tag-parser.ts
- packages/snippet-bot/test/snippet-bot.ts
> fix(snippet-bot): use git-file-utils for fetching files

- packages/owlbot-bootstrapper/app/package-lock.json
- packages/owlbot-bootstrapper/app/package.json
- packages/owlbot-bootstrapper/cli/package-lock.json
- packages/owlbot-bootstrapper/cli/package.json
- packages/owlbot-bootstrapper/common-container/package-lock.json
- packages/owlbot-bootstrapper/common-container/package.json
It should address the dependabot alerts.
> deps: security updates for owlbot-bootstrapper

- renovate.json
This will help us to know which package by just a glance
> chore: add directory name to renovate PR title

- packages/auto-label/Dockerfile
- packages/auto-label/cloudbuild.yaml
- packages/auto-label/package-lock.json
- packages/auto-label/package.json
- packages/auto-label/src/server.ts
> build(auto-label): deploy Cloud Run frontend

- packages/blunderbuss/Dockerfile
- packages/blunderbuss/cloudbuild.yaml
- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
- packages/blunderbuss/src/server.ts
> build(blunderbuss): deploy Cloud Run frontend

- packages/policy/package-lock.json
- packages/policy/package.json
- packages/policy/src/cli.ts
- packages/policy/test/test.cli.ts
> refactor(policy): switch meow to yargs

- packages/conventional-commit-lint/Dockerfile
- packages/conventional-commit-lint/cloudbuild.yaml
- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/package.json
- packages/conventional-commit-lint/src/server.ts
> build(ccl): deploy Cloud Run frontend

- packages/failurechecker/Dockerfile
- packages/failurechecker/cloudbuild.yaml
- packages/failurechecker/package-lock.json
- packages/failurechecker/package.json
- packages/failurechecker/src/server.ts
> build(failurechecker): deploy Cloud Run frontend

- packages/flakybot/Dockerfile
- packages/flakybot/cloudbuild.yaml
- packages/flakybot/package-lock.json
- packages/flakybot/package.json
- packages/flakybot/src/server.ts
> build(flakybot): deploy Cloud Run frontend

- packages/generated-files-bot/Dockerfile
- packages/generated-files-bot/cloudbuild.yaml
- packages/generated-files-bot/package-lock.json
- packages/generated-files-bot/package.json
- packages/generated-files-bot/src/server.ts
> build(generated-files-bot): deploy Cloud Run frontend

- packages/header-checker-lint/Dockerfile
- packages/header-checker-lint/cloudbuild.yaml
- packages/header-checker-lint/package-lock.json
- packages/header-checker-lint/package.json
- packages/header-checker-lint/src/server.ts
> build(header-checker-lint): deploy Cloud Run frontend

- packages/merge-on-green/Dockerfile
- packages/merge-on-green/cloudbuild.yaml
- packages/merge-on-green/package-lock.json
- packages/merge-on-green/package.json
- packages/merge-on-green/src/server.ts
> build(mog): deploy Cloud Run frontend

- packages/label-sync/Dockerfile
- packages/label-sync/cloudbuild.yaml
- packages/label-sync/package-lock.json
- packages/label-sync/package.json
- packages/label-sync/src/server.ts
> build(label-sync): deploy Cloud Run frontend

- packages/policy/Dockerfile
- packages/policy/cloudbuild.yaml
- packages/policy/package-lock.json
- packages/policy/package.json
- packages/policy/src/server.ts
> build(policy): deploy Cloud Run frontend

- packages/repo-metadata-lint/Dockerfile
- packages/repo-metadata-lint/cloudbuild.yaml
- packages/repo-metadata-lint/package-lock.json
- packages/repo-metadata-lint/package.json
- packages/repo-metadata-lint/src/server.ts
> build(repo-metadata-lint): deploy Cloud Run frontend

- packages/sync-repo-settings/Dockerfile
- packages/sync-repo-settings/cloudbuild.yaml
- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
- packages/sync-repo-settings/src/server.ts
> build(sync-repo-settings): deploy Cloud Run frontend

- packages/trusted-contribution/Dockerfile
- packages/trusted-contribution/cloudbuild.yaml
- packages/trusted-contribution/package-lock.json
- packages/trusted-contribution/package.json
- packages/trusted-contribution/src/server.ts
> build(trusted-contribution): deploy Cloud Run frontend

- packages/auto-approve/cloudbuild.yaml
- packages/auto-label/cloudbuild.yaml
- packages/blunderbuss/cloudbuild.yaml
- packages/do-not-merge/cloudbuild.yaml
- auto-approve
- auto-label
- blunderbuss
- do-not-merge
fixes #3719
> build: confiure task queue rate

- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
> deps(sync-repo-settings): update gcf-utils to V14.2.0

- packages/cherry-pick-bot/package-lock.json
- packages/cherry-pick-bot/package.json
> deps(cherry-pick-bot): update gcf-utils to V14.2.0

- packages/loadtest-bot/package-lock.json
- packages/loadtest-bot/package.json
> deps(loadtest-bot): update gcf-utils to V14.2.0

- packages/release-trigger/package-lock.json
- packages/release-trigger/package.json
> deps(release-trigger): update gcf-utils to V14.2.0

- packages/flakybot/package-lock.json
- packages/flakybot/package.json
> deps(flakybot): update gcf-utils to V14.2.0

- packages/policy/package-lock.json
- packages/policy/package.json
> deps(policy): update gcf-utils to V14.2.0

- packages/header-checker-lint/package-lock.json
- packages/header-checker-lint/package.json
> deps(header-checker-lint): update gcf-utils to V14.2.0

- packages/label-sync/package-lock.json
- packages/label-sync/package.json
> deps(label-sync): update gcf-utils to V14.2.0

- packages/auto-label/package-lock.json
- packages/auto-label/package.json
> deps(auto-label): update gcf-utils to V14.2.0

- packages/generated-files-bot/package-lock.json
- packages/generated-files-bot/package.json
> deps(generated-files-bot): update gcf-utils to V14.2.0

- packages/merge-on-green/package-lock.json
- packages/merge-on-green/package.json
> deps(merge-on-green): update gcf-utils to V14.2.0

- packages/secret-rotator/package-lock.json
- packages/secret-rotator/package.json
> deps(secret-rotator): update gcf-utils to V14.2.0

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps(release-please): update gcf-utils to V14.2.0

- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
> deps(owl-bot): update gcf-utils to V14.2.0

- packages/auto-approve/package-lock.json
- packages/auto-approve/package.json
> deps(auto-approve): update gcf-utils to v14.2.0

- packages/release-please/cloudbuild.yaml
I'm seeing memory errors in release-please-backend too.
> build(release-please): increase backend memory

- packages/release-trigger/package-lock.json
- packages/release-trigger/package.json
With this version, gcf-utils will cache Cloud Run URL.
> deps(release-trigger): update gcf-utils to V14.2.1

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 14.7.1

- packages/git-file-utils/package-lock.json
- packages/git-file-utils/package.json
- packages/git-file-utils/src/git-file-utils.ts
- packages/git-file-utils/test/git-file-utils.ts
BranchNotFoundError is a child class of FileNotFoundError.
> fix(git-file-utils): throws BranchNotFoundError for missing branch

- packages/snippet-bot/Dockerfile.frontend
- packages/snippet-bot/cloudbuild-test.yaml
- packages/snippet-bot/cloudbuild.yaml
- packages/snippet-bot/package.json
- packages/snippet-bot/src/server-frontend.ts
> build(snippet-bot): deploy Cloud Run backend

- packages/snippet-bot/src/region-tag-parser.ts
- packages/snippet-bot/test/fixtures/diff-no-region-tags.txt
- packages/snippet-bot/test/snippet-bot.ts
> fix(snippet-bot): only fetch files with region tag edit

- packages/release-please/package-lock.json
- packages/release-please/package.json
* maven-workspace: Update all discovered pom.xml within the components (https://github.com/googleapis/release-please/issues/1667) ([ace68d3](https://github.com/googleapis/release-please/commit/ace68d346291db6b591b9b3e1735d12f0a2b2bbc))
* Explicitly sort PRs by updated desc (https://github.com/googleapis/release-please/issues/1685) ([807bda0](https://github.com/googleapis/release-please/commit/807bda0ab3e09e6116b43cd670bab1115bfdbff2))
> deps: update release-please to 14.11.1

- packages/release-please/package-lock.json
- packages/release-please/package.json
Also rebuilds package-lock.json dependencies to update `@xmldom/xmldom` to 0.8.3
> deps: update release-please to v14.11.2

- packages/release-please/package-lock.json
- packages/release-please/package.json
Includes fix for extra large PR bodies
> deps: update release-please to v14.13.0

- packages/release-please/package-lock.json
- packages/release-please/package.json
Includes the fix for updating PRs with extra long bodies
> deps: update release-please to 14.13.1

- packages/snippet-bot/src/utils.ts
- packages/snippet-bot/test/utils.ts
> fix(snippet-bot): trim text when it is too long

- packages/generate-bot/package-lock.json
- packages/generate-bot/package.json
> deps(generate-bot): update recursive-readdir

- .github/workflows/links.yaml
> chore: ignore smee URL in the link checker

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 14.15.3

- packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml
- packages/owlbot-bootstrapper/cli/package-lock.json
- packages/owlbot-bootstrapper/cli/run-trigger-command.ts
- packages/owlbot-bootstrapper/cli/run-trigger.ts
- packages/owlbot-bootstrapper/cli/test/run-trigger.test.ts
- packages/owlbot-bootstrapper/common-container/commands/post-process.ts
- packages/owlbot-bootstrapper/common-container/commands/pre-process.ts
- packages/owlbot-bootstrapper/common-container/interfaces.ts
- packages/owlbot-bootstrapper/common-container/post-process.ts
- packages/owlbot-bootstrapper/common-container/pre-process.ts
- packages/owlbot-bootstrapper/common-container/test/post-process.test.ts
- packages/owlbot-bootstrapper/common-container/test/pre-process.test.ts
> feat: add testing option to quiet issue creation

- packages/owlbot-bootstrapper/cli/run-trigger-command.ts
> fix: instantiate client as the project ID that is running the build trigger, not the one from the env

- renovate.json
We would like renovate to send a release-please update immediately if possible.
> chore(deps): allow renovate to update release-please immediately

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 14.17.2

- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/gcf-bootstrapper.ts
> feat(gcf-utils): store the payload to gcs only when the body is too big

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
Testing the new feature for directly uploading payload to Cloud Task introduced with gcf-utils 14.4.0:
https://github.com/googleapis/repo-automation-bots/releases/tag/gcf-utils-v14.4.0
> chore(canary): testing gcf-utils 14.4.0

- packages/conventional-commit-lint/README.md
> chore(ccl): add always_check_pr_title to README

- packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/4763
> feat: set owl-bot's max APIs per PR to 20

- .github/blunderbuss.yml
Removing myself from some lists.
> chore: update blunderbuss

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 15.1.0

- packages/gcf-utils/src/gcf-utils.ts
- packages/gcf-utils/test/gcf-bootstrapper.ts
This is an alternative to #4866.
Only force error reports to show up in error reporting if it is the final retry attempt. Other attempts will be logged with error severity, but will not appear in the error reporting dashboard.
Towards #4627, #4537
> fix: report errors to error reporting only on the last retry attempt

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
Upgrading to test new error reporting
> deps(canary-bot): update gcf-utils to 14.4.4

- packages/release-please/package-lock.json
- packages/release-please/package.json
We should now stop reporting the first instance of these transient errors.
Fixes #4627
Fixes #4537
> deps(release-please): update gcf-utils to 14.4.4

- packages/flakybot/src/flakybot.ts
- packages/flakybot/test/flakybot.test.ts
> fix(flakybot): skip archived repositories

- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
Updating gcf-utils will make it only report errors to error reporting on the last retry attempt.
Fixes #4794
> deps(blunderbuss): update gcf-utils to 14.4.4

- packages/auto-approve/package-lock.json
- packages/auto-label/package-lock.json
- packages/bot-config-utils/package-lock.json
- packages/cherry-pick-bot/package-lock.json
- packages/conventional-commit-lint/package-lock.json
- packages/datastore-lock/package-lock.json
- packages/do-not-merge/package-lock.json
- packages/failurechecker/package-lock.json
- packages/flakybot/package-lock.json
- packages/generated-files-bot/package-lock.json
- packages/header-checker-lint/package-lock.json
- packages/issue-utils/package-lock.json
- packages/label-sync/package-lock.json
- packages/label-utils/package-lock.json
- packages/loadtest-bot/package-lock.json
- packages/merge-on-green/package-lock.json
- packages/object-selector/package-lock.json
- packages/owl-bot/package-lock.json
- packages/owlbot-bootstrapper/common-container/package-lock.json
- packages/policy/package-lock.json
- packages/release-trigger/package-lock.json
- packages/repo-metadata-lint/package-lock.json
- packages/secret-rotator/package-lock.json
- packages/snippet-bot/package-lock.json
- packages/sync-repo-settings/package-lock.json
- packages/trusted-contribution/package-lock.json
To fix dependabot alerts like https://github.com/googleapis/repo-automation-bots/security/dependabot/827.
> fix: update gcf-utils to update dependency on jsonwebtoken

- packages/blunderbuss/.eslintrc.json
- packages/blunderbuss/package-lock.json
- packages/blunderbuss/package.json
- packages/blunderbuss/src/utils.ts
Probot's context.d.ts broke typescript:
```
src/utils.ts:120:10 - error TS2590: Expression produces a union type that is too complex to represent.
120       ...context.repo(),
```
Instead of https://github.com/googleapis/repo-automation-bots/pull/4877
> chore: typescript 4.9.4 for blunderbuss

- packages/gcf-utils/package-lock.json
One step in fixing dependabot alerts like https://github.com/googleapis/repo-automation-bots/security/dependabot/839
> fix: update dependency on jsonwebtoken

- packages/label-sync/package-lock.json
- packages/merge-on-green/package-lock.json
- packages/mono-repo-publish/package-lock.json
- packages/owl-bot/package-lock.json
- packages/owlbot-bootstrapper/app/package-lock.json
- packages/owlbot-bootstrapper/cli/package-lock.json
This will fix dependabot alerts for JSON5
> fix(deps): npm audit fixes for several packages

- packages/git-file-utils/package-lock.json
- packages/git-file-utils/package.json
This gets us off a broken version of @octokit/types breaking release-please downstream.
> fix(deps): upgrade octokit types

- packages/release-please/package-lock.json
- packages/release-please/package.json
https://github.com/googleapis/release-please/releases/tag/v15.3.0
> deps: update release-please to v15.3.0

- packages/release-trigger/requirements.in
- packages/release-trigger/requirements.txt
Includes fixes for cloud java repo overrides
> deps: update releasetool to 1.10.3

- .github/workflows/ci.yaml
- packages/owl-bot/src/create-pr.ts
- packages/owl-bot/test/create-pr.ts
Fixes #4984
ci: set node version to 14 for unit tests
> fix(owlbot): include newlines when there are multiple nested commits

- packages/mono-repo-publish/src/main.ts
- packages/mono-repo-publish/test/main.test.ts
- packages/mono-repo-publish/test/sample-private-package/package.json
> build: skip publishing private packages 

- packages/mono-repo-publish/src/bin/mono-repo-publish.ts
Publication failures have occasionally been difficult to root cause.
> fix(logging): better logging for publication failures

- packages/owl-bot/src/configs-store.ts
- packages/owl-bot/src/handlers.ts
- packages/owl-bot/test/handlers.ts
> fix: (owl-bot) add ignore files list to refreshConfigs function

- packages/owl-bot/src/copy-code.ts
Fixed one race entirely.
It's not possible to fix another race without a
nonexistant variant of "git push -f" that first confirms the existing branch matches a particular commit hash.  So for that race, I minimized the time window.
Fixes https://github.com/googleapis/repo-automation-bots/issues/5010
> fix: races while updating pull request branches

- packages/policy/README.md
> docs: update policy bot readme

- packages/owl-bot/cloud-build/update-pr.yaml
Fixes https://github.com/googleapis/repo-automation-bots/issues/5031
> feat: validate configs after post processor runs

- packages/bazel-bot/docker-image/Dockerfile
- packages/bazel-bot/docker-image/generate-googleapis-gen.sh
Fixes https://github.com/googleapis/repo-automation-bots/issues/5055
> fix: collect broken commit messages

- packages/auto-approve/README.md
- packages/auto-approve/__snapshots__/check-config.test.js
- packages/auto-approve/package-lock.json
- packages/auto-approve/src/check-pr-v2.ts
- packages/auto-approve/src/process-checks/go/apiary-codegen.ts
- packages/auto-approve/src/valid-pr-schema-v2.json
- packages/auto-approve/test/fixtures/config/valid-schemasV2/valid-schema1.yml
- packages/auto-approve/test/go-apiary-codegen.test.ts
Adds `GoApiaryCodegen` config option. I copied what was done in some other config options and the PRs that added them.
Fixes #5062 🦕
> feat(auto-approve): add GoApiaryCodegen option

- packages/auto-approve/src/process-checks/node/dependency.ts
- packages/auto-approve/test/node-dependency.test.ts
Some strange PRs have prompted looking into the pattern being used.
> fix(auto-approve): update regex for Node

- packages/owl-bot/Dockerfile
- packages/owl-bot/cloud-build/scan-googleapis-gen-and-create-pull-requests.yaml
Attempt the resolution documented [here](https://github.com/orgs/community/discussions/55820) for ` RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset`.
Fixes #5066
> fix: use http/1.1 for post

- packages/owl-bot/cloud-build/update-pr.yaml
> fix: use http/1.1 for post for post-processor

- packages/owl-bot/.eslintrc.json
- packages/owl-bot/src/copy-code.ts
> debug: add more logging to copy-code process around exiting PRs

- packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
- packages/owl-bot/test/commit-post-processor-update.ts
First step towards fixing #5034.
> fix: promote draft copy-code PRs

- packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
- packages/owl-bot/src/copy-code.ts
- packages/owl-bot/src/create-pr.ts
- packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
Step 2 of 3 towards fixing #5034
> fix: flag to enable creating draft pull requests

- packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
> fix: flip flag to turn on *draft* copy code PRs

- packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/5034
> fix: flip flag to create draft prs when copying code

- packages/blunderbuss/src/blunderbuss.ts
Fixes https://github.com/googleapis/repo-automation-bots/issues/5158
> fix: assign reviewers when PR is marked ready for review

- packages/owlbot-bootstrapper/common-container/package-lock.json
> deps: update protobuf and word-wrap dependencies

- packages/auto-approve/package-lock.json
- packages/auto-label/package-lock.json
- packages/blunderbuss/package-lock.json
- packages/bot-config-utils/package-lock.json
- packages/cherry-pick-bot/package-lock.json
- packages/conventional-commit-lint/package-lock.json
- packages/cron-utils/package-lock.json
- packages/datastore-lock/package-lock.json
- packages/do-not-merge/package-lock.json
- packages/failurechecker/package-lock.json
- packages/flakybot/package-lock.json
- packages/generated-files-bot/package-lock.json
- packages/header-checker-lint/package-lock.json
- packages/issue-utils/package-lock.json
- packages/label-sync/package-lock.json
- packages/label-utils/package-lock.json
- packages/loadtest-bot/package-lock.json
- packages/merge-on-green/package-lock.json
- packages/object-selector/package-lock.json
- packages/policy/package-lock.json
- packages/repo-metadata-lint/package-lock.json
- packages/secret-rotator/package-lock.json
- packages/snippet-bot/package-lock.json
- packages/sync-repo-settings/package-lock.json
- packages/trusted-contribution/package-lock.json
> deps: update wordwrap dependency

- packages/canary-bot/package-lock.json
- packages/gcf-utils/package-lock.json
- packages/owl-bot/package-lock.json
- packages/release-please/package-lock.json
- packages/release-trigger/package-lock.json
- release-please-config.json
> deps: update word-wrap to 1.2.5

- packages/owlbot-bootstrapper/common-container/package-lock.json
- packages/owlbot-bootstrapper/common-container/package.json
Fixing an alert for a dependency brought in by nodejs-fetch. This dependency looks unused as there is a more recent node-fetch dependency being used.
> deps: remove unnecessary dependency

- .github/workflows/ci.yaml
- packages/issue-utils/package-lock.json
- packages/issue-utils/package.json
Unblock canary-bot upgrade to node 18
> feat!: require node 18

- packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
- packages/owlbot-bootstrapper/common-container/utils.ts
> fix: use correct Source-Link URL format

- packages/auto-approve/src/process-checks/python/sample-dependency.ts
- packages/auto-approve/test/python-sample-dependency.test.ts
> fix: update dependabot name for auto-approve

- packages/auto-approve/Dockerfile
- packages/auto-label/Dockerfile
- packages/blunderbuss/Dockerfile
- packages/cherry-pick-bot/Dockerfile
- packages/conventional-commit-lint/Dockerfile
- packages/do-not-merge/Dockerfile
- packages/failurechecker/Dockerfile
- packages/generate-bot/templates/Dockerfile
- packages/generated-files-bot/Dockerfile
- packages/header-checker-lint/Dockerfile
- packages/label-sync/Dockerfile
- packages/loadtest-bot/Dockerfile
- packages/merge-on-green/Dockerfile
- packages/owl-bot/Dockerfile.backend
- packages/owl-bot/Dockerfile.frontend
- packages/owlbot-bootstrapper/common-container/Dockerfile
- packages/policy/Dockerfile
- packages/release-trigger/Dockerfile.frontend
- packages/repo-metadata-lint/Dockerfile
- packages/snippet-bot/Dockerfile
- packages/snippet-bot/Dockerfile.frontend
- packages/sync-repo-settings/Dockerfile
- packages/trusted-contribution/Dockerfile
> Chore: Update base node image to v18 in Dockerfile to address OS Vulnerabilities

- packages/owl-bot/src/bin/commands/trigger-build.ts
- packages/owl-bot/src/core.ts
- packages/owl-bot/src/owl-bot.ts
- packages/owl-bot/test/owl-bot.ts
> feat(owl-bot): link to the log access operational document

- packages/release-please/package-lock.json
- packages/release-please/package.json
> deps: update release-please to 16.10.0

- packages/owl-bot/src/core.ts
This will help maintainers get access to the post-processor logs
> fix: add link to GCS log

- packages/owl-bot/src/owl-bot.ts
Log the full datastore connection error stacktrace
> debug: log datastore connection stacktrace

- packages/auto-approve/README.md
- packages/auto-approve/__snapshots__/check-config.test.js
- packages/auto-approve/package-lock.json
- packages/auto-approve/src/check-pr-v2.ts
- packages/auto-approve/src/process-checks/node/owlbot-template-changes.ts
- packages/auto-approve/src/process-checks/owl-bot-api-changes.ts
- packages/auto-approve/src/utils-for-pr-checking.ts
- packages/auto-approve/src/valid-pr-schema-v2.json
- packages/auto-approve/test/additional-validation-for-versioning.test.ts
- packages/auto-approve/test/check-pr-V2.test.ts
- packages/auto-approve/test/check-pr.test.ts
- packages/auto-approve/test/get-pr-info.test.ts
- packages/auto-approve/test/node-owlbot-template-changes.test.ts
- packages/auto-approve/test/owlbot-api-changes.test.ts
- packages/auto-approve/test/owlbot-template-changes.test.ts
feat: add Owlbot Template Changes process check for Node
Creating this according to this doc: https://docs.google.com/document/d/1PxkDU5nZihyxDJ9XvjwX7GvDDdJu8qm4TpoxMUsryz0/edit?tab=t.0#heading=h.689e00isjkgi
> feat: (auto-approve) add owlbot template process check for Node

- .github/workflows/ci.yaml
- packages/auto-approve/cloudbuild.yaml
- packages/auto-approve/package-lock.json
- packages/auto-approve/package.json
> build(auto-approve): test and run against node18

- .github/workflows/ci.yaml
- packages/conventional-commit-lint/cloudbuild.yaml
- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/package.json
- packages/conventional-commit-lint/src/utils.ts
Also forces a rebuild to address b/339332380
ci: test conventional-commit-lint against node18
> build: update conventional-commit-lint to node18

- packages/release-trigger/container-test.yaml
- packages/release-trigger/package-lock.json
Also addresses b/342572688 with a docker rebuild
> deps: update with npm audit fix

- packages/merge-on-green/src/merge-on-green.ts
This should give us more time to run tests and approve PRs.
> feat: increase MOG timeout

- packages/release-trigger/package-lock.json
> deps: update release-trigger deps

- packages/bazel-bot/cloudbuild.yaml
dpebot owned version of bazel-bot https://github.com/apps/gcp-bazel-bot
> build: switch app id and installation

- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
- packages/owl-bot/src/core.ts
> feat(owl-bot): add default retry policy for octokit usage

- packages/owl-bot/cloud-build/force-update-lock-branch.yaml
- packages/owl-bot/cloud-build/update-lock-branch.yaml
Similar to https://github.com/googleapis/repo-automation-bots/pull/5353/files but for `update-lock-branch.yaml` and `force-update-lock-branch.yaml`
> feat(owl-bot): add logs bucket for update lock workflow

- renovate.json5
> chore: use renovate recommended config and only update dockerfile/github-actions

- packages/release-please/README.md
Fixes https://github.com/googleapis/repo-automation-bots/issues/5332
Fixes #5332 🦕
> docs: fixing backtick in monorepoTags row in release-please README

- packages/owl-bot/Dockerfile
> fix: owlbot-cli update Dockerfile to rebuild the image

- packages/conventional-commit-lint/package-lock.json
- packages/conventional-commit-lint/package.json
- packages/conventional-commit-lint/src/utils.ts
- packages/conventional-commit-lint/test/conventional-commit-lint.ts
> fix(deps): update gcf-utils to v16

- packages/label-utils/package-lock.json
- packages/label-utils/package.json
> fix(deps)!: update gcf-utils to v16

- packages/canary-bot/cloudbuild-test.yaml
- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
> fix(deps): update to gcf-utils v16

- .github/workflows/ci.yaml
- packages/failurechecker/package.json
- packages/generate-bot/package-lock.json
- packages/generate-bot/package.json
- packages/generate-bot/templates/package.json.hbs
- packages/generated-files-bot/package.json
- packages/header-checker-lint/package.json
- packages/merge-on-green/package.json
- packages/mono-repo-publish/package.json
- packages/mono-repo-publish/test/sample-private-package/package.json
- packages/owl-bot/package.json
- packages/owlbot-bootstrapper/app/package.json
- packages/owlbot-bootstrapper/cli/package.json
- packages/owlbot-bootstrapper/common-container/package.json
- packages/owlbot-bootstrapper/package.json
- packages/release-brancher/package.json
- packages/release-please/package.json
- packages/release-trigger/package.json
- packages/repo-metadata-lint/package.json
- packages/secret-rotator/package.json
- packages/snippet-bot/package.json
- packages/sync-repo-settings/package.json
All bots are already running against node 18
> ci: test all bots against node 18

- packages/merge-on-green/package-lock.json
- packages/owlbot-bootstrapper/app/package-lock.json
- packages/release-please/package-lock.json
- packages/secret-rotator/package-lock.json
Update express dependencies to latest compatible version: 4.20.0
> chore(deps): update express dependencies

- packages/owlbot-bootstrapper/cli/package-lock.json
- packages/owlbot-bootstrapper/cli/package.json
Updates gax and other dependencies.
> deps: update google-cloud/cloudbuild to latest major version

- packages/merge-on-green/cloudbuild.yaml
> build: deploy m-o-g function on node18

- serverless-scheduler-proxy/go.mod
See https://buganizer.corp.google.com/issues/369909474#comment5
> chore: update go to 1.23.2

- packages/gcf-utils/src/gcf-utils.ts
> fix: handleScheduledRepository to skip suspended repositories

- .kokoro/publish.sh
- .trampolinerc
publish.sh to take RELEASE_PACKAGE environment variable so that it does not rely on GitHub in releasing.
> ci: update publish.sh to take RELEASE_PACKAGE

- packages/secret-rotator/Dockerfile.cli
- packages/secret-rotator/cloudbuild-cli.yaml
- packages/secret-rotator/package-lock.json
- packages/secret-rotator/package.json
- packages/secret-rotator/src/cli.ts
This will allow us to migrate to Cloud Run jobs instead of needing a Cloud Run service waiting for HTTP requests.
> feat: add cli and Docker image

- packages/bazel-bot/docker-image/generate-googleapis-gen.sh
> fix: bazelbot to limit bazel job count

- packages/release-please/package-lock.json
- packages/release-please/package.json
Updates release-please to 16.14.4 and jsonpath-plus to 10.1.0
> deps: update release-please to 16.14.4

- packages/canary-bot/cloudbuild.yaml
> chore: retag canary-bot-cloud-run as canary-bot

- .github/CODEOWNERS
github-automation team is the code owner for the entire repo
> chore: cleanup CODEOWNERS

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
- packages/canary-bot/src/server.ts
feat: allow configuring task-caller via env variables
deps: update gcf-utils to 16.2.1
> feat: allow running canary-bot frontend for both GCF and Cloud Run backends

- packages/release-trigger/Dockerfile
> fix: release-trigger: use slim base image

- packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
- packages/conventional-commit-lint/src/utils.ts
This was an API validation error
Fixes #5623
> fix: PR title mismatch check needs name field

- packages/auto-approve/cloudbuild.yaml
- packages/auto-label/cloudbuild.yaml
- packages/blunderbuss/cloudbuild.yaml
- packages/conventional-commit-lint/cloudbuild.yaml
- packages/do-not-merge/cloudbuild.yaml
- packages/failurechecker/cloudbuild.yaml
- packages/generated-files-bot/cloudbuild.yaml
- packages/header-checker-lint/cloudbuild.yaml
- packages/label-sync/cloudbuild.yaml
- packages/merge-on-green/cloudbuild.yaml
- packages/repo-metadata-lint/cloudbuild.yaml
- packages/sync-repo-settings/cloudbuild.yaml
- packages/trusted-contribution/cloudbuild.yaml
custom service accounts require specifying logs configuration
> build: specify logs bucket for GCF-based bots

- packages/snippet-bot/src/snippet-bot.ts
> feat(snippet-bot): add android org to allowlist

- packages/snippet-bot/src/snippet-bot.ts
> feat(snippet-bot): add terraform-google-modules to allowlist

- packages/owlbot-bootstrapper/cli/package-lock.json
Ran `npm audit fix` for packages/owlbot-bootstrapper/cli
Fixes [security#1823](https://github.com/googleapis/repo-automation-bots/security/dependabot/1823)
> fix: Upgrade dependencies in packages/owlbot-bootstrapper/cli

- packages/sync-repo-settings/README.md
> docs(sync-repo-settings): fix typo in restrictsPushes

- packages/label-utils/package-lock.json
- packages/label-utils/package.json
- packages/label-utils/test/label-utils.ts
- packages/label-utils/tsconfig.json
fix(deps)!: update @google-automations/datastore-lock to v7
> fix(deps)!: update gcf-utils to v17

- packages/header-checker-lint/package-lock.json
- packages/header-checker-lint/package.json
- packages/header-checker-lint/test/header-checker-lint.ts
> deps(header-checker-lint): Updating gcf-utils and bot-config-utils

- packages/release-please/package-lock.json
- packages/release-please/package.json
- packages/release-please/src/release-please.ts
- packages/release-please/test/compatibility-test.ts
- packages/release-please/test/release-please.ts
- packages/release-please/test/runner.ts
- packages/release-please/tsconfig.json
deps(release-please): update gcf-utils to v17
> deps(release-please): update release-please to v17

- packages/loadtest-bot/package-lock.json
- packages/loadtest-bot/package.json
- packages/loadtest-bot/test/test.ts
b/402728578
Reference: https://github.com/googleapis/repo-automation-bots/pull/5699/files#diff-ae072c603be51e08e75df14952362c4f8898ed32caee6449132b61ee1fe267d7
> deps(loadtest-bot): upgrade gcf-utils deps

- packages/release-brancher/package-lock.json
- packages/release-brancher/package.json
- packages/release-brancher/src/release-brancher.ts
- packages/release-brancher/test/release-brancher.ts
Fixes [#2103](https://github.com/googleapis/repo-automation-bots/security/dependabot/2103)
> chore(release-brancher): upgrade octokit dependencies to fix security vulnerability

- packages/generated-files-bot/package-lock.json
- packages/generated-files-bot/package.json
- packages/generated-files-bot/test/generated-files-bot.ts
> chore: upgrade deps for generated-files-bot

- packages/release-trigger/package-lock.json
- packages/release-trigger/package.json
- packages/release-trigger/test/bot.ts
- packages/release-trigger/test/release-trigger.ts
> chore: upgrade deps for release-trigger

- packages/sync-repo-settings/package-lock.json
- packages/sync-repo-settings/package.json
- packages/sync-repo-settings/src/cli.ts
- packages/sync-repo-settings/test/compatibility-test.ts
- packages/sync-repo-settings/test/sync-repo-settings.ts
- packages/sync-repo-settings/test/test.bot.ts
> chore: upgrade deps for sync-repo-settings

- packages/release-please/src/release-please.ts
This should make it easier to filter logs for repositories that use multiple configurations
> debug(release-please): add configuration options to structured logging

- packages/failurechecker/package-lock.json
- packages/failurechecker/package.json
- packages/failurechecker/test/failurechecker.ts
> chore: upgrade deps for failurechecker

- packages/owl-bot/package-lock.json
- packages/owl-bot/package.json
Fixes [2059](https://github.com/googleapis/repo-automation-bots/security/dependabot/2059)
> chore(owlbot): update code-suggester to latest to remove octokit vulnerability

- packages/canary-bot/Dockerfile
> chore(canary-bot): Use alpine for runtime container image

- packages/release-trigger/Dockerfile.frontend
This change only touches the frontend where it receives the
requests from GitHub and puts it to Cloud Tasks.
The backend container image uses Python to invoke the releasetool.
For the Python dependency, this change doesn't touch the backend
Dockerfile.
b/419000460
> chore(release-trigger): Use alpine in Release Trigger frontend

- packages/release-please/cloudbuild.yaml
- packages/release-please/src/release-please.ts
we will configure this value as part of terraform env.
> feat: add ability to block requests to release-please by repo-owner

- README.md
Org admins can still edit existing installations
> docs: remove links to apps

- packages/owl-bot/Dockerfile.backend
- packages/owl-bot/cloudbuild-test.yaml
> build: Use MOSS-approved base image for owl-bot-backend

- packages/cherry-pick-bot/Dockerfile
> build(cherry-pick-bot): update dependencies and base image

- packages/release-trigger/Dockerfile
- packages/release-trigger/Dockerfile.frontend
- packages/release-trigger/container-test.yaml
Reverts googleapis/repo-automation-bots#5788
> revert: build: update python to 3.13, update base image

- .release-please-manifest.json
- packages/object-selector/README.md
- release-please-config.json
Towards https://github.com/googleapis/librarian/issues/370
> chore: mark object-selector library as deprecated

- packages/generated-files-bot/README.md
Towards https://github.com/googleapis/librarian/issues/361
> chore: mark generated-files-bot as deprecated

- packages/canary-bot/package-lock.json
- packages/canary-bot/package.json
Testing out new allowlist/blocklist feature.
Towards https://github.com/googleapis/librarian/issues/824
> deps(canary-bot): update gcf-utils to 17.1.0

- packages/loadtest-bot/README.md
Fixes https://github.com/googleapis/librarian/issues/367
> chore: mark loadtest-bot as deprecated

- packages/header-checker-lint/README.md
Fixes https://github.com/googleapis/librarian/issues/363
> chore: mark header-checker-lint as deprecated

- packages/auto-approve/README.md
Fixes https://github.com/googleapis/librarian/issues/345
> chore: mark auto-approve as deprecated

- packages/generate-bot/README.md
- packages/generate-bot/package.json
Fixes https://github.com/googleapis/librarian/issues/360
> chore: mark generate-bot as deprecated

- packages/do-not-merge/README.md
Fixes https://github.com/googleapis/librarian/issues/356
> chore: mark do-not-merge bot as deprecated

- packages/sync-repo-settings/README.md
Fixes https://github.com/googleapis/librarian/issues/380
> chore: mark sync-repo-settings as deprecated

- packages/flakybot/README.md
Fixes https://github.com/googleapis/librarian/issues/358
> chore: mark flakybot as deprecated

- packages/gcf-utils/package-lock.json
- packages/gcf-utils/package.json
Updates form-data to fix security vulnerability.
Fixes [#2311](https://github.com/googleapis/repo-automation-bots/security/dependabot/2311) 🦕
> chore: update lock file for gcf-utils

- packages/release-please/README.md
Fixes https://github.com/googleapis/librarian/issues/375
> docs: mark release-please as deprecated

- packages/owlbot-bootstrapper/cli/package-lock.json
- packages/owlbot-bootstrapper/package-lock.json
Fixes #<2273> 🦕
https://github.com/googleapis/repo-automation-bots/security/dependabot/2292
> chore(owlbot-bootstrapper): regenerate package-lock.json

- packages/cron-utils/package-lock.json
Fixes https://github.com/googleapis/repo-automation-bots/security/dependabot/2271
> chore(cron-util): regenerate package-lock.json

- packages/bot-config-utils/package-lock.json
Fixes [#<2272> 🦕](https://github.com/googleapis/repo-automation-bots/security/dependabot/2272)
> chore(fix-bot-utils): regenerate package-lock.json

- packages/gcf-utils/package-lock.json
- packages/gcf-utils/package.json
https://github.com/googleapis/repo-automation-bots/security/dependabot/2366
> fix(deps): upgrade pino to fix fast-redact vulnerabilty
